### ISSUE TITLE
Can't set PAC on newer Windows 10 versions

### ISSUE THREAD

**Issue by orbancanon** [getlantern/lantern#5346] opened 2016-10-10 07:21 UTC
Reported by user at https://github.com/getlantern/forum/issues/1465#issuecomment-252542781. Manually toggling "Set system proxy" doesn't work.

User's WIN10 version is 14942. Some user reported 14936 didn't work either, though the reason can potentially be different.

**Comment by joesis** [comment] 2016-10-10 08:05
Bumping up to P0 and adding to backlog, as users experiencing this issue just can't use Lantern, and Windows 10 forces auto-update.

**Comment by p3rcya** [comment] 2016-10-10 08:09
Many windows 10 complaints here https://github.com/getlantern/forum/issues/1418#issuecomment-252549809

**Comment by joesis** [comment] 2016-10-10 12:23
Checked that Lantern works fine on Windows 10 version 1607 (OS Build 14936.0) VM. From https://technet.microsoft.com/en-us/windows/release-info.aspx, it's the current production version.  I'm trying to install all updates to see if one of them causes the issue.

The OS version in https://github.com/getlantern/forum/issues/1465 is OS Build 14942, which is for technical review. Lower to P1.

**Comment by joesis** [comment] 2016-10-10 12:59
It still works on build 14926.222

**Comment by joesis** [comment] 2016-10-12 09:10
So it may not directly relate to Windows version. As per @orbancanon 's confirmation with the user at https://github.com/getlantern/forum/issues/1465#issuecomment-253126709 , standalone `pac-cmd` can set PAC correctly, while Lantern can't.

**Comment by joesis** [comment] 2016-10-13 12:38
A few relevant logs:
https://github.com/getlantern/forum/files/518858/lantern.zip
https://github.com/getlantern/forum/files/521538/lantern.zip
https://github.com/getlantern/forum/files/518928/logs.zip
https://github.com/getlantern/forum/files/517439/logs.zip

**Comment by myleshorton** [comment] 2016-10-13 19:31
I think this might be the result of the random port change and this ticket:

https://github.com/getlantern/lantern-internal/issues/255

Is it only failing on Edge/IE for these users?

**Comment by joesis** [comment] 2016-10-13 22:50
@myleshorton From the forum, users only started experiencing this after auto-updated their Windows 10. The Lantern PAC URL just can't be set to OS. Should be a new issue.

**Comment by myleshorton** [comment] 2016-10-14 03:47
Oh interesting @joesis. You don't have an updated win10 by chance do you? It's working fine on my version.

**Comment by joesis** [comment] 2016-10-14 06:31
The hard part is, I couldn't reproduce it either. However, several users reported the very same issue recently. From limited info at https://github.com/getlantern/forum/issues/1466#issuecomment-252803712, Lantern worked again after reverted from build 14936 back to build 14931.

**Comment by myleshorton** [comment] 2016-10-14 14:45
OK thanks @joesis. I might be able to reproduce it on another win10 machine at home, but I can't test that again until tonight. Added to TODO along with #5354.

**Comment by myleshorton** [comment] 2016-10-14 16:36
I'm on 1607 as well @joesis, and it's generally working for me although the auto-launch after install looks like it might be failing -- checking that.

**Comment by myleshorton** [comment] 2016-10-14 16:37
hmmn, not that's working fine actually.

**Comment by orbancanon** [comment] 2016-10-17 14:13
A special Windows binary @joesis built based on `devel` but with a different `pac-cmd` does work for one user, though the intention was to collect more detailed log. Waiting for user's log. The cause is yet clear.

**Comment by p3rcya** [comment] 2016-10-17 17:19
User reported problem with Windows 10 Pro Insider Preview Build 14936.rs_prerelease.160932-1700

https://github.com/getlantern/lantern/issues/5342#issuecomment-254033104

**Comment by oxtoacart** [comment] 2016-10-17 21:31
I wonder if a build from [here](https://github.com/getlantern/flashlight/pull/88) fixes the issue?

**Comment by orbancanon** [comment] 2016-10-18 11:25
I added a feature to `pac-cmd` to show existing PAC setting and modified `pac.go` to verify the PAC is actually set.

The cause for https://github.com/getlantern/forum/issues/1465 is quite interesting. A 64bit `pac-cmd` executable works normally on user's PC. A 32bit `pac-cmd` executable can also set and show the PAC setting, but the setting doesn't show up in the control panel dialog! It doesn't take effect either. It must be something with the Windows 10 version.

Below are two screenshots uses different Lantern test binaries. The only difference is embedding 32bit or 64bit `pac-cmd` (note the Lantern version showing on the UI).

![image](https://cloud.githubusercontent.com/assets/20335954/19474154/f6f9798a-9560-11e6-96ff-0bf124a43b6e.png)

![image](https://cloud.githubusercontent.com/assets/20335954/19474191/20bff294-9561-11e6-96e9-a3aa3daae8f9.png)

One immediate solution would be to embed both 32bit and 64bit Windows executable, like what we do for Linux.

**Comment by oxtoacart** [comment] 2016-10-18 11:28
@orbancanon Awesome troubleshooting!

**Comment by oxtoacart** [comment] 2016-10-18 11:29
@orbancanon We've been thinking about switching away from using a PAC file to just setting the HTTP and HTTPS proxies. This binary does that - https://github.com/getlantern/sysproxy-cmd/tree/issue3039/binaries/windows

It's only 32 bit, but I'm curious if it works with your Windows 10?

**Comment by orbancanon** [comment] 2016-10-18 12:15
@oxtoacart The 32bit binary works on my Windows 10 VM, however, it doesn't work on the specific user's PC, and presumably other users experiencing the very same symptom. That's why I had to build a test Lantern binary for them to test.

I guess we need to do the same for `sysproxy` because it uses the same set of syscall as `pac`.

Maybe postpone switching to `sysproxy` until next version? More testing would be required.

**Comment by oxtoacart** [comment] 2016-10-18 12:27
@orbancanon Yes, definitely don't want to switch yet. I was just curious mostly.

**Comment by orbancanon** [comment] 2016-10-18 12:54
Well, to be precise, it's not 32bit vs 64bit binary. It's the binary built on 32bit Windows 7 versus binary built on 64bit Windows 10, both with same set of toolchain (GnuWin32 + MingW-W64), with [same set of compile/link flags](https://github.com/getlantern/pac-cmd/blob/master/Makefile#L6). Not clear what's going on. Maybe something with the `wininet` library where `InternetSetOption` syscall resides.

**Comment by oxtoacart** [comment] 2016-10-18 12:57
Ah, interesting. Based on those flags, both should be 32 bit binaries. I wonder if the version built on Windows 10 works on Windows XP and 7. If it does, I say we just build a single binary that way.

**Comment by orbancanon** [comment] 2016-10-18 13:02
No @oxtoacart . The binary built on Windows 10 doesn't work on my 32 bit Windows 7.

**Comment by oxtoacart** [comment] 2016-10-18 13:05
@orbancanon Drats.

**Comment by orbancanon** [comment] 2016-10-18 13:07
The error message is as below. By inspecting the exe file, it seems both has 32bit PE flag. Confused...

>  C:\Users\IEUser\AppData\Roaming\byteexec\pac-cmd.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

**Comment by oxtoacart** [comment] 2016-10-18 13:15
@orbancanon What is the exact mingw gcc executable that you're using on Windows 10 and Windows 7?

**Comment by oxtoacart** [comment] 2016-10-18 13:17
I suspect that what may be happening with the binary built from Windows 10 is that it's a 32-bit binary but linked against the 64-bit Windows libraries because it's using the mingw-w64 compiler. You may have the mingw-w32 compiler installed too, which may produce the results you want.

**Comment by myleshorton** [comment] 2016-11-14 19:13
Closing this one @joesis thanks!

**Closed by myleshorton** 2016-11-14 19:13 UTC
Labels: P1
