### ISSUE TITLE
peerdnsreg leaking memory

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2174] opened 2015-01-15 18:57 UTC

**Comment by oxtoacart** [comment] 2015-01-16 04:54
@myleshorton I went to deploy the fix for this and while updating the godeps noticed that peerscanner is using an old version of an API in flashlight, so we'll need to make some updates there.  It's actually using flashlight to make a plain fronted request, so we can probably use the new fronted library directly.

**Comment by myleshorton** [comment] 2015-01-16 04:57
Yeah I actually just saw that and tried deploying as well. Honestly this is one of the really tricky parts about non-versioned libraries, but we should be able to use HttpClientUsing without much trouble. I can give that a look. It is odd peerdnsreg all of a sudden started using so much memory. I wonder what changed.

**Comment by myleshorton** [comment] 2015-01-16 05:11
I'll knock this out tomorrow!

**Comment by myleshorton** [comment] 2015-01-16 22:27
This is being addressed in https://github.com/getlantern/peerscanner/pull/4

**Comment by myleshorton** [comment] 2015-01-17 00:25
This is still an issue with the latest changes @oxtoacart -- memory growing really steadily. Still unclear what changed to cause this issue, but it's clearly a problem. Possibly something on CloudFlare's side?

**Comment by oxtoacart** [comment] 2015-01-17 01:44
@myleshorton See comment here https://github.com/getlantern/peerscanner/pull/4/files#diff-34c0958fc0c14f1d7f66cc50a1658fc8R249

**Comment by oxtoacart** [comment] 2015-01-17 03:20
@myleshorton I went ahead and updated the issue-2174 branch to use the updated fronted and pushed to heroku.

**Comment by oxtoacart** [comment] 2015-01-17 10:40
@myleshorton There was still gigantic memory growth, so I hacked together a version of the original peerscanner that pulls in just the update to the cloudflare lib, minimizing other changes.

https://github.com/getlantern/peerscanner/tree/issue-2174-hack

I've deployed it and am keeping my fingers crossed.

**Comment by myleshorton** [comment] 2015-01-17 14:43
So the two earlier changes without any of the connection pooling tweaks I think had a significant positive impact. In particular I actually think just the change to the new GC in 1.3.3 and in 1.4.1 versus whatever we were running before had a huge impact. If you look at the memory growth, both those versions would do a massive GC much sooner than the prior version and would also grow much slower. The 1.4.1 version looked like it might actually do the more massive GC in time for us to be below Heroku's 2x dyno threshold, which is really the main thing we need at this point.

That said, we really should get to the bottom of this. Here's what my quick memory profiling turned up, which could support something along the lines of the connection pool theory:

(pprof) top5
12.03MB of 26.54MB total (45.32%)
Dropped 100 nodes (cum <= 0.13MB)
Showing top 5 nodes out of 86 (cum >= 1.50MB)
      flat  flat%   sum%        cum   cum%
    5.02MB 18.91% 18.91%     5.02MB 18.91%  bufio.NewReaderSize
    2.50MB  9.43% 28.34%     2.50MB  9.43%  crypto/tls.(*block).reserve
    1.51MB  5.67% 34.01%     1.51MB  5.67%  bufio.NewWriter
    1.50MB  5.65% 39.67%        6MB 22.61%  crypto/x509.parseCertificate
    1.50MB  5.65% 45.32%     1.50MB  5.65%  newproc_m

**Comment by myleshorton** [comment] 2015-01-17 14:44
Oh, also I think that change to fronted will also be valuable for Android, as we probably want to be a little less aggressive with pooling there.

**Comment by myleshorton** [comment] 2015-01-17 15:43
Actually the 1.4.1 GC profile still maxes out at just over what a 2x dyno can handle unfortunately -- GCs at 1.1 GB, and a 2X has 1GB. I did just revert to the 1.4.1 version, though, as it performs much better.

**Comment by oxtoacart** [comment] 2015-01-17 15:47
Cool.  I did just notice that going back to the old version didn't help
with the leak :(

Cheers,
Ox

-----------------------------------------------------------------------------------------

"I love people who harness themselves, an ox to a heavy cart,
who pull like water buffalo, with massive patience,
who strain in the mud and the muck to move things forward,
who do what has to be done, again and again."

- Marge Piercy

**Comment by oxtoacart** [comment] 2015-01-17 15:49
@myleshorton I'm planning to take a comprehensive look at peer registration this weekend, including this ticket as well as:

https://github.com/getlantern/lantern/issues/1924
https://github.com/getlantern/lantern/issues/1993
https://github.com/getlantern/lantern/issues/2132

**Comment by myleshorton** [comment] 2015-01-17 16:02
> Cool.  I did just notice that going back to the old version didn't help
> with the leak :(

Right the leak is still there in all cases, but the memory maxes out at 1.1 GB with 1.4.1 versus about 3.4 GB with the old 1.3.1, which unfortunately is not quite good enough.

**Comment by oxtoacart** [comment] 2015-01-19 04:24
@myleshorton Here's a refactored version of peerscanner - https://github.com/getlantern/flashlight-build/tree/peerscanner/src/github.com/getlantern/peerscanner.  Note that I went ahead and integrated it into flashlight-build.

It's built to run on a Digital Ocean instance, configured per these changes - https://github.com/getlantern/lantern_aws/pull/34.  A test version is already up and running at ps-singapore-001, accessible via CloudFlare at https://peerscanner.getiantem.org.

The old peerscanner has been changed to simply forward requests to the new one, per these changes - https://github.com/getlantern/peerscanner/pull/5

I still need to update flashlight to send the registration messages.

The benefits of this new approach are:

1. Realtime instead of batch operation, reduces amount of time between checks for each server
2. Fewer API calls to CloudFlare (in particular we only enumerate the full DNS once) and consequently much less object creation
3. Ability to run on much cheaper Digital Ocean hosting
4. Deregistering of fallbacks should reduce timeout errors when using flashlight

**Comment by oxtoacart** [comment] 2015-01-19 21:50
@myleshorton I figured out the root cause of the memory growth - https://github.com/getlantern/lantern/issues/2178

**Comment by myleshorton** [comment] 2015-01-20 05:48
Awesome @oxtoacart! It would be great to deploy the memory leak fix ASAP, as not the memory is growing to 8GB even on the PX dyno, so even those aren't enough. Sounds like we should also deploy that fix to Lantern itelf and possibly all flashlight servers is that right?

I'm honestly a little wary of getting into a large refactoring that's addressing much lower priority issues, and especially wary of getting rid of our ability to auto-scale on Heroku, but we can talk about it.

**Comment by oxtoacart** [comment] 2015-01-20 14:05
> Awesome @oxtoacart! It would be great to deploy the memory leak fix ASAP, as not the memory is growing to 8GB even on the PX dyno, so even those aren't enough. Sounds like we should also deploy that fix to Lantern itelf and possibly all flashlight servers is that right?

Agreed.

> I'm honestly a little wary of getting into a large refactoring that's addressing much lower priority issues, and especially wary of getting rid of our ability to auto-scale on Heroku, but we can talk about it.

1. As written, the clock process can't scale horizontally anyway

2. I'm convinced that the domain fronted user experience would be better if we are able to detect unresponsive hosts more quickly, and also if we remove unresponsive fallbacks from rotation.  I say this because I see errors from CloudFlare like "origin down" as well as timeouts even when I'm running against fallbacks.

**Comment by oxtoacart** [comment] 2015-01-20 14:56
Oh, also, while in here I also cleaned up another couple of things:

1. Handle the case when a new name is reported for the same IP

2. Remove ips from rotation that don't have a corresponding individual entry (not a big deal, but just some nice housekeeping)

**Comment by myleshorton** [comment] 2015-01-20 15:09
OK, well let's give it a shot, although I do want to be super disciplined about only addressing the highest priority things going forward, as the big danger is a cycle of continually fixing bugs in things that don't matter as much. I agree the CloudFlare issues are key. So are you saying this might fix #2141, or are you saying there's an unticketed P1 issue for origins being down? 

Is it possible to deploy just the enproxy fix now? That's a major production problem at this point. 

The diff also appears to contain a bunch of stuff from other unmerged pull requests. Is that right?

**Comment by oxtoacart** [comment] 2015-01-20 15:32
> OK, well let's give it a shot, although I do want to be super disciplined about only addressing the highest priority things going forward, as the big danger is a cycle of continually fixing bugs in things that don't matter as much. I agree the CloudFlare issues are key. So are you saying this might fix #2141, or are you saying there's an unticketed P1 issue for origins being down?

Yes, sorry, should have ticketed that - https://github.com/getlantern/lantern/issues/2179.  Also, in general I'm wondering if getting the domain-fronted experience rock solid will help with things like the XMPP issues that we see (#2006), users not getting their fallback assignment, etc.  Lastly, I don't think I would have discovered the enproxy issue if I hadn't been digging into this, so I think it's pretty big win in a variety of areas that actually matter a whole bunch.

> Is it possible to deploy just the enproxy fix now? That's a major production problem at this point.

Almost.  I'm still in the middle of testing enproxy and making some further tweaks, including cleaning up the close sequence as I noticed an occasional leak there.  Once enproxy looks good, we can definitely deploy to peerdnsreg.  For now, I just bounced the clock dyno to bring memory back down.  Other than having to bounce it from time to time, do you see the current leak causing any other problems?

> The diff also appears to contain a bunch of stuff from other unmerged pull requests. Is that right?

Yes, which is why I haven't pull requested it.  I manually merged a bunch of pending PRs into this branch because I didn't want to have to redo my changes after those land, and because I wanted to test my changes in the context of what I anticipate will be the final product.  PRs hanging around for a week or more has costs.

**Comment by myleshorton** [comment] 2015-01-20 18:30
> Yes, sorry, should have ticketed that - #2179. Also, in general I'm wondering if getting the domain-fronted experience rock solid will help with things like the XMPP issues that we see (#2006), users not getting their fallback assignment, etc. Lastly, I don't think I would have discovered the enproxy issue if I hadn't been digging into this, so I think it's pretty big win in a variety of areas that actually matter a whole bunch.

Cool yeah I agree really nailing domain fronting is still super high priority. Users continually talk about how slow Lantern is too, although it's unclear if that's always related to domain fronting. We should do more in-country testing for that probably.

I'm still baffled as to why the memory all of a sudden started becoming an issue on peerdnsreg -- very odd. Did the enproxy connection leak issue also affect our code from way back in Oct or whenever we did the last peerdnsreg update?

**Comment by oxtoacart** [comment] 2015-01-20 18:42
> I'm still baffled as to why the memory all of a sudden started becoming an issue on peerdnsreg -- very odd. Did the enproxy connection leak issue also affect our code from way back in Oct or whenever we did the last peerdnsreg update?

It's likely that it did not, though I'm not 100% sure.  The other possible explanation is that something in Google's response changed, as the problem only happens under specific circumstances (in particular a redirect).  If I had to be though, I'd bet on it being a regression.

**Comment by oxtoacart** [comment] 2015-01-21 03:32
So, I deployed a new build to peerdnsreg that incorporates the latest enproxy code, but memory is still growing.  So it looks like the memory growth is being caused by something else.

On a positive note, the enproxy fix will hopefully help with this other error that I saw in the peerdnsreg log:

`Jan 20 19:17:31 cloudflare-peerdnsreg app/web.2:  2015/01/21 03:17:30 http: Accept error: accept tcp [::]:19641: too many open files; retrying in 1s `

**Comment by zjhxmjl** [comment] 2015-01-21 03:49
@oxtoacart,sorry i can't see what you mean?

**Comment by oxtoacart** [comment] 2015-01-21 04:12
Interestingly, the refactored peerscanner using the same enproxy, running on ps-singapore-001 is not experiencing any memory growth.

**Comment by myleshorton** [comment] 2015-01-21 06:47
Thanks @oxtoacart very interesting. Well, that's a pretty good argument for using the new one! Are you already forwarding traffic to it from the old peerscanner?

**Comment by oxtoacart** [comment] 2015-01-21 07:32
I'm not forwarding traffic yet, but the new one has been scanning all of the fallbacks.  I'll do an experiment tomorrow where I forward all of the traffic to the new one.  I'll let you know how that goes.

**Comment by oxtoacart** [comment] 2015-01-21 17:43
@myleshorton I'm now forwarding traffic from Heroku to our new DO peerscanner.  I've confirmed that peers are getting registered (both by running my own peer and observing traffic, as well as inspecting CloudFlare DNS).  The fallbacks rotation is also populated, and I'm currently browsing through roundrobin.getiantem.org and stuff seems to be working fine.

The DO peerscanner server is currently a $20 per month instance with 2 CPUs.  15 minute load average is around 0.25, or 12.5% of capacity.  Memory RES for process is around 50MB and holding steady.

The DO peerscanner server is running the same monitoring script as the flashlight servers and will report to fallback-alarms if load average exceeds 70% of capacity, and will automatically restart at 90% of capacity.

Meanwhile, memory and load average for the web dynos are super low, so I'm actually going to scale them down to a single 1X dyno.

```
2015-01-21T17:41:52.394591+00:00 heroku[web.2]: source=web.2 dyno=heroku.27587875.2c2513a5-ffa2-476b-8f9a-11d6e04e84fb sample#load_avg_1m=0.00 sample#load_avg_5m=0.00
2015-01-21T17:41:52.394718+00:00 heroku[web.2]: source=web.2 dyno=heroku.27587875.2c2513a5-ffa2-476b-8f9a-11d6e04e84fb sample#memory_total=4.10MB sample#memory_rss=4.10MB sample#memory_cache=0.00MB sample#memory_swap=0.00MB sample#memory_pgpgin=1562pages sample#memory_pgpgout=513pages
```

I'll continue to keep an eye on it while I prepare the pull requests for review.

**Comment by myleshorton** [comment] 2015-01-21 18:02
Awesome! Very odd it behaves so differently on DO. I wonder why.

I think the only thing we'll really need on that box is some sort of
comparable monitoring.

On Wednesday, January 21, 2015, oxtoacart <notifications@github.com> wrote:

> @myleshorton <https://github.com/myleshorton> I'm now forwarding traffic
> from Heroku to our new DO peerscanner. I've confirmed that peers are
> getting registered (both by running my own peer and observing traffic, as
> well as inspecting CloudFlare DNS). The fallbacks rotation is also
> populated, and I'm currently browsing through roundrobin.getiantem.org
> and stuff seems to be working fine.
>
> The DO peerscanner server is currently a $20 per month instance with 2
> CPUs. 15 minute load average is around 0.25, or 12.5% of capacity. Memory
> RES for process is around 50MB and holding steady.
>
> The DO peerscanner server is running the same monitoring script as the
> flashlight servers and will report to fallback-alarms if load average
> exceeds 70% of capacity, and will automatically restart at 90% of capacity.
>
> Meanwhile, memory and load average for the web dynos are super low, so I'm
> actually going to scale them down to a single 1X dyno.
>
> 2015-01-21T17:41:52.394591+00:00 heroku[web.2]: source=web.2 dyno=heroku.27587875.2c2513a5-ffa2-476b-8f9a-11d6e04e84fb sample#load_avg_1m=0.00 sample#load_avg_5m=0.00
> 2015-01-21T17:41:52.394718+00:00 heroku[web.2]: source=web.2 dyno=heroku.27587875.2c2513a5-ffa2-476b-8f9a-11d6e04e84fb sample#memory_total=4.10MB sample#memory_rss=4.10MB sample#memory_cache=0.00MB sample#memory_swap=0.00MB sample#memory_pgpgin=1562pages sample#memory_pgpgout=513pages
>
> I'll continue to keep an eye on it while I prepare the pull requests for
> review.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2174#issuecomment-70884695>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment] 2015-01-21 18:16
> Awesome! Very odd it behaves so differently on DO. I wonder why.

The code is very different.  The old code was extremely chatty with CloudFlare, frequently fetching the entire set of DNS entries.  The new code only does that once, at startup, and the only subsequent communication with CloudFlare is to register/deregister specific hosts.  Also, the connectivity check goes directly through the host under test rather than through CloudFlare, although I don't think that would make much of a difference.

I've noticed that there still appears to be some sort of file descriptor leak on connections to CloudFlare, so there must be a lingering bug in the cloudflare library that we're using.  It's much slower than on the old app because we don't call CloudFlare that often, but it's still there.

```
peerscann 2190 lantern  121u  IPv6  95588      0t0     TCP 128.199.74.92:62443->173.245.54.192:28716 (CLOSE_WAIT)
```

> I think the only thing we'll really need on that box is some sort of comparable monitoring.

Can you please elaborate?

**Comment by myleshorton** [comment] 2015-01-21 18:50
> The code is very different.

Oh -- I thought you also deployed the new code to Heroku but said it didn't solve the problem? Maybe that was just the enproxy change?

> Can you please elaborate?

We just need to make sure we monitor the new machine in a comparable way to how we monitor the current machine. Maybe just adding the DO metrics for that box to our support days is good enough, though. Is that what you were thinking?

**Comment by oxtoacart** [comment] 2015-01-21 18:55
> Oh -- I thought you also deployed the new code to Heroku but said it didn't solve the problem? Maybe that was just the enproxy change?

I deployed an updated version of the original peerscanner to Heroku that incorporated the latest and greatest enproxy, but that continued to exhibit a fast leak.  The peerscanner that's running on DO is a very different codebase, but that uses the same latest and greatest enproxy.

> We just need to make sure we monitor the new machine in a comparable way to how we monitor the current machine. Maybe just adding the DO metrics for that box to our support days is good enough, though. Is that what you were thinking?

Gotcha.  We should already be monitoring the fallback-alarms mailing list (just updated template to reflect that), on which we will receive alerts once the peerscanner machine starts to get overloaded.  Is that enough?

**Comment by myleshorton** [comment] 2015-01-21 19:27
> Gotcha. We should already be monitoring the fallback-alarms mailing list (just updated template to reflect that), on which we will receive alerts once the peerscanner machine starts to get overloaded. Is that enough?

I mentioned this offline, but just to record here the key issue with the peerscanner was memory, so if we're unable to monitor memory that's a pretty big problem.

**Comment by oxtoacart** [comment] 2015-01-21 19:34
Memory alerting bug logged here - https://github.com/getlantern/lantern/issues/2183

As mentioned offline, memory pressure will lead to climbing load_avg, which will eventually trigger auto-restart, so we're in better shape anyway than we were on Heroku.

**Comment by myleshorton** [comment] 2015-01-21 20:36
Looks like we close this ticket proper @oxtoacart right?

**Comment by oxtoacart** [comment] 2015-01-22 03:22
This is mostly fixed, but I'm still seeing file descriptors for CloudFlare connections leaking.

BTW, here is the PR for it - https://github.com/getlantern/flashlight-build/pull/34

**Comment by oxtoacart** [comment] 2015-01-22 23:34
Okay, I finally found the leak!  It was actually not on our connections to the CloudFlare API, but on CloudFlare's connections to our web front-end.  Sometimes the requests to register would hang.  CloudFlare would close its end of the connection, but the request handler was still spinning and so wouldn't close its connection.

I've now added a timeout to prevent this hanging, and I no longer see the file descriptor leak!

**Comment by myleshorton** [comment] 2015-01-22 23:41
Sweet!!! So in web.go correct? Or maybe in the refactored version of web.go?

On Thu, Jan 22, 2015 at 3:34 PM, oxtoacart <notifications@github.com> wrote:

> Okay, I finally found the leak! It was actually not on our connections to
> the CloudFlare API, but on CloudFlare's connections to our web front-end.
> Sometimes the requests to register would hang. CloudFlare would close its
> end of the connection, but the request handler was still spinning and so
> wouldn't close its connection.
>
> I've now added a timeout to prevent this hanging, and I no longer see the
> file descriptor leak!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2174#issuecomment-71121578>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment] 2015-01-22 23:48
Yes, the refactored web.go.

**Comment by oxtoacart** [comment] 2015-01-23 13:59
Okay, peerscanner has been running for 11 hours now, memory is holding steady at around 60MB and we have about 50 file descriptors in CLOSE_WAIT, which is about what it was soon after the process started.  These are just connections that haven't timed out yet.

**Comment by myleshorton** [comment] 2015-01-23 17:26
Sweet! Great stuff @oxtoacart!

On Fri, Jan 23, 2015 at 5:59 AM, oxtoacart <notifications@github.com> wrote:

> Okay, peerscanner has been running for 11 hours now, memory is holding
> steady at around 60MB and we have about 50 file descriptors in CLOSE_WAIT,
> which is about what it was soon after the process started. These are just
> connections that haven't timed out yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2174#issuecomment-71196393>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Closed** 2015-02-02 17:57 UTC
Labels: P1
