### ISSUE TITLE
Lantern ignore domains in  /etc/hosts

### ISSUE THREAD

**Issue by crysislinux** [getlantern/lantern#3228] opened 2015-10-05 03:13 UTC
system: OSX El Captain
lantern version: 2.0.9

I have some local sites that are under development.

 \# /etc/hosts
127.0.0.1 example.dev

I can access local sites via 127.0.0.1, but cannot via example.dev

example.dev should go DIRECT but it seems go through the PROXY now.

Thanks.

**Comment by LukyHugh** [comment] 2015-11-06 03:11
I have same problem. How to fix this error.

**Comment by kcloze** [comment] 2015-11-07 00:18
Me too

**Comment by wonderffee** [comment] 2015-11-22 11:51
The same problem, could someone give a solution?

**Comment by royaso** [comment] 2016-01-08 02:22
ding!!

me too!

is there a way to bypass these local hosts domains?

**Comment by oxtoacart** [comment] 2016-04-22 03:38
Duplicate of #3472.

**Closed by oxtoacart** 2016-04-22 03:38 UTC
