### ISSUE TITLE
"Bad response status for read: 403 Forbidden"

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#2395] opened 2015-04-16 18:55 UTC
This is very prominent in our logs.  This is the error you get if you try and use domain fronting from an unauthorized location, hence the low priority.  But I'm not positive that this is the only cause.  Ideally we should be able to filter these out by location, but I don't know whether loggly allows that.

**Comment by myleshorton** [comment] 2015-07-20 19:18
With and Iran-focused user base this shoots to the #1 issue in our logs. Let's knock it out!

**Comment by myleshorton** [comment] 2015-07-20 23:59
Hey @fffw I just realized this one should also be pretty quickly reproducible on one of our VPSes.

**Comment by fffw** [comment] 2015-07-21 07:26
I can easily reproduce it by launching Lantern when VPN connected. Most of the errors are during checking against masquerades.

Through the response, we can know for sure that it's cloudflare that returns 403, and the cause is described [here](https://support.cloudflare.com/hc/en-us/articles/200169226-Why-am-I-getting-a-403-error-).

> Jul 21 06:54:42.937 - 0m4s DEBUG enproxy: conn_impl.go:165 Got response: &{403 Forbidden 403  HTTP/1.1 1 1 map[Connection:[keep-alive] Set-Cookie:[__cfduid=xxx; expires=Wed, 20-Jul-16 06:54:41 GMT; path=/; domain=.getiantem.org; HttpOnly] Cf-Ray:[xxx-SIN] Server:[cloudflare-nginx] Date:[Tue, 21 Jul 2015 06:54:42 GMT] Content-Type:[text/plain; charset=utf-8] Content-Length:[0]] 0x4bd3620 0 [] false map[] 0xc20892be10 <nil>}

Seems accessing via VPN triggers its [Browser Integrity Check](https://support.cloudflare.com/hc/en-us/articles/200170086-What-does-the-Browser-Integrity-Check-do-). Try accessing from Iran VPS now.

**Comment by fffw** [comment] 2015-07-21 08:23
Monitored for half an hour, normal access from Iran VPS didn't report any 403 error. I guess it only be triggered on some conditions.

By searching "403 Forbidden fronted" for last day, the distribution by country is very interesting.

![image](https://cloud.githubusercontent.com/assets/10410437/8795665/5c9d77e8-2fc1-11e5-839b-afa31f3320bb.png)

At least JP and SG should not be at the top of the list. One possible reason is that they are where VPN servers located. CloudFlare detects spammers / robots by IP range?

**Comment by fffw** [comment] 2015-07-21 08:38
Other causes, though relatively few, are accessing LAN hosts or non-standard ports. We can eliminate those errors by checking them in PAC file. Created https://github.com/getlantern/lantern/issues/2780 to handle it.

**Comment by myleshorton** [comment] 2015-07-21 19:44
Thanks @fffw. Interestingly we're seeing this in one set of user logs, but all of the 403 errors are again for the bogus sites Chrome seems to test with. We're seeing logs like the following, with no 403 errors for real sites so far:

```
ERROR flashlight.client: reverseproxy.go:186 http: proxy error: Dest: gauhaueuru:80    ProxyHost:     Unable to issue write request: Bad response status for read: 403 Forbidden
```

Looking at the automated logs, though, that appears to be a minority of cases.

**Comment by fffw** [comment] 2015-07-22 01:02
Good news is, with the change of PAC file in https://github.com/getlantern/lantern/pull/2781, the bogus sites will not go to Lantern, hence eliminates those 403 error.

**Comment by fffw** [comment] 2015-07-27 06:58
Oh no the 403 error is returned by [ourselves](https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/flashlight/server/server.go#L151) as we [we only allow access from a few countries](https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/flashlight/flashlight.go#L331)! CloudFlare just transparently passes the code back.

US and GB is allowed, but SG, JP, NL, etc, is not. So if users using Lantern over VPN hosted from those country, they will get 403. It can be confirmed by below curl command from our DO instances. we will find that US instances get 200 OK, but instances from Amsterdam and Singapore return 403 Forbidden, no exception.

> curl --insecure -vL https://nl.fallbacks.getiantem.org --header 'Host: nl.fallbacks.getiantem.org' --header 'X-Enproxy-Dest-Addr: www.google.com:80' --header 'X-Enproxy-Op: write' --header 'X-Enproxy-Id: 1111' --header 'Content-type: application/octet-stream' -X POST

Rather than changing allowed countries from whitelist to blacklist, we can simply access directly in such scenario, as Lantern just slows down a site if user already has VPN connected. Your thoughts guys?

**Comment by uaalto** [comment] 2015-07-27 07:20
Great finding!
I guess the main reason for not allowing those countries is to save resources, right?
I think that providing direct access defeats the purpose of using Lantern for those users. They may actually want to use it for some reason. If we don't provide service to those countries, we should be clear about it, not just provide direct access.

**Comment by myleshorton** [comment] 2015-07-27 17:54
Thanks guys. So @fffw unfortunately the 403 you're referring to actually only checks the actual client IP via X-Forwarded-For -- i.e. it doesn't use the IP of the proxy. See:

https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/flashlight/server/server.go#L394

So the curl command above gets a 403 from DO in Amsterdam because Amsterdam is not allowed, but that's not the case for clients connecting through there.

**Comment by aranhoide** [comment] 2015-07-27 18:42
@myleshorton that makes sense for web proxies.  Are VPNs populating X-Forwarded-For, though?

**Comment by myleshorton** [comment] 2015-07-27 18:54
Oh I see interesting @aranhoide. So that would explain why @fffw is seeing those errors when running with his VPN. The VPN *doesn't* add X-Forwarded-For, but CloudFlare does, and we don't allow access!

So we might be seeing 403 errors for a couple of different reasons -- sometimes us, sometimes CloudFlare. Hopefully the additional logging will clear it all up. Oh, that requires an update to all running Flashlight instances though as soon as https://github.com/getlantern/lantern/pull/2823 is merged! Can you handle that @aranhoide? 

We also need to update the addresses the config server is returning to never use localhost, but that's a different issue.

**Comment by aranhoide** [comment] 2015-07-27 19:18
Sure, I can handle the deployment of #2823.  I asked a question about the localhost thing in the relevant ticket.

**Comment by fffw** [comment] 2015-08-03 03:39
Instead of hardcode the countries, we can make it configurable to adjust more easily through Salt. What do you think @aranhoide @myleshorton ?

**Comment by aranhoide** [comment] 2015-08-03 05:31
@fffw I like it!

**Comment by myleshorton** [comment] 2015-08-05 22:10
I like it too @fffw, although I do want to also make sure we're able to deploy this fix soon so don't want re-architecting things to delay it too much. Doing it via salt would make it easier to deploy changes but:

1. How often are we really likely to deploy changes?
1. How much time would that really save?

I agree it's the ideal solution, but I'm just not sure how much of a win it would really be in practice.

**Comment by aranhoide** [comment] 2015-08-06 04:01
I don't think it would take much re-architecting, but yeah, I don't see us changing this often, if ever.  So maybe I'll do the quickest thing now and add the command line parameter the next time that we need to change it.

**Closed** 2015-08-06 06:21 UTC
Labels: P1

**Comment by xiam** [comment] 2015-09-04 21:52
This one started to pop up again. Was this caused by today's troubleshooting?

**Comment by myleshorton** [comment] 2015-09-04 22:14
Did it pop up in 2.0.2 and above?
