### ISSUE TITLE
Loading screen of Death on windows 

### ISSUE THREAD

**Issue by Droyk** [getlantern/lantern#4282] opened 2016-05-13 02:40 UTC
Good evening guys 

I am having a problem https://streamable.com/g2cx

Loading screen of death it never goes away tried everything but still doesn't go away 

using the lantern latest version 2.2.3
I am on windows 10 pro x64
Chrome 50.0.2661.102 m (64-bit)

**Comment by CHN008** [comment] 2016-05-13 15:20
Maybe you need set it by the "Settings" File,Or Run it  "As Administrator".

![lt-settings](https://cloud.githubusercontent.com/assets/16646697/15252520/da5bedc0-1960-11e6-945a-5fa3449fa628.jpg)

Mine Runs Well,But I Cant't Open The Setting Page.

My Mainly used tool is:"xx-net".

https://github.com/XX-net/XX-Net

**Comment by myleshorton** [comment] 2016-05-13 22:44
Was it working fine for you before @Droyk?

**Comment by xiam** [comment] 2016-05-14 01:51
Hello @Droyk, do you have any message on the web console? could you share a fullscreen video from installation until replicating the problem? Thanks.

**Comment by fthvgb1** [comment] 2016-05-14 03:55
I have a same problem on windows 10,
<img src="http://i4.buimg.com/e9365640b34b3b48.png">
<img src="http://i4.buimg.com/fd13942ca641fe2a.png">
,but it can work normally on ubuntu

**Comment by Droyk** [comment] 2016-05-14 07:01
@CHN008 I don't have any setting files on the folder
![screenshot_20160514122625](https://cloud.githubusercontent.com/assets/15848350/15266864/8269b790-19cf-11e6-9e11-a44b636b4d49.png)
@myleshorton No actually I am a new user of lantern
@xiam Well there are 2 error messages on console 
![g0gzett](https://cloud.githubusercontent.com/assets/15848350/15266838/af30f5f0-19ce-11e6-8051-3aa72452aa34.png)

**Comment by xiam** [comment] 2016-05-14 12:24
Thanks @Droyk, that really helps, could you send us another picture of your system proxy settings?

**Comment by CHN008** [comment] 2016-05-14 16:37
@Droyk I Found It Will Appears Like That On Your Computer When I Am Using Chrome And Firefox,But It Will Be Better OnSouGou Browser.
I Can't Open The Setting Page,But It Helps Surfing Google.

Maybe You Can Run "Any desk" on your computer and we can help you,via the Remote assistance.

**Comment by Droyk** [comment] 2016-05-15 05:38
@xiam okay here are my system proxy settings ![screenshot_20160515110325](https://cloud.githubusercontent.com/assets/15848350/15272210/ae20345a-1a8c-11e6-98f5-facebb26fe62.png)

and I just boot my system up in safe mode and it seems like lantern is running really fine on safe mode.
but when I boot up in normal mode it gives loading screen of death.
So I thought that my computer could be the problem so I try lantern on my friends computer. he also have windows 10 pro x64 installed and it seems like it also gave him the same loading screen but it ran fine on safe mode.

**Comment by xiam** [comment] 2016-05-15 05:52
Thanks, so after running Lantern the "Script Address" field remains blank?

**Comment by Johnaka** [comment] 2016-05-15 12:47
![screenshot 10](https://cloud.githubusercontent.com/assets/11838212/15274116/f8300be6-1ac4-11e6-893c-f7a31b8a0cfa.png)


i am on windows 10 facing the same also my IDM keeps capturin that file .

**Comment by Droyk** [comment] 2016-05-16 02:29
@xiam No actually these settings are before running the lantern ![screenshot_20160515110325](https://cloud.githubusercontent.com/assets/15848350/15272210/ae20345a-1a8c-11e6-98f5-facebb26fe62.png)

and this is the image of after running the lantern 
![screenshot_20160516074658](https://cloud.githubusercontent.com/assets/15848350/15278791/020f6f50-1b3b-11e6-991e-c82bc9ef7f3a.png)

**Script Address:** http://127.0.0.1:16823/proxy_on.pac?1463364942240340900

and after closing the lantern the system proxy settings clears all fields itself automatically. 
![screenshot_20160516075447](https://cloud.githubusercontent.com/assets/15848350/15278829/7d76a212-1b3b-11e6-806c-e8a5c925bba6.png)

@Johnaka I have IDM to but it doesn't capture anything at all

**Comment by xiam** [comment] 2016-05-16 02:57
That looks good @Droyk, this is really useful.Wwhat's the Chrome version you're using? and, if you go to http://127.0.0.1:16823/proxy_on.pac?1463364942240340900 directly, do you see anything?

**Comment by Droyk** [comment] 2016-05-16 03:20
Already described above I am using Chrome 50.0.2661.102 m (64-bit)

and without launching the lantern first if I go directly to the page it gives me this 
![screenshot_20160516084330](https://cloud.githubusercontent.com/assets/15848350/15279471/4b5ced52-1b42-11e6-956c-b5c7e7f4dfad.png)

but after running the lantern If I directly go to the page it gives me a download file proxy_on.pac
https://onedrive.live.com/redir?resid=7DED3594CFE70046!595&authkey=!AC6cV68PqYLI-2A&ithint=file%2cpac

**Comment by Johnaka** [comment] 2016-05-16 15:31
![screenshot 11](https://cloud.githubusercontent.com/assets/11838212/15294290/16ac07a6-1ba5-11e6-9d39-8010d8658d8a.png)

**Comment by myleshorton** [comment] 2016-05-16 17:56
I added this to the backlog for this next sprint @xiam, and thanks for all the info @Droyk and @Johnaka. We should be able to figure out a fix.

**Comment by myleshorton** [comment] 2016-05-16 17:56
That locale of en_GB is an interesting hint I think @xiam.

**Comment by myleshorton** [comment] 2016-05-17 15:54
Let me know if you want me to jump in on this @xiam

**Comment by myleshorton** [comment] 2016-05-17 15:55
It seems like something must have changed from 2.1.x, but I'm not sure what. We did actually upgrade angular to I believe 1.5.3.

**Comment by xiam** [comment] 2016-05-19 02:03
I unfortunately haven't been able to reproduce this error, if anyone could provide me with a step by step guide on how to reproduce it and a list of all the current programs opened at the time would be awesome.

**Comment by xiam** [comment] 2016-05-19 02:38
Try this as well:

1. Launch Lantern.
1. Launch Chrome Developer tools.
1. Press the reload button or Ctrl + R to reload the UI.
1. Click the Network Tab on Chrome's dev tools.
1. Select the WebSocket connection (`/data`) from the list.
1. Go to the "Frames" tab.

You should see something like: 

![screen shot 2016-05-18 at 9 35 37 pm](https://cloud.githubusercontent.com/assets/385670/15380939/87734a0c-1d40-11e6-826d-07579cbc11c1.png)

If the `Frames` tab is empty, take a look at the `Headers` tab, I have this:

![screen shot 2016-05-18 at 9 36 12 pm](https://cloud.githubusercontent.com/assets/385670/15380946/a5ec5730-1d40-11e6-93df-9306356bc7fb.png)

**Comment by xiam** [comment] 2016-05-19 03:27
> Let me know if you want me to jump in on this @xiam

Please do @myleshorton, I haven't find any interesting clue yet. I've tried with different Xunlei settings combinations, the locale message does not seem to be related, I think it has to do something with certain program running in the background but I can't be sure of that yet...

**Comment by fffw** [comment] 2016-05-25 13:15
@Droyk or someone else who experienced the same issue, could you help us to diagnose if you are convenient?

The steps are as following:

* Quit Lantern

* Open Terminal
```
cd C:\Users\<your-user-name>\AppData\Roaming\Lantern
export TRACE=flashlight.ui
lantern.exe
```
* The Lantern page will open. Please record screenshots as per https://github.com/getlantern/lantern/issues/4282#issuecomment-220213272

* Send screenshots and Lantern logs to me at fffw@getlantern.org
The logs are under C:\Users\<your-user-name>\AppData\Roaming\Lantern\logs

It would be a great help to find out the root cause!

**Comment by Droyk** [comment] 2016-05-25 18:34
@fffw just saw your comment and try to run Lantern and I got surprised now it's working really Fine I don't know why 
Proof: ![screenshot_20160525234318](https://cloud.githubusercontent.com/assets/15848350/15551514/f1e9c788-22d3-11e6-9742-0b87f9881bf5.png)

and I tried to diagnose it but giving me this error 
![screenshot_20160526000220](https://cloud.githubusercontent.com/assets/15848350/15551803/3eba38d0-22d5-11e6-8f2b-7b9cddd763bc.png)

**Comment by fffw** [comment] 2016-05-26 00:18
Oh sorry @Droyk there's a typo. Should be `set` instead of `export`. It's to instruct Lantern to print verbose logs for `flashlight.ui` package. As you didn't see the WebSocket error anymore, it becomes unnecessary to collect those logs.

The 404 error is expected because we don't have an en_GB translation, so it falls back to the default.

Anyway, glad that Lantern shows correctly for you again.

**Comment by fffw** [comment] 2016-05-26 00:25
Someone in the [devel forum](https://groups.google.com/d/msg/lantern-devel/FP5zW0KgzYs/eE_6kQjrAwAJ) saw the same always loading screen on Edge, but worked on Firefox.

**Comment by myleshorton** [comment] 2016-06-11 05:21
Should we close this for now since the UI is completely re-written @fffw and @xiam?

**Comment by fffw** [comment] 2016-06-11 06:59
I agree. Even if it recurs, the context is totally irrelevant.

**Comment by Droyk** [comment] 2016-06-12 11:25
Okay I will close it for now because my problem is not occurring. but can you guys plz answer my two simple question  @myleshorton what do you mean by
> the UI is completely re-written

I am not seeing any UI changes at all which version are you guys even talking about Right now I am on 2.2.4 the UI is same as before. 

@fffw what do you mean by 

> context is totally irrelevant

**Comment by fffw** [comment] 2016-06-12 11:51
@Droyk sorry for the confusion. Yes, current stable version is still 2.2.4 but a completely rewritten UI will come out soon.

**Comment by myleshorton** [comment] 2016-06-21 17:06
closing this for now.

**Closed by myleshorton** 2016-06-21 17:06 UTC
Labels: P1
