### ISSUE TITLE
It can't works on Ubuntu 15.04

### ISSUE THREAD

**Issue by losywee** [getlantern/lantern#3233] opened 2015-10-06 10:25 UTC
Hi, Writer, it can't works on Ubuntu 15.04 and no traffic.

**Comment by uaalto** [comment] 2015-10-07 14:33
Thank you @losywee 
I'll close this issue because it seems a duplicate of https://github.com/getlantern/lantern/issues/3224

**Closed by uaalto** 2015-10-07 14:33 UTC
