### ISSUE TITLE
Pro users cannot circumvent

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4988] opened 2016-07-11 06:07 UTC
He said he cannot access any websites including facebook and Chinese sites.
Logs here https://github.com/getlantern/forum/issues/480#issuecomment-231576034 @fffw

**Comment by p3rcya** [comment] 2016-07-11 07:09
More complaint https://github.com/getlantern/forum/issues/426#issuecomment-231655771 no log yet

**Comment by shuhankuang** [comment] 2016-07-11 13:46
我mac, 付费账户，启动后一直loading... :(

**Comment by guizhenwei** [comment] 2016-07-11 16:37
On Win 10 with version 3.0.6 Lantern Pro.

Hard to connect to the Internet.
No Google, no twitter, no facebook, no youtube, no wikipedia....

I have invited my friends to purchase the pro version, and they payed their money. 
I may fail they hope.

Please fix this situation **A.S.A.P**.

**Comment by myleshorton** [comment] 2016-07-11 16:38
Hey @guizhenwei can you send us your logs and just put in the subject "guizhenwei from GitHub"?

Instructions are here:

https://github.com/getlantern/lantern/wiki/Emailing-lantern-logs

**Comment by p3rcya** [comment] 2016-07-13 04:49
More log https://github.com/getlantern/forum/issues/358#issuecomment-232255406

**Comment by p3rcya** [comment] 2016-07-13 18:26
This user (log here https://github.com/getlantern/forum/issues/569#issue-165254299 ) can use Pro at home but not in the company

**Comment by p3rcya** [comment] 2016-07-18 01:15
More log https://github.com/getlantern/forum/issues/686

**Comment by p3rcya** [comment] 2016-07-19 17:28
More log https://github.com/getlantern/forum/issues/712

**Comment by p3rcya** [comment] 2016-07-20 18:52
More log https://github.com/getlantern/forum/issues/357#issuecomment-233870573

**Comment by p3rcya** [comment] 2016-07-21 19:21
https://github.com/getlantern/lantern/issues/5065#issue-166771447

**Comment by p3rcya** [comment] 2016-07-24 05:01
More log https://github.com/jaywongchina

**Comment by p3rcya** [comment] 2016-07-25 05:23
more log https://github.com/getlantern/forum/issues/815#issuecomment-234822014

**Comment by p3rcya** [comment] 2016-07-25 06:48
more log https://github.com/getlantern/forum/issues/822#issue-167290196

**Comment by p3rcya** [comment] 2016-07-25 18:41
more log https://github.com/getlantern/forum/files/380856/lantern.txt

**Comment by p3rcya** [comment] 2016-07-26 04:13
more log https://github.com/getlantern/forum/files/382993/lantern.txt

**Comment by p3rcya** [comment] 2016-07-27 16:30
@oxtoacart Logs posted way back might be due to the 1970 bug and users not really using Pro servers. So I suggest you reviewing the most recent logs first

**Comment by p3rcya** [comment] 2016-07-27 16:33
more https://github.com/getlantern/lantern/issues/5092#issuecomment-235637173

**Comment by p3rcya** [comment] 2016-07-27 16:33
More https://github.com/getlantern/forum/issues/847 (no log yet)

**Comment by myleshorton** [comment] 2016-07-30 05:25
Hey @oxtoacart and @fffw this one seems important if either of you happen to get to it before me!

**Comment by orbancanon** [comment] 2016-07-30 07:49
@myleshorton I'm scanning the logs and comments, in reverse order.

getlantern/forum#847: @p3rcya checked with user, it is caused to Xunlei

https://github.com/getlantern/lantern/issues/5092#issuecomment-235637173: Chrome doesn't respect Lantern as proxy, asked user to check.

https://github.com/getlantern/forum/files/382993/lantern.txt: server is inaccessible, though it's not blocked when testing from vps in China.

https://github.com/getlantern/forum/issues/822#issue-167290196( https://github.com/getlantern/forum/files/380856/lantern.txt ): Lantern timed out to read from sites directly, including www.baidu.com. I suspect it's network glitch.


https://github.com/getlantern/forum/issues/815#issuecomment-234822014: No access record from browser. Asked user to check.

https://github.com/getlantern/forum/issues/802#issuecomment-234758007: Can't dial any site. Should be network issue.

https://github.com/getlantern/lantern/issues/5065#issue-166771447: recovered.

I suspect if they are caused by different reasons.

**Comment by p3rcya** [comment] 2016-08-01 16:19
More pro log without xunlei https://github.com/getlantern/forum/issues/892 @fffw

**Comment by myleshorton** [comment] 2016-08-01 21:38
Thanks @p3rcya and @orbancanon! Just added another one here:

http://lantern.s3.amazonaws.com/lantern.log

**Comment by LightsJiao** [comment] 2016-08-02 02:21
所以把我的问题重定义到这里来，Pro用户怎么连上呢？
我昨晚回去用家里的网，可以正常翻墙、打开国内网站，但是国内网站打开很慢
而在公司（也能访问百度等大部分网站，部分娱乐网站被限制不允许访问而已）就不能翻墙，连正常打开国内网站都做不到

**Comment by p3rcya** [comment] 2016-08-04 02:06
More, no log yet  https://github.com/getlantern/forum/issues/921

**Comment by p3rcya** [comment] 2016-08-07 16:51
more log https://github.com/getlantern/forum/files/405379/lantern.txt

**Comment by p3rcya** [comment] 2016-08-07 16:57
more log https://github.com/getlantern/forum/issues/934#issuecomment-238070806

**Comment by p3rcya** [comment] 2016-08-08 16:09
more log https://github.com/getlantern/forum/issues/957

**Comment by p3rcya** [comment] 2016-08-10 06:48
more log https://github.com/getlantern/forum/issues/966#issue-170340515

**Comment by orbancanon** [comment] 2016-08-17 11:36
Scanned logs since I last did so, in reverse order.

https://github.com/getlantern/lantern/issues/4988 Didn't set as system proxy.

https://github.com/getlantern/forum/issues/957 Solved. Configuration issue.

https://github.com/getlantern/forum/files/405379/lantern.txt Not Pro user. Proxy blocked/inaccessible, already retired.

https://github.com/getlantern/forum/issues/921 Didn't set as system proxy.

http://lantern.s3.amazonaws.com/lantern.log Not Pro user. Assigned a (slow) NYC proxy somehow. The reassigned SGP server after restart did work.

https://github.com/getlantern/forum/issues/892 corporate network disallows some sites and port.

One thing we can do is to show warning on Lantern UI if it's not set as system proxy. @fffw @p3rcya @myleshorton

**Comment by myleshorton** [comment] 2016-08-22 19:34
I'm going to close this for now in favor of the more specific tickets - namely https://github.com/getlantern/lantern/issues/5178, https://github.com/getlantern/lantern/issues/5126, https://github.com/getlantern/lantern_aws/issues/291, and https://github.com/getlantern/lantern/issues/5039 with associated various reasons calls might not go through.

**Comment by p3rcya** [comment] 2016-08-27 17:39
More log https://github.com/getlantern/forum/files/440675/05_Laptop.Log_lantern.txt

**Comment by p3rcya** [comment] 2016-08-28 01:33
More log https://github.com/getlantern/forum/issues/1125#issuecomment-242947457

**Comment by oxtoacart** [comment] 2016-08-28 03:22
At least one of the servers "128.199.186.223" shows a "Mismatched token" error from client IP `111.161.77.224`.

**Comment by p3rcya** [comment] 2016-08-28 03:50
More log https://github.com/getlantern/forum/issues/1126

I'm keeping this open so we can analyze more Pro logs from users and perhaps open additional tickets.

**Comment by p3rcya** [comment] 2016-08-28 20:01
more log https://github.com/getlantern/forum/issues/815#issuecomment-242963252

**Comment by p3rcya** [comment] 2016-08-30 17:58
more log https://github.com/getlantern/forum/issues/1146#issue-173974307

**Comment by p3rcya** [comment] 2016-09-01 06:54
more log https://github.com/getlantern/forum/issues/1164#issue-174435887

**Comment by p3rcya** [comment] 2016-09-03 04:35
no log yet https://github.com/getlantern/lantern/issues/5243#issue-174869002

**Comment by p3rcya** [comment] 2016-09-03 04:36
more log https://github.com/getlantern/forum/issues/1183

**Comment by p3rcya** [comment] 2016-09-03 18:15
more log https://github.com/getlantern/forum/issues/1187

**Comment by orbancanon** [comment] 2016-09-04 11:39
https://github.com/getlantern/forum/issues/1187 Log is 2.2.5. Server is good but has no access record from browser or other applications.

https://github.com/getlantern/forum/issues/1183 has access record from other applications but without browser. asked user to check Xunlei or plugins.

https://github.com/getlantern/forum/issues/1164#issue-174435887 No access record from browser.

https://github.com/getlantern/forum/issues/1146 Not quite sure why it's slow, but a few servers were temporarily timing out.

https://github.com/getlantern/forum/issues/1126 Not Pro. server is inaccessible.

**Comment by p3rcya** [comment] 2016-09-05 06:25
more log https://github.com/getlantern/lantern/issues/5240#issuecomment-244639312

**Comment by p3rcya** [comment] 2016-09-11 07:10
more log https://github.com/getlantern/lantern/issues/5268#issue-176178128

**Comment by p3rcya** [comment] 2016-09-11 07:10
more log https://github.com/getlantern/forum/issues/1254#issue-176213132

**Comment by p3rcya** [comment] 2016-09-11 07:16
more log https://github.com/getlantern/forum/issues/1250#issue-176178837

**Comment by p3rcya** [comment] 2016-09-14 17:59
more log https://github.com/getlantern/forum/issues/1286#issue-176898269

**Comment by p3rcya** [comment] 2016-09-15 18:39
more log https://github.com/getlantern/forum/issues/1292

**Comment by p3rcya** [comment] 2016-09-16 05:02
more log https://github.com/getlantern/lantern/issues/5285

**Comment by p3rcya** [comment] 2016-09-16 16:23
more log https://github.com/getlantern/forum/issues/1302

**Comment by p3rcya** [comment] 2016-09-21 17:45
more log https://github.com/getlantern/forum/issues/1352#issue-178271060 (He uploaded the log as an image. You need to change the extension. )

**Closed** 2017-05-23 21:17 UTC
