### ISSUE TITLE
Browser got HTTP 500 error when EOF received in reverse proxy

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2292] opened 2015-03-09 08:34 UTC
`http: proxy error: EOF` will be logged to console at the same time (not through golog).

**Comment by fffw** [comment] 2015-03-09 08:55
[Go source](http://golang.org/src/net/http/httputil/reverseproxy.go#L147) treat EOF as error. We may need to check in detail.

**Comment by fffw** [comment] 2015-03-10 05:19
Another concrete example, direct access to `http://www.dapenti.com/blog/index.asp` will timeout, whereas HTTP 500 through Lantern.

Returns 500 is meaningful for server side reverse proxy, but not here.

**Comment by oxtoacart** [comment] 2015-03-10 15:25
+1.  Fundamentally the problem is that we're turning all sorts of different errors from the final connection into 500 errors. We could include a custom header on the responses from the proxy that we could use to transmit more detailed information about the error, and then mimic it on the client-side. So for example if we get an unexpected EOF, the client would just close the connection from the browser to mimic an unexpected EOF.

Timeout would be difficult to mimic though, so this may not end up being exactly 1 to 1.

**Comment by myleshorton** [comment] 2016-07-28 05:56
Closing in favor of #5058

**Closed by myleshorton** 2016-07-28 05:56 UTC
Labels: P2

**Comment by fffw** [comment] 2016-07-28 06:05
@myleshorton I don't think they are the same issue. As long as we are still using `ReverseProxy`, most of the HTTP status codes will trigger 500. It's reasonable for a reverse proxy, but not for our purpose.

We may have already solved it by respond 502 or 503 manually. I didn't see 500 error for a long time.
