### ISSUE TITLE
Lantern Pro can not work on macOS Sierra

### ISSUE THREAD

**Issue by brilliance-boy** [getlantern/lantern#5260] opened 2016-09-09 03:28 UTC
Lantern Pro can not work on macOS Sierra

**Comment by Artoria2e5** [comment] 2016-09-10 19:42
Duplicate of #5254.

**Comment by p3rcya** [comment] 2016-09-13 05:58
closed in favor of https://github.com/getlantern/lantern/issues/5254

**Closed by p3rcya** 2016-09-13 05:58 UTC
