### ISSUE TITLE
[bug] UI fails to start on IE8 (Windows XP)

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2263] opened 2015-02-25 02:44 UTC
This is on Windows XP, IE8.

The first time Lantern UI comes up, a confusing message like this is shown:

![screen shot 2015-02-24 at 8 28 59 pm](https://cloud.githubusercontent.com/assets/385670/6363950/666ec71a-bc65-11e4-882c-df4b8836f187.png)

Users can easily enable that setting by clicking the bar and choosing "Enable Intranet Settings" (it should be documented somewhere):

![screen shot 2015-02-24 at 8 29 20 pm](https://cloud.githubusercontent.com/assets/385670/6363956/7593e39c-bc65-11e4-887e-959033edda00.png)

After that, the UI reloads with another problem (maybe an extra comma or a missing semicolon?):

![screen shot 2015-02-24 at 8 30 57 pm](https://cloud.githubusercontent.com/assets/385670/6363965/8ff1018e-bc65-11e4-88c1-a7fddb5d00c6.png)

**Comment by oxtoacart** [comment] 2015-02-25 02:46
This is a dupe of #2261

**Comment by atavism** [comment] 2015-02-25 02:52
Thanks for the extra screenshots, @xiam! I copied those over to #2261

**Closed** 2015-03-01 08:37 UTC
