### ISSUE TITLE
Lantern stopped working, accessing from PRC

### ISSUE THREAD

**Issue by looper1234** [getlantern/lantern#3400] opened 2016-01-11 10:47 UTC
used to work perfectly fine, now it gets stuck on the status 'waiting for proxy tunnel response'
using chrome on win 10

[log link removed by @aranhoide; please send these to team@getlantern.org instead]

**Comment by pjzhong** [comment] 2016-01-11 11:50
Same here...........

**Comment by looper1234** [comment] 2016-01-11 18:06
I followed a post on twitter to use tor and set local proxy setting from lantern, that worked.

**Comment by wrlssqi** [comment] 2016-01-12 03:29
same here. I can ping the server, but seems that lantern transfer no data at all. 
DEBUG balancer: balancer.go:106 Successfully dialed via (trusted) chained proxy at 45.32.24.116:443 to connect://en.wikipedia.org:443 on pass 0

**Comment by aranhoide** [comment] 2016-01-12 20:20
Thanks all for your reports!

@looper1234 : were you using any other proxy management software in addition to Lantern?

@pjzhong : does the solution that @looper1234 describes work for you?

@wrlssqi : have you tried the solution @looper1234 suggests?  Also, please don't post the IPs of servers here, even if they don't seem to be working for you.

**Comment by wrlssqi** [comment] 2016-01-13 02:22
@aranhoide IE works well with lantern, but chrome and Microsoft edge don't work. In chrome, it just "waiting for proxy tunnel" and then nothing happened. Then the error code is "ERR_CONNECTION_ABORTED" or "ERR_TIME_OUT". seems like other people have same problem too. Maybe it's the win10's fault??

**Comment by looper1234** [comment] 2016-01-13 02:26
@aranhoide, I had xxnet also installed, but did not run both at the same time.

**Comment by looper1234** [comment] 2016-01-13 02:44
Here is the article about using lantern to revive tor
https://gochrome.info/tor-revive/

translations for the steps:
1 check yes for ISP blocks tor
2 no need to mess with the bridges
3 check yes for local proxy
4 enter the proxy data for lantern, remember to leave lantern running in tray

and this has worked, I can use tor in PRC now, never could before.

**Comment by wrlssqi** [comment] 2016-01-13 06:22
I have solved my problem. It's caused by Thunder, the download manager software. When I uninstall Thunder, chrome and edge go back to normal.

**Comment by boer0924** [comment] 2016-01-13 10:45
@wrlssqi  Yeah! it's worked. The fuck Thunder!

The software versions:
Windows 10 TH2(1151) system image.
Thunder 1.0.32.350 (http://vip.xunlei.com/fast_xl/)
Lantern 2.0.10 beta

**Comment by looper1234** [comment] 2016-01-13 11:00
@wrlssqi, getting rid of thunder (迅雷) worked for me too.
thanks

**Comment by pjzhong** [comment] 2016-01-13 11:20
@aranhoide @looper1234 thanks! Lantern Work well agian.

**Comment by faddat** [comment] 2016-02-11 09:21
Xunlei is now blocking lantern?

**Comment by myleshorton** [comment] 2016-02-12 20:40
We're actually not sure exactly what the conflict is @faddat, but we suspect it's something to do with Xunlei's modification of proxy settings.

**Comment by myleshorton** [comment] 2016-02-29 21:06
Closing in favor of #3679

**Closed by myleshorton** 2016-02-29 21:06 UTC
