### ISSUE TITLE
When I quit Lantern,I cannot connect to the Internet

### ISSUE THREAD

**Issue by geniusfhr** [getlantern/lantern#3417] opened 2016-01-21 14:58 UTC
Mac OSX 10.9,When I quit Lantern,I cannot connect to  the Internet,How to solve this problem?

**Comment by wutaizeng** [comment] 2016-02-20 09:13
`+1 `
- Mac OSX 10.11.3 
- Lantern 2.0.16 (20160219.041128)

**Comment by myleshorton** [comment] 2016-02-23 05:28
Do you have any proxy setting in your network preferences after Lantern quits @geniusfhr or @wutaizeng?

**Comment by wutaizeng** [comment] 2016-02-23 05:59
@myleshorton  No, but i have a proxy setting before Lantern first start.

**Comment by myleshorton** [comment] 2016-02-29 21:04
This is almost certainly the same root cause as #3039. Closing in favor of that ticket.

**Closed by myleshorton** 2016-02-29 21:04 UTC
