### ISSUE TITLE
Lots of too many open files errors

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2330] opened 2015-03-26 04:09 UTC
Reading lantern.yaml appears to be a common place, but we're getting this error in a variety of places and are clearly failing to close either a network connection or file descriptor somewhere.

**Comment by fffw** [comment] 2015-03-26 06:16
I submitted a similar ticket at https://github.com/getlantern/lantern/issues/2307, but seems Lantern didn't have many handles opened.

**Comment by fffw** [comment] 2015-03-31 12:58
I hit it again just now. I'm not sure, but it might be caused by rigid limit of launchd for each process it launches, instead of system level limits.
```
~ () $ sudo launchctl limit maxfiles
	maxfiles    256            unlimited
```
A detailed description [here](http://support.code42.com/CrashPlan/Latest/Troubleshooting/Backups_Stall_Due_To_Too_Many_Open_Files#OS_X_Yosemite_Version_10.10_And_Later)

I changed the limit to 65536 and monitor, hope it works.

**Comment by myleshorton** [comment] 2015-03-31 15:13
Nice find @fffw! I still think we shouldn't be hitting it regardless, as
prior lantern versions never have. Something we're not closing in the
logging perhaps? Just trying to think of relatively new components, but the
first and hardest step is to reliably reproduce it.

On Tuesday, March 31, 2015, fffw <notifications@github.com> wrote:

> I hit it again just now. I'm not sure, but it might be caused by rigid
> limit of launchd for each process it launches, instead of system level
> limits.
>
> ~ () $ sudo launchctl limit maxfiles
>     maxfiles    256            unlimited
>
> A detailed description here
> <http://support.code42.com/CrashPlan/Latest/Troubleshooting/Backups_Stall_Due_To_Too_Many_Open_Files#OS_X_Yosemite_Version_10.10_And_Later>
>
> I changed the limit to 65536 and monitor, hope it works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2330#issuecomment-88074255>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by atavism** [comment] 2015-04-22 04:11
This is appearing as a top error in Loggly again. There's definitely a file descriptor that isn't being closed. Might be helpful to leave Lantern running awhile and check ``lsof -p <pid>`` to track this down.

**Comment by myleshorton** [comment] 2015-04-22 18:23
Thanks @atavism. Yeah I agree this is a big problem. I see one potential issue with never closing connections on the server side here:

https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/flashlight/flashlight.go#L263

I would think we'd be seeing too many open files on our servers to.

**Comment by myleshorton** [comment] 2015-04-22 18:25
Actually we have the same read/write timeout issue on the local proxy, so we could theoretically be building up connections from the browser. That seems unlikely since the browser should be good about closing them, but you never know.

**Comment by fffw** [comment] 2015-04-24 03:39
Yes I saw lots of client proxy connections in CLOSE_WAIT state, which seems unusual. `msgsrvr` means port 8787. From TCP/IP Illustrated, it means that FIN was received from browser but connection was not closed at the proxy side. So it may not related to `ReadTimeout`, but the logic of `ReverseProxy` maybe.

```
lantern_d 92086 merlin    3u    IPv4 0x7d82e58ffe920b15        0t0      TCP 127.0.0.1:msgsrvr->127.0.0.1:60105 (CLOSE_WAIT)
lantern_d 92086 merlin   15u    IPv4 0x7d82e58ffbc49f05        0t0      TCP 127.0.0.1:msgsrvr->127.0.0.1:55189 (CLOSE_WAIT)
lantern_d 92086 merlin   19u    IPv4 0x7d82e59007ea73e5        0t0      TCP 127.0.0.1:msgsrvr->127.0.0.1:57031 (CLOSE_WAIT)
```

**Comment by fffw** [comment] 2015-04-24 13:43
Seems those piled CLOSE_WAIT connections are caused by [here](https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/flashlight/client/handler.go#L99), `io.Copy` will not return until `connOut` is closed by peer or error encountered.

As HTTP/1.1 no longer depends on connection close to indicate the end of response, it should be safe to interrupt copy when the read half of `clientConn` is closed.

**Comment by myleshorton** [comment] 2015-04-24 16:16
Interesting @fffw. So you're able to consistently reproduce it? And it only seems to happen with HTTPS connections is that right?

**Comment by fffw** [comment] 2015-04-24 17:16
Yes from my finding it only occurs for HTTPS. I can reproduce lots of
CLOSE_WAIT connections. Through my PR, they can be totally removed, hence
will not cause file descriptors exceed 256 limit easily.
2015年4月25日 上午12:16于 "myleshorton" <notifications@github.com>写道：

**Comment by fffw** [comment] 2015-05-22 00:34
I encountered this again when using beta 5, but `lsof` shows lots of ESTABLISHED connections instead. Could be connection leaks.

**Comment by myleshorton** [comment] 2015-05-22 04:23
Hmnn.. wow. This is extremely important to knock out!

On Thu, May 21, 2015 at 5:34 PM, fffw <notifications@github.com> wrote:

> I encountered this again when using beta 5, but lsof shows lots of
> ESTABLISHED connections instead. Could be connection leaks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2330#issuecomment-104457575>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by myleshorton** [comment] 2015-05-26 19:22
I ran for a long time hitting whitelisted sites intensively and was unable to reproduce this FWIW.

**Comment by myleshorton** [comment] 2015-06-03 19:48
So this appears to be the reason one of our test instances on a VPS died. Given that specific test instance has likely not seen a lot of traffic, the issue appears to have been caused by continual config updates (or rather perceived updates) leading to file descriptor build up over time:

Here's the first instance:

```
May 28 00:38:25.895 - flashlight.client: server.go:1777 http: Accept error: accept tcp x.x.x.x:8888: too many open files; retrying in 5ms
```

**Comment by myleshorton** [comment] 2015-06-03 19:50
My guess is this issue is reproducible through artificially setting the config updates to happen very frequently with forcing the config to be considered changed.

**Comment by myleshorton** [comment] 2015-06-03 20:08
From the logs it also appears possible automated scans had discovered a proxy running here and were using it for general traffic.

**Comment by myleshorton** [comment] 2015-06-03 20:17
Full logs are uploaded to s3

**Comment by fffw** [comment] 2015-06-04 09:07
@myleshorton Yes those connections are mostly made from outside to proxy port.

```lsof -nPp 1128 | grep TCP | grep 8888 | cut -d ">" -f 2 | cut -d ":" -f 1 | sort  | uniq -c```

I installed a tool called `iptraf` to show traffics, but those connections hardly have any traffic.

**Comment by fffw** [comment] 2015-06-04 15:01
I temporarily added periodically connection dump to branch `issue2330`. We can see lots of long running intercepted connections (10min+), like below:

```
Jun 04 14:41:38.396 - DEBUG flashlight.client: handler.go:35 **********Connection to www.google.com:443 via 188.166.123.90:443 lasted for 33m12.791920738s
Jun 04 14:41:38.396 - DEBUG flashlight.client: handler.go:35 **********Connection to www.google.com:443 via 188.166.123.90:443 lasted for 33m34.353829464s
Jun 04 14:41:38.397 - DEBUG flashlight.client: handler.go:35 **********Connection to ms139.slack-msgs.com:443 via 54.173.228.194:443 lasted for 32m48.179961091s
Jun 04 14:41:38.397 - DEBUG flashlight.client: handler.go:35 **********Connection to p18-caldav.icloud.com:443 via 17.151.236.19:443 lasted for 33m11.369714782s
Jun 04 14:41:38.397 - DEBUG flashlight.client: handler.go:35 **********Connection to 12.client-channel.google.com:443 via 104.238.150.147:443 lasted for 32m48.145937754s
Jun 04 14:41:38.397 - DEBUG flashlight.client: handler.go:35 **********Connection to p18-caldav.icloud.com:443 via 17.151.236.19:443 lasted for 30m2.864085856s
```

If we run it like `TRACE=flashlight.client ./lantern_darwin_amd64`, we can also see intercepted connections less than 10min. They are much more than connections established from application to 8787 (proxy port) at the same time.

Theoretically, [`pipeData`](https://github.com/getlantern/lantern/blob/83a78b7cda2dd1e2f2cc23f388e66438665116a0/src/github.com/getlantern/flashlight/client/handler.go#L147) will return if `clientConn` is closed by remote end, hence trigger an error return of [`io.Copy(clientConn, connOut)`](https://github.com/getlantern/lantern/blob/83a78b7cda2dd1e2f2cc23f388e66438665116a0/src/github.com/getlantern/flashlight/client/handler.go#L165), but we can add trace to make sure.

**Comment by fffw** [comment] 2015-06-05 07:27
So the cause is somewhat obvious. Lantern still holds lots of `clientConn` handles whereas application already closed them. It's possibly because if `connOut` has nothing to be read, `io.Copy(clientConn, connOut)` never has a chance to write to `clientOut`, hence not be aware that `clientConn` has already closed.

**Comment by myleshorton** [comment] 2015-06-05 17:27
Interesting @fffw thanks. I see one possible cause. I'm not seeing this code path in the server logs where this appeared, but there also could be multiple causes. Have a look at:

https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/detour/detour.go#L126

If we decide it is DNS hijacked, what happens to the dc.conn from https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/detour/detour.go#L120

??

At that point dc.conn is open, and I don't see it being closed anywhere.

**Comment by myleshorton** [comment] 2015-06-05 17:28
Oh, also, I meant to point out that I believe the version running on the server before was pre beta 5, so it's possible it didn't include all the current potential fixes for this.

**Comment by fffw** [comment] 2015-06-06 05:13
Yeah good catch @myleshorton ! It should be fixed

**Closed** 2015-06-07 19:42 UTC
Labels: P1

**Comment by myleshorton** [comment] 2015-06-22 20:14
Looks like this is fixed once and for all!!
