### ISSUE TITLE
Port code to turn system proxying on and off to Go

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#1902] opened 2014-10-18 00:56 UTC
Needs to work on all platforms.

**Comment by myleshorton** [comment] 2015-01-16 18:48
It's also possible @fffw's changes to the configureNetworkServices may mean we don't need setuid for this to work.

**Comment by myleshorton** [comment] 2015-01-16 18:48
Actually @fffw this ticket might be a good one to work on since it touches some of the stuff you just did.

**Comment by fffw** [comment] 2015-01-17 02:01
So that means, instead of separated console application, we should write a new go library that simply calls APIs on each platform to set proxy pac?

**Comment by oxtoacart** [comment] 2015-01-17 02:13
@fffw I would do whatever is easiest.  On some platforms, there are existing commands that do what we need, and simply running them might be enough.

I experimented with that here - https://github.com/oxtoacart/netutil/blob/master/netutil_darwin.go

**Comment by oxtoacart** [comment] 2015-01-17 02:20
@fffw That said, since you found that calling the APIs directly can be much faster, maybe it does make sense to provide API bindings.  The whole user access control thing is another variable that we have to deal with.

**Comment by fffw** [comment] 2015-01-17 02:21
Got the points, thanks.


Regards,Merlin

**Comment by myleshorton** [comment] 2015-01-18 04:56
Yeah basically @fffw we already have methods for doing this on the various platforms. See:

https://github.com/getlantern/lantern/blob/devel/src/main/java/org/lantern/Proxifier.java

On Windows, we can all out to https://github.com/getlantern/winproxy
On OSX, we can call your existing configureNetworkServices
On Ubuntu we can use gsettings, as in:

gsettings set org.gnome.system.proxy autoconfig-url blah

As you likely saw, on OSX configureNetworkServices requires root, although I'd be curious to see what happens running it as the current user with your latest changes. Windows should be fine and I believe Ubuntu as well.

So unless there's some reason for doing something different, we already have working solutions for each platform that we should just use.

**Comment by oxtoacart** [comment] 2015-01-18 16:36
> Yeah basically @fffw we already have methods for doing this on the various platform

+1

Just a note on why I think we should discuss this in the context of a potential extension.  If we had an extension, I think a viable mode of usage would be to dispense with the system-wide autoproxy configuration and simply have an on/off toggle in our extension on a per-tab basis.  That way, we just proxy everything you're doing within a given tab, without having to worry about whether the list is complete.  When a user doesn't need proxying, she can just turn it off in whatever tab she is in.

@atavism What do you think?

**Comment by atavism** [comment] 2015-01-18 23:20
> @atavism What do you think?

@oxtoacart, I completely agree. Being able to proxy on a per-tab basis from an extension has always seemed really powerful and a better user experience to me. I threw together the Firefox extension in an effort to move us in that direction and to show it wouldn't be difficult maintaining multiple extensions. We could use a context menu item to add/remove a site from your whitelist:  https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Add_a_Context_Menu_Item I assume we'd do something analogous with Chrome.

![image](https://cloud.githubusercontent.com/assets/6346213/5794496/4d2063f2-9f25-11e4-993e-aab724e74d12.png)

**Comment by myleshorton** [comment] 2015-01-21 06:52
What makes it a better user experience?

**Comment by oxtoacart** [comment] 2015-01-22 17:36
> What makes it a better user experience?

I won't speak for @atavism, but for me this would be very handy because it would be a quick and easy way to do both proxied and unproxied browsing, and to clearly know which is which (based on how the extension looks when I'm on a given tab).  Unfortunately, this may all be moot :(

https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/7MevxLfCF8k
https://code.google.com/p/switchy/issues/detail?id=11

**Comment by myleshorton** [comment] 2015-01-22 20:01
Interesting thanks @oxtoacart! I still think Lantern automatically routing around any blocking is the ideal experience because it requires no user interaction.

@fffw very slick implementation of this at https://github.com/getlantern/pacon!

The one really problematic issue I can see is requiring root on OSX. I actually originally envisioned this just calling those existing executables using https://github.com/getlantern/byteexec. That would enable us to do something special on OSX on install like using setuid on configureNetworkServices. That has the advantage of just getting root permissions once and then not having to worry about it. Your implementation prompts for root every time, is that correct? 

It's very slick though -- I didn't even realize you can call out directly from cgo to objective C like that.

**Comment by oxtoacart** [comment] 2015-01-22 23:26
> Interesting thanks @oxtoacart! I still think Lantern automatically routing around any blocking is the ideal experience because it requires no user interaction.

Yes, if we can make this work reliably, in all countries, I agree that it would be the better user experience.  That's a big if though.

> The one really problematic issue I can see is requiring root on OSX. I actually originally envisioned this just calling those existing executables using https://github.com/getlantern/byteexec. That would enable us to do something special on OSX on install like using setuid on configureNetworkServices. That has the advantage of just getting root permissions once and then not having to worry about it. Your implementation prompts for root every time, is that correct?

Will browsers fall back to direct connections if they can't contact the proxy?  If so, we could:

- Simplify the PAC file so that it basically sends everything through our local proxy
- Update the proxy to decide whether or not actually proxy based on the whitelist
- Make the PAC file something that lives on the file system
- Install the PAC file once, then don't worry about it anymore

**Comment by myleshorton** [comment] 2015-01-22 23:39
> Will browsers fall back to direct connections if they can't contact the proxy? If so, we could:

That's a very cool insight. I believe they will, although I'm not 100% sure how they handle it. That's what "DIRECT" in this line means though:

```
PROXY 127.0.0.1:8787; DIRECT
```

Basically if you can't hit the proxy go, directly. What I don't know is:

1. Does that affect performance?
1. What does the browser consider to be proxy failure to be? In particular, is a successful connect not a failure.

The other tricky thing is that at least Chrome will start ignoring your proxy settings if the proxy isn't working, although I don't know exactly what triggers that either.

I do think that's a very cool insight, though, and if we could get it working would be a nice win.

**Comment by oxtoacart** [comment] 2015-01-22 23:58
Well, for Chrome anyway, this is what I get :(  Maybe there's some other way to accomplish this hack?

![screen shot 2015-01-22 at 5 52 17 pm](https://cloud.githubusercontent.com/assets/5000654/5867313/10edd64c-a260-11e4-868a-1f64da6b7e3f.png)

**Comment by fffw** [comment] 2015-01-23 03:39
> I still think Lantern automatically routing around any blocking is the ideal experience because it requires no user interaction.

I completely agree. I had a chat with a few college student friends yesterday, majors from art to design to accounting. They feel current solutions (commercial VPNs and fqrouter, on phones and pads) too complicated, even just a simple tap. If a page fails to open, they don't know if it is caused by firewall or the site itself. They even call all circumvention tools VPN.

> Your implementation prompts for root every time, is that correct?

Yes that's impractical. The only improvement is that we can make a simple tool that works across platforms, which still requires setuid when installs on Mac (or first run), and run it through a single exec on main go program.

I'm not clear how `byteexec` fits here. Embed the binary in main program, extract it on first run, and setuid on Mac (which still prompts for password)?

**Comment by myleshorton** [comment] 2015-01-23 04:00
> I completely agree. I had a chat with a few college student friends
> yesterday, majors from art to design to accounting. They feel current
> solutions (commercial VPNs and fqrouter, on phones and pads) too
> complicated, even just a simple tap. If a page fails to open, they don't
> know if it is caused by firewall or the site itself. They even call all
> circumvention tools VPN.
>

That's incredibly valuable data. It would be great to know what they think
of Lantern.


>  Your implementation prompts for root every time, is that correct?
>
> Yes that's impractical. The only improvement is that we can make a simple
> tool that works across platforms, which still requires setuid when installs
> on Mac (or first run), and run it through a single exec on main go program.
>
> I'm not clear how byteexec fits here. Embed the binary in main program,
> extract it on first run, and setuid on Mac (which still prompts for
> password)?
>

Yeah a couple of things. Honestly I kind of like your implementation
better, but the advantages of bytexec are:

1) We can setuid on just the extracted executable on first run as you said
2) Each platform-specific solution can be its own independent open source
project, which is more modular overall and more likely to attract open
source users and contributors.

The setuid bit is tricky though. I wonder if there are cocoa APIs we can
call to grab permissions just on that first run to setuid? Apple actually
recommends doing things like that through launchd daemons, in which case we
just need those permissions to write the launchd config to the root daemon
directory.

—
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/1902#issuecomment-71143182>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by myleshorton** [comment] 2015-01-23 04:39
That is to say the best approach might be launchd and to write a launchd
script that calls configureNetworkServices and is triggered through one of
the launchd triggering methods.

On Thursday, January 22, 2015, Adam Fisk <afisk@getlantern.org> wrote:

>
> I completely agree. I had a chat with a few college student friends
>> yesterday, majors from art to design to accounting. They feel current
>> solutions (commercial VPNs and fqrouter, on phones and pads) too
>> complicated, even just a simple tap. If a page fails to open, they don't
>> know if it is caused by firewall or the site itself. They even call all
>> circumvention tools VPN.
>>
>
> That's incredibly valuable data. It would be great to know what they think
> of Lantern.
>
>
>>  Your implementation prompts for root every time, is that correct?
>>
>> Yes that's impractical. The only improvement is that we can make a simple
>> tool that works across platforms, which still requires setuid when installs
>> on Mac (or first run), and run it through a single exec on main go program.
>>
>> I'm not clear how byteexec fits here. Embed the binary in main program,
>> extract it on first run, and setuid on Mac (which still prompts for
>> password)?
>>
>
> Yeah a couple of things. Honestly I kind of like your implementation
> better, but the advantages of bytexec are:
>
> 1) We can setuid on just the extracted executable on first run as you said
> 2) Each platform-specific solution can be its own independent open source
> project, which is more modular overall and more likely to attract open
> source users and contributors.
>
> The setuid bit is tricky though. I wonder if there are cocoa APIs we can
> call to grab permissions just on that first run to setuid? Apple actually
> recommends doing things like that through launchd daemons, in which case we
> just need those permissions to write the launchd config to the root daemon
> directory.
>
> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/getlantern/lantern/issues/1902#issuecomment-71143182>
>> .
>>
>
>
> --
> --
> President
> Brave New Software Project, Inc.
> https://www.getlantern.org
> pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by fffw** [comment] 2015-01-23 06:17
That depends on how we want to install and run Lantern as background process, and how systray/config page/browser extension interacts with it, on each platform.




Seems flashlight is platform-independent currently, so on Mac, we’ll create a long-run launchd daemon which starts and stop flashlight, set system pac, etc., and the UI part interacts with flashlight through RESTful API?




In fact, it’s a bit obscure to me what each running parts will be on client after fully ported to go.

**Comment by myleshorton** [comment] 2015-01-23 08:57
Hey sorry I'm only talking about the proxy part running as a launchd
*daemon*. Lantern runs also also as a launchd agent in user space now, but
I would just not worry about that part for the purposes of this.

Actually for now if you're just able to call setuid through cocoa with that
call triggering an authentication prompt, we could just go with that for
now.

Alternatively you could skip that part entirely for now and just leave it
so that we are at least able to call setuid on an external
configureNetworkServices file later, that's fine too.

On Thursday, January 22, 2015, fffw <notifications@github.com> wrote:

> That depends on how we want to install and run Lantern as background
> process, and how systray/config page/browser extension interacts with it,
> on each platform.
>
>
>
>
> Seems flashlight is platform-independent currently, so on Mac, we’ll
> create a long-run launchd daemon which starts and stop flashlight, set
> system pac, etc., and the UI part interacts with flashlight through RESTful
> API?
>
>
>
>
> In fact, it’s a bit obscure to me what each running parts will be on
> client after fully ported to go.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/1902#issuecomment-71152281>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by fffw** [comment] 2015-02-01 13:38
Oh I just found why launchd maters here. Record 3 methods here for later reference.

. `AuthorizationExecuteWithPrivileges` and `chmod` to repair setuid bit
https://developer.apple.com/library/mac/documentation/Security/Conceptual/authorization_concepts/03authtasks/authtasks.html

. As a launchd daemon
https://developer.apple.com/legacy/library/samplecode/BetterAuthorizationSample/Introduction/Intro.html

. Also a launchd daemon, but through `SMJobBless` and `NSXPCConnection`, which requires both caller and callee program code signed.
https://developer.apple.com/library/mac/samplecode/EvenBetterAuthorizationSample/Introduction/Intro.html

**Comment by oxtoacart** [comment] 2015-02-02 15:28
@fffw Thanks!

Here's a handy tutorial on launchd that I found - http://launchd.info/

**Comment by myleshorton** [comment] 2015-02-02 17:00
Awesome @fffw. Yeah it seems like one of the launchd approaches is the cleanest.

**Comment by myleshorton** [comment] 2015-02-02 17:02
The easiest way to do this is probably to not even use the Cocoa APIs and instead to just put the plist file in /Library/LaunchDaemons/ and to then call out to launchctl, but the Cocoa API approach might be cleaner not sure.

**Comment by oxtoacart** [comment] 2015-02-02 18:27
@myleshorton @fffw See https://github.com/kardianos/service

I'm playing with that as part of figuring out a generalized solution to installing the app.  Stay tuned.

**Comment by myleshorton** [comment] 2015-02-02 20:01
OK interesting @oxtoacart. What's the main thing you're trying to get out of https://github.com/kardianos/service? We run Lantern as a service now on OSX, and the Windows services APIs are notoriously hairy. It's also not immediately clear what the benefit of running as a service on Windows is versus just running on startup. Theoretically there's auto-restart type stuff, but in practice if Lantern's crashing we have other issues.

**Comment by oxtoacart** [comment] 2015-02-02 21:55
> What's the main thing you're trying to get out of https://github.com/kardianos/service?

As you know, one of my objectives is to avoid having anything but the barest bones installer code and having an executable that can stand on its own.  I think this will simplify initial distribution and will definitely simplify updates, since we can focus on just updating the binary rather the results of what an installer ran. However, we still want to follow platform-specific conventions like installing the executable to `c:\program files` on Windows or `/Applications` on Mac.

To accomplish this, we need to overcome two problems:

1. We need to be able to install privileged helpers that can do things like managing proxy settings without continually prompting the user for authorization.

2. For simplicity, we'd like the binary to be able to manage its own auto-updates.  However, since our program runs as an unprivileged program, it can't actually replace its own contents in the canonical installed location (e.g. `c:\program files`). One way to deal with this is to have the update performed by a privileged helper with root-level permissions.

The approach that I'm prototyping to solve both of these problems is based on the [BetterAuthorizationSample](https://developer.apple.com/legacy/library/samplecode/BetterAuthorizationSample/Introduction/Intro.html) that @fffw mentioned.  The key to this is to use a system service as opposed to a user service (which is what Lantern currently runs under on OS X).  I already know that the approach works on OS X and I suspect that it will work on Windows too, but I need to verify that as part of this prototype.

The main work-product is a new library called [escalated](https://github.com/getlantern/escalated) whose [godoc](http://godoc.org/github.com/getlantern/escalated) should give a good idea of what I'm shooting for.

Using escalated, we should be able to build a binary that runs in an unprivileged context but that can execute privileged stuff when it needs to.  This eliminates both the need for an actual installer (other than just placing the binary in the right location and adding a shortcut), and it even eliminates the need for the program to itself to have an install routine.  The only time that the user is prompted for authorization is when we first install the service, which happens lazily based on whenever the first privileged function is called.

The [demo](https://github.com/getlantern/escalated/blob/master/demo/demo.go) illustrates this in action.

The kardianos/service library just looked interesting because it provides a cross-platform way to register services.  I'm already finding that I've had to tweak it quite a bit, so I may not end up using it, but it helped me get started.

**Comment by myleshorton** [comment] 2015-02-02 22:12
@fffw so I would maybe just leave the privilege issue for now until we have a better idea of exactly how we'll handle it.

**Comment by fffw** [comment] 2015-02-08 16:16
Draft implementation at https://github.com/getlantern/pacon/pull/1

**Comment by fffw** [comment] 2015-02-14 16:14
Factored command line tool to seperate repo as per our pow wow discussion.

PR https://github.com/getlantern/pac-cmd/pull/1 is the tool.

PR https://github.com/getlantern/pac/pull/2 is the go code to use it.

**Comment by myleshorton** [comment] 2015-02-14 16:23
Awesome! I'll give it a look.

On Saturday, February 14, 2015, fffw <notifications@github.com> wrote:

> Factored command line tool to seperate repo as per our pow wow discussion.
>
> PR getlantern/pac-cmd#1 <https://github.com/getlantern/pac-cmd/pull/1> is
> the tool.
>
> PR getlantern/pac#2 <https://github.com/getlantern/pac/pull/2> is the go
> code to use it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/1902#issuecomment-74380894>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment] 2015-02-20 15:02
Library is ready, assigning it to myself to integrate.

**Comment by oxtoacart** [comment] 2015-02-23 19:50
This is now integrated.  Great work @fffw!

**Closed by oxtoacart** 2015-02-23 19:50 UTC
Labels: P1, PENDING MERGE
