### ISSUE TITLE
Error building android-lib

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2552] opened 2015-05-19 20:56 UTC
On OSX...

$ make android-lib
github.com/getlantern/tarfs
../../tarfs/tarfs.go:255: AssetFile.Size is ambiguous
../../tarfs/tarfs.go:255: cannot use f (type *AssetFile) as type os.FileInfo in return argument:
	*AssetFile does not implement os.FileInfo (missing Size method)
../../tarfs/tarfs.go:279: AssetDirectory.Size is ambiguous
../../tarfs/tarfs.go:279: cannot use f (type *AssetDirectory) as type os.FileInfo in return argument:
	*AssetDirectory does not im

**Comment by myleshorton** [comment] 2015-05-19 21:01
@fffw do you have any idea what this might be? Looks like something to do with genassets again?

**Comment by myleshorton** [comment] 2015-05-19 21:20
Or sorry I meant the above comment for @xiam!

**Comment by xiam** [comment] 2015-05-19 22:52
I could not reproduce the error so I checked out a clean repo and tried again, now I am having a completely different error, and just noticed the https://github.com/golang/mobile now requires Go 1.5:

```
# golang.org/x/mobile/app/internal/callfn
/src/golang.org/x/mobile/app/internal/callfn/callfn_arm.s:8 syntax error, last name: 0
make: *** [android-lib] Error 2
```

The temporal fix is this:

```
cd src/golang.org/x/mobile
git checkout cd5954b
```

We'll probably need to use gost here too.

After that I tried building again and it worked, so I am not sure what's happening, anyone else experiencing the same error?

**Comment by fffw** [comment] 2015-05-21 00:55
I encountered following error. Trying to touch docker to find out the reason.

```
finalize namespace chdir to /src/golang.org/x/mobile no such file or directoryFATA[0001] Error response from daemon: Cannot start container bbe437c89253c56ea9115ccea95343a017766527782d883b4f20e92b8eab36c9: finalize namespace chdir to /src/golang.org/x/mobile no such file or directory
```

**Comment by xiam** [comment] 2015-05-21 01:00
Probably the same thing, could you try this?

```
go get golang.org/x/mobile/cmd/gobind
```

Then try again.

**Comment by fffw** [comment] 2015-05-21 01:38
Oh I found it. I didn't `source setenv.sh` before `make android-lib`, so it just installed to another place. Should add it to `docker-golang-android` target.

**Comment by fffw** [comment] 2015-05-21 02:07
Although there are still lots of `javac` errors, the specific error in this issue is fixed by https://github.com/getlantern/lantern/pull/2558. @myleshorton Mind take a look?

@xiam I didn't face the issue you encountered. As the code is compiled inside `golang/mobile` docker image, shouldn't Go version be handled by the image itself?

**Comment by xiam** [comment] 2015-05-21 02:34
@fffw Yeah, everything should be managed within the container, the problem was that I didn't add golang/mobile with gost.

**Comment by atavism** [comment] 2015-05-24 16:03
If you build the library with the latest version of ``golang/mobile`` you end up with

```
05-24 11:49:39.885    1962-1998/? A/Go﹕ missing _rt0_arm_linux1
05-24 11:49:39.906    1962-1998/? A/libc﹕ Fatal signal 11 (SIGSEGV), code 1, 
fault addr 0x0 in tid 1998 (GoMain)
```

**Closed** 2015-05-28 16:04 UTC
Labels: P1
