### ISSUE TITLE
Lantern is not proxying when internet is reconnected

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2488] opened 2015-05-07 17:48 UTC
I couldn't reproduce this bug. Below are the possible steps that lead to this issue.

1. Start running lantern.
2. Disconnect wifi or router (basically no internet connection).
3. Connect to the internet.
4. Now lantern doesn't proxy(whatismyipaddress.com showed up my own ip address and not the proxy server address) though it shows up in the system tray as well as in the lantern browser where it shows the server connection.

**Comment by myleshorton** [comment] 2015-05-07 18:10
A few questions on this one @sheena3: 

1. You did see it not proxy at least one time right?
1. Did you by chance check chrome://net-internals under proxy to see if Lantern was set as the proxy in Chrome?
1. Windows right?
1. Is this specific to beta 5?

**Comment by sheena3** [comment] 2015-05-07 18:42
1. Yes, it happened today when my internet connection was down for about 5 mins. I tried reproducing it by disconnecting just wifi as well as router itself but couldn't.
2. No, I didn't. 
3. Yes
4. Yes

**Comment by myleshorton** [comment] 2015-05-12 16:40
To clarify on this one @sheena3 this isn't necessarily new in beta 5 correct? I'm wondering if we can push it to beta 6.

**Comment by sheena3** [comment] 2015-05-12 16:47
I came across this issue only in beta 5 and it didn't occur again. So yes @myleshorton, I think it is safe to push it to beta 6. If I ever come across this again, I'll update it here.

**Comment by myleshorton** [comment] 2015-05-28 16:10
Actually marking as a duplicate of #2291

**Closed by myleshorton** 2015-05-28 16:10 UTC
