### ISSUE TITLE
Spinning forever at the main page 

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4882] opened 2016-07-03 03:55 UTC
User reported https://github.com/getlantern/forum/issues/271 getting more info

**Comment by p3rcya** [comment] 2016-07-03 16:32
Many users reported the same problem! 

User1 with log:  https://github.com/getlantern/forum/issues/271#issuecomment-230139294

User 2 with log: https://github.com/getlantern/forum/issues/271#issuecomment-230149935

**Comment by p3rcya** [comment] 2016-07-04 03:17
Also here https://github.com/getlantern/forum/issues/285

**Comment by fffw** [comment] 2016-07-04 08:10
Both are connectivity issue to the assigned Lantern proxy. See also https://github.com/getlantern/lantern/issues/4905

**Comment by myleshorton** [comment] 2016-07-04 16:35
Any commonality in terms of OS and browser for this guys, or does it seem to apply to all OSes and browsers?

**Comment by myleshorton** [comment] 2016-07-04 16:38
For a little background here @p3rcya, I think this is largely the result of Lantern now relying on everything working immediately on startup for the UI to appear without any errors. So if you get assigned to a proxy that's blocked or has other problems, for example, this will arise. Getting the IP address and logs of these users would definitely be helpful.

**Comment by myleshorton** [comment] 2016-07-04 16:39
It's also always possible there's some other UI bug, or if this is just XP, for example, then it could be something simpler.

**Comment by p3rcya** [comment] 2016-07-04 16:39
@myleshorton I included the logs in my previous posts. @fffw investigated already and thought it caused by https://github.com/getlantern/lantern/issues/4905

**Comment by myleshorton** [comment] 2016-07-04 16:41
Oh sorry didn't realize the logs were included -- thanks @p3rcya. Yeah I would say this is the higher level bug, and #4905 is a solution to probably the most important aspect of it.

**Comment by p3rcya** [comment] 2016-07-04 16:41
@myleshorton I saw 10+ users complained about this. So this should be prioritized.

**Comment by p3rcya** [comment] 2016-07-05 02:49
Win 10 user log: https://github.com/getlantern/forum/issues/309#issue-163759508

**Comment by p3rcya** [comment] 2016-07-06 07:20
More log: https://github.com/getlantern/forum/issues/325#issuecomment-230696190

**Comment by p3rcya** [comment] 2016-07-06 17:31
More log: http://7tszt3.com1.z0.glb.clouddn.com/lantern_lantern.log.txt

**Comment by p3rcya** [comment] 2016-07-06 19:28
More: https://github.com/getlantern/forum/issues/325#issuecomment-230706614

**Comment by sunshine19090** [comment] 2016-07-07 19:38
@myleshorton how to reproduce this ?

**Comment by p3rcya** [comment] 2016-07-07 19:40
This is caused by proxying being blocked. @myleshorton maybe you have some
blocking script for sunny to test?

On Thursday, July 7, 2016, sunshine19090 <notifications@github.com> wrote:

> @myleshorton <https://github.com/myleshorton> how to reproduce this ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4882#issuecomment-231184650>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHjwqSEUAsTpqBzJPJYF9fz0hwMbbpouks5qTVXIgaJpZM4JDzBl>
> .
>


-- 
Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)

**Comment by myleshorton** [comment] 2016-07-07 20:40
Yeah this one's going to be tough to reproduce @sunshine19090

**Comment by p3rcya** [comment] 2016-07-08 18:54
User reported it present in 3.0.6 on Mac https://github.com/getlantern/forum/issues/421#issuecomment-231442826

**Comment by p3rcya** [comment] 2016-07-08 19:33
User reported it present in 3.0.6 on Win 10 https://github.com/getlantern/forum/issues/421#issuecomment-231452132

**Comment by sunshine19090** [comment] 2016-07-08 21:10
@myleshorton is there a way to assign a  blocked server to associate with my email address?

**Comment by p3rcya** [comment] 2016-07-08 21:20
@sunshine19090 You will have to use a Chinese VPN to simulate the blocking. I can give you a Chinese VPN and you can test from there directly without any deliberate configuration by  @myleshorton.  But keep in mind that all your traffic will be monitored.

**Comment by myleshorton** [comment] 2016-07-09 00:01
Yes, but it won't be blocked for you =).

On Fri, Jul 8, 2016 at 2:10 PM, sunshine19090 <notifications@github.com>
wrote:

> @myleshorton <https://github.com/myleshorton> is there a way to assign a
> blocked server to associate with my email address?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4882#issuecomment-231473604>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABF0nnVTo9SjBfoeRskgGS6PIjhYcWr4ks5qTrzOgaJpZM4JDzBl>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by p3rcya** [comment] 2016-07-12 02:00
More complaints now https://github.com/getlantern/forum/issues/524#issue-164974707

**Comment by myleshorton** [comment] 2016-07-12 02:35
I just offloaded that user with the two year plan @p3rcya, so hopefully it should start working again.

**Comment by p3rcya** [comment] 2016-07-12 02:40
@myleshorton @fffw But what happened? Pro server IP shouldn't be blocked. Even if they were blocked, the main UI should still load, right?

**Comment by myleshorton** [comment] 2016-07-12 02:50
Yeah that's a good question. Actually it should load no matter what via domain fronting, and it also should automatically use other proxies. It could be related to this:

https://github.com/getlantern/lantern/issues/4967

Actually, it would be useful to get the user's settings.yaml file in the c:/Users/username/AppData/Roaming/Lantern

**Comment by fffw** [comment] 2016-07-12 02:56
@myleshorton The full content of settings.yaml can be seen from logs. @p3rcya that user with 2 year plan didn't upload log yet.

**Comment by myleshorton** [comment] 2016-07-12 03:17
Good point @fffw. I was looking at the logs from the first user in that ticket, actually, which didn't include the beginning of the logs, which I believe is when the settings.yaml is logged.

**Closed** 2016-10-24 20:22 UTC
