### ISSUE TITLE
UI: When entering Promo code need confirmation of free month(s) added

### ISSUE THREAD

**Issue by carsonefv** [getlantern/lantern#4577] opened 2016-06-07 23:46 UTC
When entering Promo code there is currently no confirmation that free months have been added, can we make a notification saying "Three free months added!" or "One Free month added!" in place of the error text in #28BCD3 color text?

Current error text: 
![adfc24aa-fc71-4253-acee-3f59809e7de0](https://cloud.githubusercontent.com/assets/4400763/15878122/724429e8-2ce6-11e6-9599-072e37afd94c.png)

**Comment by sunshine19090** [comment] 2016-06-08 04:48
@carsonefv I assume that once the promo code is applied to get free months, then the apply promotion button will be disabled and the user has to use "Continue to checkout" link. In that case, I would like to suggest to have text something that goes like "Click on "continue to checkout" to proceed with the payment".

**Comment by myleshorton** [comment] 2016-06-08 04:56
This is a duplicate of #4541, but will reference this ticket from there.

**Comment by xiam** [comment] 2016-06-14 23:23
The user does not have to click on "continue checkout" anymore, the payment screen is shown right after entering a valid promotion code. Do we need something in between?

**Comment by myleshorton** [comment] 2016-06-14 23:29
Maybe a snack bar saying one month added or something?

**Comment by xiam** [comment] 2016-06-15 02:31
We can't use a snackbar that easily because we have a traslucent overlay, but I did this:

![screen shot 2016-06-14 at 9 30 23 pm](https://cloud.githubusercontent.com/assets/385670/16066238/3f87b65a-3277-11e6-9788-a89aa992ab4d.png)

**Comment by fffw** [comment] 2016-06-15 07:43
The dialog looks inconsistent with existing UI. An alternative would be:
1. Take out the "apply promotion" button.
2. Contact pro-server to check referral code once user input 6 characters, along with an animation.
3.1. Error happens: Show error beneath the input field.
3.2. Code is correct: Extend the button to "continue to checkout and receive three extra months"

**Comment by carsonefv** [comment] 2016-06-15 13:35
@xiam I like where @fffw is going with this, i think we should extend the bottom button to just say "Promotion applied! Continue to checkout"

I think since the screen already says the details about receiving three months after checkout we don't have to write that again. any thoughts on this @Derekf5 @chipstehr ?

**Comment by xiam** [comment] 2016-06-16 05:37
Sounds good, I think we can try that. We have some other pending issues that also need our attention, tho. So, I'm moving this to the backlog again, we'll have to review it later. 

Please consider merging the initial fix as a temporary solution in the meantime, it may look inconsistent but it's better than not having any feedback.

**Comment by sunshine19090** [comment] 2016-06-24 22:18
I see the promotion applied message right after clicking on apply promotion button. Closing.

**Closed by sunshine19090** 2016-06-24 22:18 UTC
