### ISSUE TITLE
Lack of rpm installer package

### ISSUE THREAD

**Issue by UsherBaby** [getlantern/lantern#4203] opened 2016-05-04 06:55 UTC
Is that possible to add rpm installer package ？

**Comment by xiam** [comment] 2016-05-16 15:33
OpenSUSE and Fedora are right behind Ubuntu, Mint and Debian, so this is important and we're going to work on this @UsherBaby, it's unfortunately not a top priority right now but we'll keep this in mind.

Marking as duplicate of https://github.com/getlantern/lantern/issues/3737

**Closed by xiam** 2016-05-16 15:33 UTC
Labels: P2
