### ISSUE TITLE
Lantern 1.5.17 is not loading - showstopper

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2319] opened 2015-03-20 16:53 UTC
While testing without internet connection, I found that Lantern couldn't connect to internet after I reset. But I am not sure if that could be the only reason as I did other actions too. Below are the steps. 

User: sunshine@getlantern.org

Steps:

1. In Get mode - Turn off internet connection. Got the message at the bottom "Your internet connection appears to be offline". 
2. Sent a message from Contact Lantern Developers screen (raised issue #2318)
3. Tried to add a friend (Got an error message. Expected.)
4. Tried to update proxy list manually (Able to add a new site. I don't know if that needs internet connection or not)
5. Changed the mode to Give mode. (Didn't get any error message)
6. I reset Lantern account. Got the message in the welcome screen "Please connect to internet to proceed"
7. I turned on the internet connection. Lantern started the loading process but didn't move on to the next step. It was still loading.
8. I quit lantern and reopened it. Lantern didn't open automatically. I had to use "Show lantern" in system tray icon. Lantern opened but still the same. It isn't loading.

![not loading](https://cloud.githubusercontent.com/assets/11394369/6756393/945c2238-cf4f-11e4-8e4f-443ec08d1e3b.png)

**Comment by oxtoacart** [comment] 2015-03-20 17:16
Okay, @sheena3 was able to work around this by stopping Lantern, removing the .lantern folder and starting lantern again.

Since this is on the old codebase that's been completely rewritten, I'm closing the bug.

**Closed by oxtoacart** 2015-03-20 17:16 UTC

**Comment by aranhoide** [comment] 2015-03-21 04:07
If we are closing bugs that can only be reproduced in the old version, shouldn't @sheena3 be testing the new version only?

**Comment by myleshorton** [comment] 2015-03-21 04:14
Yeah @sheena3 has really just been running the old version for reference to get to know the full version of the app, but yeah @sheena3 I would not open tickets against only that version. Thanks!
