### ISSUE TITLE
Win 10 doesn't show up in account management page

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4956] opened 2016-07-08 19:47 UTC
![image](https://cloud.githubusercontent.com/assets/7925929/16699605/fdb5d608-4509-11e6-9bfe-1ef308aab720.png)

![image](https://cloud.githubusercontent.com/assets/7925929/16699626/1a87f52c-450a-11e6-927a-11e86c490e40.png)

**Comment by p3rcya** [comment] 2016-07-08 19:49
@uaalto I think this is a backend problem because when the desktop version think Nexus 5 is the only device tied to the pro account as well

**Comment by sunshine19090** [comment] 2016-07-08 21:41
#4957 has the same issue but could be a different scenario. I didn't see the devices immediately after verifying the email address of unauthorized user.

**Comment by myleshorton** [comment] 2016-07-08 22:36
This is a duplicate of https://github.com/getlantern/pro-server/issues/210

**Closed by myleshorton** 2016-07-08 22:36 UTC
