### ISSUE TITLE
"x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#2398] opened 2015-04-16 19:30 UTC
Seen in loggly, seems to appear in FireTweet a lot.  Maybe something wrong with the CA setup there?  P0 because of FireTweet focus, and we're already on it anyway.

**Comment by myleshorton** [comment] 2015-04-18 14:01
To add a little more context, this is happening somewhere in fronted, although unfortunately we don't have the line number in logs. We should ideally at least report the actual root cert -- could be a MITM attempt.

**Comment by atavism** [comment] 2015-04-18 15:40
@myleshorton Created a PR for this after I saw your comment. It prepends log messages with the file name and line number: https://github.com/getlantern/flashlight-build/pull/182

**Comment by myleshorton** [comment] 2015-04-20 22:41
It would be great to just log the cert we don't trust.

**Comment by xiam** [comment] 2015-05-04 17:16
I have a few hints but still no luck debugging the exact cause of this, just a quick update, it looks like the @myleshorton suggestion it's a bit complicated to implement, this error is produced right within the Go's [crypto/x509](https://golang.org/src/crypto/x509/verify.go#L104) package, and this verification is triggered by a call to `httpClient.Do()`. I'm taking a different approach now trying to see if I can produce this error by deleting system's certs on a vm.

**Comment by xiam** [comment] 2015-05-04 17:29
Going to try one more thing with `vms.dialer.tlsConfig`, maybe we can get some debugging info from it.

**Comment by fffw** [comment] 2015-05-05 01:59
Started from Apr 28th, only tens of them reported each day, but it burst since May 4th.

I exported all messages of this error on 2.0.0-beta4 in last 7 days. The masquerade domains was not distributed evenly. One domain, *www.hawkhost.com*, contributed 436 out of 1394 items, occurred each day across timezones. Other domains only had less than 5 occurrences each.

**Comment by xiam** [comment] 2015-06-08 17:37
@fffw I'm following this issue and I was able to find some some recent logs of it, however the tlsInfo bit was not recorded, do you think we can remove [this check](https://github.com/getlantern/lantern/pull/2472/files#diff-d89b8c910f43a32ce0cc53f817ddef06R148) temporarily?

**Comment by fffw** [comment] 2015-06-08 22:01
Of course @xiam . It's just for logging purpose anyway.

**Comment by xiam** [comment] 2015-07-09 16:57
Looks like the error count for this one has decreased in beta6, only `636` occurrences this week so far.

I've noticed that most of the logged errors mention the same domain name, so that's a great clue. As far as I understand if this domain name is misbehaving it should not have be included by the genconfig script in the first place, right?

**Comment by xiam** [comment] 2015-07-09 16:59
Chrome does not complain about the authenticity of the CA.

![screen shot 2015-07-09 at 10 58 35 am](https://cloud.githubusercontent.com/assets/385670/8601478/8ccaa1da-2629-11e5-8a6e-dc42f7f135d7.png)

**Comment by myleshorton** [comment] 2015-07-09 19:32
Thanks @xiam. So keep in mind that we only consider CAs to be trusted if we explicitly mark them as trusted in our config. I wonder if there's a bug in our generation script? We could also relax our threshold for which CAs we consider trusted. See:

https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/flashlight/genconfig/genconfig.go#L289

**Comment by xiam** [comment] 2015-07-09 20:23
Thanks @myleshorton.

After running genconfig again and checking the git diff the failing domain name I identified was there:

```
git diff | grep failingdomainname
-		Domain:    "failingdomainname.com",
```

So genconfig identified the misbehaving domain name and removed it.

**Comment by myleshorton** [comment] 2015-07-09 23:16
Oh very interesting thanks @xiam! Come to think of it, on the config server how often is the config check run @aranhoide?

**Comment by xiam** [comment] 2015-07-17 20:00
I think we have identified that this problem is related to the default configuration and that it can be attenuated by running genconfig. Now it looks like we can silence the `tlsInfo()` output now. What do you think, team?

**Comment by myleshorton** [comment] 2015-07-17 20:03
Yeah sounds good to me @xiam. I think we ultimately could expand our trusted CA list slightly beyond our current 4 as well, which would mitigate appearances of this as sites switch CAs, but for now just silencing it sounds good to me.

**Comment by myleshorton** [comment] 2015-07-20 19:09
Closing this now that we have a good idea of the cause.

**Closed by myleshorton** 2015-07-20 19:09 UTC
Labels: P0
