### ISSUE TITLE
Public IP/GeoIP lookup in Go

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2213] opened 2015-02-02 22:52 UTC
Needs it be tunneled itself.

**Comment by oxtoacart** [comment] 2015-02-02 23:20
See https://github.com/getlantern/lantern/blob/392431a144e64a785eb9556f07a6f4a245c17321/src/main/java/org/lantern/util/PublicIpAddress.java#L81

Basically, our GeoIP lookup service returns the caller's IP, so you can just make a call to that.

**Comment by aranhoide** [comment] 2015-02-03 00:08
Any reason not to always do that?  I was going to add a ticket to implement GeoIP lookup in Go, but as a first step I'll just edit the title of this one.

**Comment by myleshorton** [comment] 2015-02-03 00:10
Makes sense @aranhoide!

**Comment by myleshorton** [comment] 2015-02-03 05:10
This is also partially already implemented on the go side @aranhoide at:

https://github.com/getlantern/flashlight/blob/master/statserver/peer.go#L143

The big problem there is that the call isn't tunneled.

**Comment by oxtoacart** [comment] 2015-02-03 13:15
Yeah, that existing call is only used in Give mode so tunneling isn't necessary.

**Comment by oxtoacart** [comment] 2015-02-03 17:09
> need to tunnel it for this ticket.

Most definitely :)

**Comment by xiam** [comment] 2015-02-17 17:51
I was thinking on using `github.com/getlantern/flashlight/util` to tunnel the `http.Get` call.

But, do we have a way to know if a client proxy is actually listening? If not, can we safely suppose it will be listening at that point in time? or should we try to proxy and see if it fails and try a naked request?

**Comment by oxtoacart** [comment] 2015-02-17 18:07
Good question.  You can use [waitforserver](http://godoc.org/github.com/getlantern/waitforserver) to wait for the client proxy to come up.

When running with `-role client` (i.e. Get mode), we should never make unproxied requests to any of our infrastructure. I noticed that we already do this in config.go and logged #2243.

**Comment by xiam** [comment] 2015-02-17 20:51
@oxtoacart Before being able to use waitforserver, we need to know in which interface and port is the client proxy listening to, and that's a value that can be changed by the user (`-addr`). I think the most simple way to do this is having an exported variable that holds the configuration for the running process, I mean, instead of declaring a [local variable](https://github.com/getlantern/flashlight-build/blob/devel/src/github.com/getlantern/flashlight/flashlight.go#L49) named `cfg`, we could set the value of an exported variable, let's say we add a new "Settings" variable to the `config` package and we set the value of `config.Settings` instead of setting `cfg`, other packages could access the settings by importing the `config` package and reading `config.Settings`.

The flashlight client and config packages make possible to have more than one proxies and configurations running in the same process, but the flashlight CLI only provides options for running just one client bound to one configuration, so I guess it won't have a big impact in the current way flashlight works.

What do you think?

**Comment by oxtoacart** [comment] 2015-02-17 21:12
The pattern that we're following right now is that whenever the config changes, we notify interested parties of that - see https://github.com/getlantern/flashlight-build/blob/valencia/src/github.com/getlantern/flashlight/flashlight.go#L121

If you have a method like lookupIp(), you could just call that in here.  Note - you'll need to call it twice, once for the first-time setup, and then once inside of the loop.

**Comment by oxtoacart** [comment] 2015-02-17 21:13
BTW @xiam, I really appreciate that you ask me for my opinion on such things!

**Comment by xiam** [comment] 2015-02-17 21:32
Oh, but of course! Got it now :-)! thanks @oxtoacart.

**Comment by oxtoacart** [comment] 2015-02-17 21:34
NP.  BTW, you might wonder why we don't have a more generic mechanism for subscribing to config updates.  The reason is that I like for my code to be as sequential as possible, and by doing it this way the config updates are applied in a predictable order and anyone can step through the code to see what's going on.

**Comment by myleshorton** [comment] 2015-02-17 22:43
We also need to ultimately send this to the UI via a websocket.

**Comment by xiam** [comment] 2015-02-18 02:50
Hello @atavism! What do you recommend for the websocket communication? I guess there are other parts already using websockets and I could make a simple function that can be used by an existent service.

**Comment by xiam** [comment] 2015-02-18 05:02
I ran into an interesting condition here and I think it could be important. My working branch is [issue-2213](https://github.com/getlantern/flashlight-build/tree/issue-2213).

I built and launched a flashlight proxy.

```sh
git branch
# * issue-2213
pwd
# ...flashlight-build/src/github.com/getlantern/flashlight
go build
 ./flashlight -role client -addr 127.0.0.1:9999 -statsaddr 127.0.0.1:1212 
```

Then I tried to test the proxy.

```
curl -x 127.0.0.1:9999 http://www.google.com/humans.txt --verbose
```

It seems to me it takes longer than usual to show a result and also produces more errors than the version currently in `devel`.

After a time the log is filled with messages like:

```
balancer: Dialing tcp://go-geoserve.herokuapp.com:80 with fronted proxy at fallbacks.getiantem.org:443 using masquerade set cloudflare
flashlight.statserver: Unable to getOrCreatePeer: Could not get response from server: "Get http://go-geoserve.herokuapp.com/lookup/162.159.247.184: read tcp 127.0.0.1:9999: use of closed network connection"
```

These messages are produced by the go-geoserve service that is not responding when we use the client created by `util.HTTPClient` to tunnel the request. Oddly enough, if we don't use the proxy to tunnel requests for go-geoserve, everything works as usual again.

Could you reproduce the same odd behavior? Do you think [forcing a timeout](https://github.com/getlantern/flashlight-build/blob/issue-2213/src/github.com/getlantern/flashlight/statserver/peer.go#L17) on the tunnel has anything to do with it?

Oddly enough, explicitly getting go-geoserve over a proxy sometimes does yield results:

```sh
curl -x 127.0.0.1:9999 "http://go-geoserve.herokuapp.com/lookup/198.41.249.170"  --verbose
# * Hostname was NOT found in DNS cache
# *   Trying 127.0.0.1...
# * Connected to 127.0.0.1 (127.0.0.1) port 9999 (#0)
# > GET http://go-geoserve.herokuapp.com/lookup/198.41.249.170 HTTP/1.1
# > User-Agent: curl/7.37.0
# > Host: go-geoserve.herokuapp.com
# > Accept: */*
# > Proxy-Connection: Keep-Alive
# > 
# < HTTP/1.1 200 OK
# < Content-Length: 1440
# < Content-Type: text/plain; charset=utf-8
# < Date: Wed, 18 Feb 2015 04:37:23 GMT
# * Server Cowboy is not blacklisted
# < Server: Cowboy
# < Via: 1.1 vegur
# < X-Reflected-Ip: 198.41.249.170
# < 
```

**Comment by oxtoacart** [comment] 2015-02-18 08:08
@xiam We had a problem with our domain-fronting infrastructure late last night.  Could you please try your test again and see if it's any better now?

**Comment by oxtoacart** [comment] 2015-02-18 08:12
@xiam Sorry I didn't make this clear earlier, but I think we'll actually need to use direct domain-fronting to geo.getiantem.org.  Otherwise, the IP address we get back will be the IP address of a proxy.  See https://github.com/getlantern/lantern/blob/devel/src/main/java/org/lantern/geoip/GeoIpLookupService.java for the Java implementation of this.

**Comment by atavism** [comment] 2015-02-18 12:15
> Hello @atavism! What do you recommend for the websocket communication? I guess there are other parts already using websockets and I could make a simple function that can be used by an existent service.

Hi, @xiam! Yes, it should be fairly easy for you to integrate this with the existing implementation. See https://github.com/getlantern/flashlight-build/blob/websocket/src/github.com/getlantern/flashlight/http/http.go and https://github.com/getlantern/flashlight-build/blob/websocket/src/github.com/getlantern/ui/app/js/app.js ; there's also code for displaying the self dot on the map already here: https://github.com/getlantern/flashlight-build/blob/websocket/src/github.com/getlantern/ui/app/js/vis.js and  https://github.com/getlantern/flashlight-build/blob/websocket/src/github.com/getlantern/ui/app/partials/vis.html

**Comment by oxtoacart** [comment] 2015-02-18 14:08
@xiam I just added explicit support for direct fronting to fronted.  See https://github.com/getlantern/flashlight-build/pull/56.

**Comment by xiam** [comment] 2015-02-18 16:19
@oxtoacart Thanks! It's working now, I'm glad that was a known problem and not something new.

**Comment by xiam** [comment] 2015-02-18 16:34
@oxtoacart I think it could be useful if I add a new `FrontedClient() (*http.Client, error)` exported function to the `util` package that we could use in cases like this. This function would create a `fronted.Dialer` with Host `fallbacks.getiantem.org` and will return a `DirectHttpClient()`. How does it sound?

**Comment by oxtoacart** [comment] 2015-02-18 16:45
@xiam I think the util package should remain stateless, and fronted dialers are actually stateful.  Client is already initializing fronted dialers based on the configuration - https://github.com/getlantern/flashlight-build/blob/devel/src/github.com/getlantern/flashlight/client/balancer.go#L22

Can you plug in there?

**Comment by xiam** [comment] 2015-02-18 18:08
@oxtoacart I'm getting a bit confused, I understand I could take a random (?) chained server from `cfg.ChainedServers` and use the `chainedServer.dialer()` to get a dialer, except this dialer is a `*balancer.Dialer` that does not satisfy the `frontend.Dialer` interface as it does not have a `DirectHttpClient()` method, and I think we don't have a way to access `DirectHttpClient()` from that context.

So, I could add a `DirectHttpClient()` method to `balancer.go`, right? that method will generate the `*http.Client` I need. But, in order to do that I would need to access the set of verified masquerades and take a verified masquerade, the problem with it is that the set is a not exported property that belongs to the `fronted` package.

I'm afraid I'm still not catching the trick here. Could you help me with another tip?

**Comment by oxtoacart** [comment] 2015-02-18 18:26
Chained servers don't domain front.  You need to grab a fronted server.

**Comment by xiam** [comment] 2015-02-18 19:15
@oxtoacart Thanks for the clarification! Sorry if I'm a bit slow here.

I'm now looking at ./flashlight/client/fronted.go, and this is the dialer I need: https://github.com/getlantern/flashlight-build/blob/devel/src/github.com/getlantern/flashlight/client/fronted.go#L60, but it is still transformed into a `*balancer.Dialer`, I think I could add a `DirectHttpClient` property to the `balancer.Dialer` struct and set it to `fd.DirectHttpClient`, then I could: 1) use any of the `Config.Client.FrontendServers` (I'd take a random one) as I already have access to the configuration from the statserver package or 2) figure out how to access the balancer.Balancer from the statserver package and use it to get a DirectHttpClient.

Does it sound better?

**Comment by oxtoacart** [comment] 2015-02-18 19:57
@xiam I would do something like this - https://github.com/getlantern/flashlight-build/pull/59

Note that I'm using the fronted.Dialer with the highest QOS to maximize our chance of success.

**Comment by xiam** [comment] 2015-02-18 20:00
@oxtoacart Thanks a lot! I really appreciate your help, Ox.

**Comment by oxtoacart** [comment] 2015-02-18 20:01
@xiam You're welcome.

**Comment by xiam** [comment] 2015-02-18 21:50
OK, so I created a geo package inside flashlight and I updated [statserver](https://github.com/getlantern/flashlight-build/commit/2dc7a717e277611fed2cde6bf25f292e26d4d56e#diff-2744f8edbc2908aaa5455b8045541f4bL147) to use it instead of a non-proxied request.

Now I want to use the same package to get geolocation information of the user and, as the websocket funcionality is in the websocket branch, I tried to merge [my changes](https://github.com/getlantern/flashlight-build/commit/2dc7a717e277611fed2cde6bf25f292e26d4d56e) (issue-2213) into that branch, but unfortunately I ran into some conflicts:

```
Auto-merging src/github.com/getlantern/tarfs/tarfs/main.go
CONFLICT (add/add): Merge conflict in src/github.com/getlantern/tarfs/tarfs/main.go
Auto-merging src/github.com/getlantern/tarfs/tarfs.go
CONFLICT (add/add): Merge conflict in src/github.com/getlantern/tarfs/tarfs.go
Auto-merging src/github.com/getlantern/tarfs/demo/resources.go
...
```

My branch was a spinoff of the valencia branch.

It would probably be better to copy a recent tarfs over my branch but I'm not sure, which branch has a tarfs package more up to date?

**Comment by oxtoacart** [comment] 2015-02-18 23:43
The valencia branch has the most recent tarfs package.

**Comment by xiam** [comment] 2015-02-19 18:07
Hello @atavism,

 I'm integrating my changes into the websocket branch but I got into some merge errors.

First, the tarfs, it had a lot of conflicts so I copied tarfs from the valencia branch since that's the most recent package version.

After that I found flashlight had some problems like:

```
++<<<<<<< HEAD
 +      "github.com/getlantern/nattywad"
 +      "github.com/getlantern/proxiedsites"
++=======
++>>>>>>> issue-2213
````

And things like that. I see that those merge errors are due to parts that were removed in the valencia branch but still remain in websocket.

Now, I think that I can safely overwrite the conflicting files with copies from valencia, those files would be:

```
src/github.com/getlantern/flashlight/client/config.go
src/github.com/getlantern/flashlight/config/config.go
src/github.com/getlantern/flashlight/config/flags.go
```

Would you worry for any file on that list?

**Comment by atavism** [comment] 2015-02-19 22:06
Hey @xiam, I would just work off this branch https://github.com/getlantern/flashlight-build/pull/62 @oxtoacart took care of most of those issues already there

**Comment by xiam** [comment] 2015-02-19 23:06
@atavism Fine, just did it with no problems. Let me take another look our websocket services to finish this up :-).

**Comment by oxtoacart** [comment] 2015-02-19 23:11
@xiam I'm doing a little bit of tweaking in the websockets code to make it a little bit more generic.  If you can wait until tomorrow morning, I should have it ready to go by then.

**Comment by xiam** [comment] 2015-02-19 23:48
@oxtoacart Sure. I'll continue investigating how things are currently working on the UI but I'll wait for your message to continue my integration.

**Comment by xiam** [comment] 2015-02-21 18:38
I opened a [PR](https://github.com/getlantern/flashlight-build/pull/82) that intends to close this ticket, the user's geolocation information is now sent to the client and logged to the console.

@atavism I looked at the code you told me is for drawing the point but I'm feeling a bit lost, do you think you could help me finding a way through? Here's the code that prints the geolocation information: https://github.com/getlantern/flashlight-build/blob/ed80c984e5f8eee35e837a0d11e3f9558a26aa33/src/github.com/getlantern/lantern-ui/app/js/services.js#L9. Thanks!

**Comment by atavism** [comment] 2015-02-21 19:53
@xiam Great! I added some code to update the model location field after the geolocation finishes. The point automatically gets drawn on the map once those attributes are set. See [here](https://github.com/getlantern/flashlight-build/commit/39941d14b493f7d001e4efd8d722205d3b1dd9dc). With those latest changes, you should see your point on the map now.

**Comment by xiam** [comment] 2015-02-22 13:48
Thanks a lot @atavism! Now I see the point.

Ha-ha.

**Closed** 2015-02-23 19:49 UTC
Labels: P1
