### ISSUE TITLE
Cannot build Docker image

### ISSUE THREAD

**Issue by anadahz** [getlantern/lantern#3347] opened 2015-12-12 18:10 UTC
While trying to build lantern via docker
```
$ docker build -f Dockerfile .
```
```
Rpmdb checksum is invalid: dCDPT(pkg checksums): grub2.x86_64 1:2.02-0.13.fc21 - u

The command '/bin/sh -c yum -y update && yum clean all' returned a non-zero code: 1
```

**Comment by xiam** [comment] 2015-12-15 04:47
Can you try with "make docker"?

**Comment by anadahz** [comment] 2015-12-15 11:56
The issue is not on the host machine but in docker process.
Have you tried and you can't reproduce this issue by running ```make docker``` ?

**Comment by xiam** [comment] 2015-12-15 12:10
Hello @anadahz -- Yes, I tried with `make docker` on an empty boot2docker machine and could not reproduce your problem. This is my version info:

```
> boot2docker version 
Boot2Docker-cli version: v1.8.0
Git commit: 9a26066
> docker --version
Docker version 1.9.1, build a34a1d5
```

Any other clue?

**Comment by fffw** [comment] 2015-12-15 12:22
@anadahz Can you try the diagnostic in https://github.com/docker/docker/issues/10180? Those steps are valuable to isolate the cause.

**Comment by anadahz** [comment] 2015-12-15 23:47
@xiam did you install anything on the empty boot2docker machine?
```
# make docker
-sh: make: not found
```

**Comment by xiam** [comment] 2015-12-16 00:44
@anadahz Please take a look at the instructions at https://github.com/getlantern/lantern, all the prerequisites (like make) are listed there. You'll need a Linux or OSX host to be able to build the docker image.

**Comment by xiam** [comment] 2015-12-16 04:17
I just built the image again on a different machine, so I'm closing this for now @anadahz.

**Closed by xiam** 2015-12-16 04:17 UTC

**Comment by anadahz** [comment] 2015-12-16 09:21
@xiam you mentioned that you have used boot2docker could you please share your steps to build lantern in boot2docker?

**Comment by xiam** [comment] 2015-12-16 12:55
@anadahz boot2docker is a program to run docker containers on a mac. See http://boot2docker.io/. Once you have the requisites you just go to the lantern directory and type `make linux`, `make darwin` or `make windows`.
