### ISSUE TITLE
pac-cmd makes networkd crashing on darwin

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#5204] opened 2016-08-24 01:47 UTC
After running for several hundred of times.

Seen when investigating https://github.com/getlantern/lantern/issues/3039

**Comment by fffw** [comment] 2016-08-29 07:28
For a record, here's the tutorial https://developer.apple.com/library/mac/documentation/Networking/Conceptual/SystemConfigFrameworks/SC_Intro/SC_Intro.html

**Comment by fffw** [comment] 2016-08-29 09:05
Ok from the [doc](https://developer.apple.com/library/mac/documentation/Networking/Conceptual/SystemConfigFrameworks/SC_Components/SC_Components.html#//apple_ref/doc/uid/TP40001065-CH207-CHDDEDFJ), `pac-cmd` has no way to crash `networkd` directly. System configuration framework communicates with `configd`, so does `networkd`.

The only practical way to reduce the possibility is to avoid setting proxy frequently and only to a few active network connections.

Below is the crash log I saw repetitively. It was happening during memory allocation when evaluating the PAC content. Users may experienced different issue than what I saw.

```
Aug 26 16:56:25 Camelot networkd[53288]: 1   0x7fff8cdede4f JSC::Heap::Heap(JSC::VM*, JSC::HeapType)
Aug 26 16:56:25 Camelot networkd[53288]: 2   0x7fff8cdeab70 JSC::VM::VM(JSC::VM::VMType, JSC::HeapType)
Aug 26 16:56:25 Camelot networkd[53288]: 3   0x7fff8cf8bb5d JSC::VM::createContextGroup(JSC::HeapType)
Aug 26 16:56:25 Camelot networkd[53288]: 4   0x7fff8ce09f42 JSGlobalContextCreateInGroup
Aug 26 16:56:25 Camelot networkd[53288]: 5   0x7fff8c5e0949 CreateJSContextForAutoConfigurationScript
Aug 26 16:56:25 Camelot networkd[53288]: 6   0x7fff8c5e2e8d PACCacheEntry_ConstructJSContext(void*)
Aug 26 16:56:25 Camelot networkd[53288]: 7   0x7fff8bf07881 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
Aug 26 16:56:25 Camelot networkd[53288]: 8   0x7fff8bee6fbc __CFRunLoopDoSources0
Aug 26 16:56:25 Camelot networkd[53288]: 9   0x7fff8bee64df __CFRunLoopRun
Aug 26 16:56:25 Camelot networkd[53288]: 10  0x7fff8bee5ed8 CFRunLoopRunSpecific
Aug 26 16:56:25 Camelot networkd[53288]: 11  0x7fff8bf279b1 CFRunLoopRun
Aug 26 16:56:25 Camelot networkd[53288]: 12  0x10fc0d918
Aug 26 16:56:25 Camelot networkd[53288]: 13  0x7fff932ca5ad start
Aug 26 16:56:25 Camelot networkd[53288]: 14  0x1
Aug 26 16:56:25 Camelot com.apple.xpc.launchd[1] (com.apple.networkd[53288]): Service exited due to signal: Segmentation fault: 11
```

**Comment by myleshorton** [comment] 2016-08-29 13:27
Moving to TODO

**Comment by oxtoacart** [comment] 2016-08-29 15:02
@fffw Nice analysis!

**Comment by fffw** [comment] 2016-08-30 07:03
Finally confirmed that even setting PAC on the only active interface "Wi-Fi" hundreds of times would make `networkd` crash, while `networksetup` doesn't cause the same issue. The code of `networksetup` is not open sourced unfornatunately.

**Comment by fffw** [comment] 2016-08-30 07:59
Tried a Python prototype using`SCDynamicStoreCopyProxies` and `SCDynamicStoreSetMultiple`, but the store didn't change at all though the call returns `True`. A quick Google shows that no one succeeded in this route.

**Comment by fffw** [comment] 2016-08-30 10:32
`networkd` will restart after crashing. Only an example when `networkd` hangs instead of crashes  can reproduce https://github.com/getlantern/lantern/issues/3039. Pause at this moment.

**Comment by oxtoacart** [comment] 2016-08-30 11:37
@fffw I tried decompiling the code using https://www.hopperapp.com/ but I wasn't able to find much of use.  I did see that the code is manually backing up /Library/Preferences/SystemConfiguration/preferences.plist.  Maybe it actually manipulates that file directly instead of using the API?

**Comment by myleshorton** [comment] 2016-09-01 18:54
I wonder if there's some issue where multiple calls from pac-cmd on multiple threads can somehow collide while `networksetup` gets around that somehow? If that's a possibility, I wonder if just shooting all the `pac-cmd` calls down the same go channel and just pausing in between each call for like 2 seconds at a minimum would do the trick.

What do you think @fffw and @ox?

**Comment by oxtoacart** [comment] 2016-09-01 19:23
@myleshorton I think @fffw tried pac-cmd by itself (single-threaded?).

**Comment by myleshorton** [comment] 2016-09-13 19:58
Hey @fffw I can easily reproduce this issue. Anything I should do to diagnose? I just haven't been able to find the cause even when reproducing it, but restarting networkd definitely works every time.

**Comment by fffw** [comment] 2016-09-14 02:25
@myleshorton can you do following to change pac quickly?

```
for i in {0..1000}; do
  ~/Library/Application\ Support/byteexec/pac-cmd on
http://127.0.0.1:16823/proxy_on.pac;
  ~/Library/Application\ Support/byteexec/pac-cmd off;
done
```

And see what's happening to networkd?

```
tail -f /var/log/system.log | grep networkd | grep -v "invalid URL scheme"
```

On my Mac, it caused `networkd` to crash, but never hung it.

**Comment by oxtoacart** [comment] 2016-10-17 21:43
Should be resolved by https://github.com/getlantern/flashlight/pull/88

**Comment by oxtoacart** [comment] 2016-10-27 21:32
@myleshorton is going to check whether or not this is still happening for him.

**Comment by oxtoacart** [comment] 2016-12-08 22:06
@myleshorton Still hasn't seen a crash since upgrading to the latest OS X, and he's been running Lantern a lot.

**Comment by oxtoacart** [comment] 2016-12-22 22:14
@p3rcya Have you seen any reports of this from people in the field who are running OS X Sierra 10.12.1 or newer?

**Comment by oxtoacart** [comment] 2017-01-05 22:14
@p3rcya Any updates?

**Comment by p3rcya** [comment] 2017-01-06 08:15
It takes a long time for people to upgrade to 10.12.1 and newer. So I'm still waiting.

**Comment by oxtoacart** [comment] 2017-01-19 22:07
Closing. If we get another report of this, we can reopen.

**Closed by oxtoacart** 2017-01-19 22:07 UTC
