### ISSUE TITLE
lantern doesn't work with chrome browser while IE is OK, really need help!!!

### ISSUE THREAD

**Issue by y11022053** [getlantern/lantern#3279] opened 2015-10-26 00:57 UTC
I launch the lantern, then the system LAN setting is set as "http://127.0.0.1:16823/proxy_on.pac", IE browser starts working.
BUT chrome doesn't work, I don't install any Switch proxy Extensions in chrome, and the settings of chrome says "Google Chrome uses the proxy of system".

**Comment by myleshorton** [comment] 2015-11-03 20:50
Thanks @y11022053 and sorry for the delay. With lantern running what do you see if you go here in Chrome:

chrome://net-internals/#proxy

**Comment by kururucn** [comment] 2015-12-19 16:58
I actually got the same problem. I checked my net-internals.
It says PAC script://127.0.0.1:16823/proxy_on.pac

**Comment by kururucn** [comment] 2015-12-19 17:04
Just for your information. Lantern works again after I uninstalled Xunlei, A chinese downloading software.

**Comment by chk007** [comment] 2015-12-22 09:33
Thanks @kururucn . I solved the problem with your method.

**Comment by iliul** [comment] 2015-12-23 02:00
@myleshorton it is a good idea,it's work

**Comment by yannxia** [comment] 2015-12-28 14:50
@kururucn Thanks, it's work, so cool

**Comment by soradolls** [comment] 2015-12-28 14:50
@kururucn any idea for running xunlei and lantern together?

**Comment by myleshorton** [comment] 2016-02-29 21:07
Closing in favor of #3679

**Closed by myleshorton** 2016-02-29 21:07 UTC

**Comment by wparam** [comment] 2016-05-04 08:25
It has nothing to do with xunlei, it is the chrome's proxy issue!

**Comment by headio** [comment] 2016-05-14 10:53
@kururucn Really helps, but sometimes I want to use xunlei to download video, any solution to fix it?

**Comment by xiam** [comment] 2016-05-14 12:22
Hello @headio, unfortunately we're not able to reproduce this error. Does the latest version (2.2.3) still fail for you? Could you send us a screencast or some pictures from the developer console? Is it the same thing reported here? https://github.com/getlantern/lantern/issues/4282#issuecomment-219205013

**Comment by headio** [comment] 2016-05-14 15:06
@xiam , thanks for reply. And, yes, I download lantern today, the version is 2.2.3.  My chrome version is 50, xunlei version is VIP version 1.0.33.358. I found when I reinstall xunlei and unselecte browser support, the issues gone. If you need reproduce error, I can install it and try.

**Comment by xiam** [comment] 2016-05-15 06:10
Interesting, could you share with me step by step instructions on how to
unselect browser support? I just need a way to reproduce that bug. Thanks!
