### ISSUE TITLE
WSASend tcp 127.0.0.1:8787: An established connection was aborted by the software in your host machi

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2901] opened 2015-08-08 00:12 UTC
Still few occurrences but it's currently showing on top.

```
{"extra":{"country":"IR","language":"en","logLevel":"ERROR","osArch":"386","osName":"windows","osVersion":"","timeZone":"IRDT","version":"2.0.0+stable (20150807.013721)"},"fullMessage":"ERROR flashlight.client: handler.go:96 Unable to respond OK: WSASend tcp 127.0.0.1:8787: An established connection was aborted by the software in your host machine.\n","hostname":"hidden","instanceid":"f46d047387de","locationInfo":"ERROR flashlight.client","message":"WSASend tcp 127.0.0.1:8787: An established connection was aborted by the software in your host machi","timestamp":1438992657546}
```

**Comment by uaalto** [comment] 2015-08-08 09:24
Thanks @xiam! It is a duplicate of https://github.com/getlantern/lantern/issues/2429, I will close this one.

**Closed by uaalto** 2015-08-08 09:24 UTC
