### ISSUE TITLE
Shows 0 MB remaining even for a first time user

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#5029] opened 2016-07-15 20:00 UTC
This is in 3.0.7

![shows 0mb](https://cloud.githubusercontent.com/assets/11394369/16886968/1ee6b7d4-4a8c-11e6-866b-a63d6c537500.png)

**Comment by sunshine19090** [comment] 2016-07-20 16:39
This happens in win 10 too. In edge browser, there is no progress in the bar but it still shows there is no more free data as well as there is no in-browser notification to upgrade.

**Comment by myleshorton** [comment] 2016-07-20 21:03
Are you sure you had never run Lantern before on those VMs/machines @sunshine19090?

**Comment by p3rcya** [comment] 2016-07-20 21:05
@myleshorton This is a newly created VPS instance in China.

**Comment by p3rcya** [comment] 2016-07-20 21:11
I've seen many users reporting it before. But this is not a priority now

**Comment by myleshorton** [comment] 2016-07-20 22:26
Interesting -- thanks @p3rcya

**Comment by sunshine19090** [comment] 2016-07-21 03:32
Yes @myleshorton , I never used lantern in those machines.

**Comment by p3rcya** [comment] 2016-07-27 19:47
This is a duplicate of https://github.com/getlantern/lantern/issues/4822

**Closed by p3rcya** 2016-07-27 19:47 UTC
Labels: P1
