### ISSUE TITLE
flashlight: Unable to respond OK: use of closed network connection

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2560] opened 2015-05-21 12:59 UTC
```
flashlight.client: handler.go:102 Unable to respond OK: use of closed network connection
```

This is the top error in Loggly for the new beta.

**Comment by atavism** [comment] 2015-05-27 04:19
Still seeing this as a top error in Loggly.

**Comment by myleshorton** [comment] 2015-05-27 21:30
I've been playing around with reproducing this with no luck. Tried lots of browsing and just downloading really large files. Do we report FireTweet logs to loggly BTW @atavism? If so, do they have a different version number? That would be useful if not.

**Comment by myleshorton** [comment] 2015-05-27 21:42
Looks like this popped up in one of our automated builds!

https://travis-ci.org/getlantern/lantern/builds/64322451

**Comment by fffw** [comment] 2015-05-29 14:12
If we search for "Unable to respond OK" on Loggly, we can find several messages saying connection closed by remote host, acrossing different versions. But this specific error only occurs on beta 5.

It must be caused by my changes [here](https://github.com/getlantern/lantern/commit/4ce2d7a5f3cf03deb2e1af5db952e38760007892), when the request completes very soon and hence closed `clientConn`, but `respondOK` never have a chance to run. The page will be unable to open in this case.

**Comment by myleshorton** [comment] 2015-05-29 16:29
Yeah that makes sense @fffw. I'll look at it. A WaitGroup would work but feels like overkill.

**Closed** 2015-05-29 17:59 UTC
Labels: P1
