### ISSUE TITLE
Sometimes the source has present date whereas our feed has past date

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4021] opened 2016-04-19 19:17 UTC
I came across this one article where the source article has today's date but in our feed, it shows yesterday's date. I am not sure how frequently this is happening. So please close this issue if this can be ignored.

The below article highlighted shows April 18th whereas the source shows April 19th. 

![image](https://cloud.githubusercontent.com/assets/11394369/14652208/345c88e4-0628-11e6-9dcb-9953de86f88b.png)

**Comment by fffw** [comment] 2016-04-20 10:47
Can it be caused by different time zone?

**Comment by xiam** [comment] 2016-04-20 15:02
That's most likely to be the cause @fffw. I'm not sending any timezone information.

@fffw, @atavism  is the ui capable of accepting an RFC 3339 date like `2006-01-02T15:04:05Z07:00`?

**Comment by fffw** [comment] 2016-04-20 15:38
js code should be able to handle time zone anyway, with whichever library
we can find.

**Comment by xiam** [comment] 2016-04-20 17:46
I checked and Go is handling this date conversion just fine, it uses GMT times tho, is this date being converted to local time @fffw?

**Comment by fffw** [comment] 2016-04-21 02:32
Ok I see @xiam . I'll handle time zone conversion in js code.

**Comment by fffw** [comment] 2016-04-21 03:18
Desktop parses `publishDate` as GMT time, and recognises time zone of browser when display.


There're cases that `publishDate` in RSS is not the same as what shows in article. One example is http://www.aljazeera.com/news/2016/04/frontrunners-trump-clinton-win-york-primaries-160420032200547.html 

In feed.json: `{"publishedDate": "2016-04-20T14:30:31Z",...}`,
in article page: `20 Apr 2016 09:32 GMT`,
which is same as what in `"meta" : {"LastModifiedDate": "Wed, 20 April 2016 09:32:51 GMT",...}`

FMPOV it's safe to ignore that difference.

**Comment by xiam** [comment] 2016-04-21 16:25
I think this is the expected behaviour, AJ uses GMT and the client translates that GMT into the local time, so unless we want to show timezones in the UI I think we're fine. Closing for now.

**Closed by xiam** 2016-04-21 16:25 UTC
Labels: P2
