### ISSUE TITLE
Don't open web browser on automatic startup

### ISSUE THREAD

**Issue by Gigglelife** [getlantern/lantern#2802] opened 2015-07-23 14:00 UTC

**Comment by fffw** [comment] 2015-07-23 15:02
Lantern doesn't have "Don't open web browser" option anywhere. Could you take a screenshot?

**Comment by aranhoide** [comment] 2015-07-23 16:41
@fffw: I think this is a feature request.

**Comment by myleshorton** [comment] 2015-07-23 17:13
Actually that's the way it's supposed to work regardless -- we'll implement it @Gigglelife thanks.

**Comment by sheena3** [comment] 2015-08-03 18:32
This is working fine in Mac. In windows 8.1, browser is still opening

**Comment by myleshorton** [comment] 2015-08-03 18:37
Thanks @sheena3. You don't have it set to open on startup in settings correct?

**Comment by sheena3** [comment] 2015-08-03 18:39
I did set it to open automatically on system startup.

**Comment by myleshorton** [comment] 2015-08-03 18:40
OK of course that makes sense -- checking now thanks!

**Comment by myleshorton** [comment] 2015-08-03 18:54
I can't reproduce this @sheena3. Are you sure you're using the latest installer that added this functionality?

**Comment by sheena3** [comment] 2015-08-03 18:56
Does this need latest installer? I used the installer that you sent me as
an update. Should I download it again to test this?

On Tue, Aug 4, 2015 at 12:24 AM, myleshorton <notifications@github.com>
wrote:

> I can't reproduce this @sheena3 <https://github.com/sheena3>. Are you
> sure you're using the latest installer that added this functionality?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2802#issuecomment-127369444>
> .
>



-- 
Regards,
Sunshine

**Comment by sheena3** [comment] 2015-08-03 19:16
I installed Lantern using the installer that I downloaded now. It is not working. Browser is opening with Lantern running irrespective of the settings.

**Comment by sheena3** [comment] 2015-08-06 17:37
I tested this in Chrome browser in Windows 8.1. It is still opening the browser when running Lantern automatically on restart.

**Comment by myleshorton** [comment] 2015-08-06 18:12
OK I think I see the problem -- I'm on it.

**Comment by sheena3** [comment] 2015-08-07 17:01
This works fine in windows. Tested in chrome, IE and Firefox. I will complete testing in Mac and Linux and then close this issue.

**Comment by sheena3** [comment] 2015-08-07 17:55
works fine. Closing

**Closed by sheena3** 2015-08-07 17:55 UTC
Labels: P2, QA
