### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by EdwardAutumn** [getlantern/lantern#5526] opened 2016-12-28 08:39 UTC
i have been experienced this issue constantly.

**Comment by GreatRain** [comment] 2016-12-28 09:28
so do i

**Comment by myleshorton** [comment] 2016-12-28 17:45
Thanks @EdwardAutumn and @GreatRain. Are you guys using pro or free? The main thing we've been seeing is just the network in general being insanely slow.

Did you submit your logs through Lantern? Finally, are you running on mobile or desktop?

Thanks again and sorry for the trouble.

**Comment by myleshorton** [comment] 2016-12-28 17:46
FYI @joesis interesting people are now seeing this as the context deadline exceeded.

**Comment by myleshorton** [comment] 2016-12-28 17:52
@aixi and @jingmingcn please follow this ticket for progress on this.

**Comment by EdwardAutumn** [comment] 2016-12-29 01:07
@myleshorton i'm using pro and running at desktop.i will provide the log when this happen again.

**Comment by myleshorton** [comment] 2016-12-29 04:22
Thanks @EdwardAutumn. I actually was just able to reproduce it, so hopefully will be able to figure something out.

@joesis this happened to me quite quickly (definitely not as long as the supposed timeout) in FireFox:

![image](https://cloud.githubusercontent.com/assets/1143966/21536728/4e2bf3ce-cd3b-11e6-9e05-ea5122f7571b.png)

**Comment by myleshorton** [comment] 2016-12-29 04:22
I'm curious about the keep-alive actually.

**Comment by myleshorton** [comment] 2016-12-29 04:24
Huh! Woah -- just noticed the HTTP/0.0. That's odd.

It happened on this page:

**Comment by myleshorton** [comment] 2016-12-29 04:25
And this is a free Lantern version - 3.5.11

**Comment by myleshorton** [comment] 2016-12-29 04:33
Seeing a lot of these in the logs:

```
Dec 29 04:20:09.828 - 6322m14s DEBUG flashlight.client: client.go:279 Connection to www.cbsnews.com:80 established too late, closing
```

**Comment by joesis** [comment] 2016-12-29 07:39
@myleshorton The `Keep-Alive` header has an incorrect format, should be `Keep-Alive: timeout=38`. I thought I created a patch in `proxy` package but not actually. Created a quick PR at https://github.com/getlantern/proxy/pull/6

**Comment by joesis** [comment] 2016-12-29 07:42
It doesn't seem to be the cause of early context cancellation, though.

**Comment by myleshorton** [comment] 2016-12-30 05:33
I merged in that fix @joesis. The other crazy thing is `HTTP/0.0`, but I can't imagine that's the cause either.

**Comment by myleshorton** [comment] 2016-12-30 19:41
I think there's something seriously messed up here @oxtoacart and @joesis -- I got this very easily just trying to navigate from twitter.com to facebook.com -- initially it kept reloading twitter.com and not even going to facebook!

**Comment by myleshorton** [comment] 2016-12-30 19:47
Yup I got this again during more testing, but the connection could not have been established too late because it timed out almost instantly!

```
Dec 30 19:46:59.324 - 8689m4s DEBUG flashlight.client: client.go:279 Connection to whatismyipaddress.com:80 established too late, closing
```

**Comment by myleshorton** [comment] 2016-12-30 20:55
It seems like this might be an issue with persistent connections somehow -- i.e. the persistent connection has timed out? still not sure.

**Comment by oxtoacart** [comment] 2016-12-31 02:05
@myleshorton I think you're right. Here's the problem - https://github.com/getlantern/proxy/blob/master/proxy_http.go#L88

The dialer is using whatever context was passed in to the intercept method. That context was constructed using WithTimeout here - https://github.com/getlantern/flashlight/blob/devel/client/handler.go#L21

WithTimeout actually just sets a hard deadline based on time.Now(), see https://golang.org/src/context/context.go?s=13917:13994#L426

For HTTP requests, that same dialer in proxy_http.go may be used multiple times over the lifetime of a user-agent connection, and each time it's used it still has that original deadline.

**Comment by oxtoacart** [comment] 2016-12-31 02:06
Really, there's no benefit to starting the context in the handler rather than in the dialer itself, so I'm going to just do that.

**Comment by oxtoacart** [comment] 2016-12-31 02:18
Actually, I'm looking at the original change to use `context` and I'm not really getting it. The only place where the context is referenced is in the dialer, to set timeout for the dial operation. We effectively used to do that already, just not using a context but instead using net.DialTimeout(). Since we don't seem to check the context deadline for anything other than dialing, it seems superfluous. I think the change that actually keeps Chrome from marking Lantern as a bad proxy is the fact that we now preemtively return 200 OK to CONNECT requests even if we can't dial downstream.

**Comment by oxtoacart** [comment] 2016-12-31 02:42
Here are a couple of pull requests with my attempt at resolving. I still need to do more manual testing, but so far so good.

https://github.com/getlantern/flashlight/pull/142
https://github.com/getlantern/proxy/pull/7

**Comment by joesis** [comment] 2016-12-31 02:58
@oxtoacart The reason Chrome marked bad proxy previously was due to ERR_CONNECTION_TIMED_OUT (https://github.com/getlantern/lantern/issues/5447#issuecomment-267544047). Each package has its own timeouts, but they can add up to more than 30s.

So to be clear, this issue only happens for HTTP, when the first connection to proxy server closed for some reason, and `http.Transport` trying to dial a new one? Sorry I didn't realize that there can be more than one upstream connections made in single `ServeHTTP`.

**Comment by oxtoacart** [comment] 2016-12-31 03:05
> Each package has its own timeouts, but they can add up to more than 30s.

I eliminated the context from packages that weren't checking the context for timeout anyway and whose operations didn't take very long. I think I kept the important part for your change here -

https://github.com/getlantern/flashlight/blob/9b3d5af3582d81fa849900b774461f65ac522e12/client/client.go#L279

> So to be clear, this issue only happens for HTTP, when the first connection to proxy server closed for some reason, and http.Transport trying to dial a new one?

Yes, it only happens for HTTP, but I don't think it requires the original proxy connection to have been closed. It's possible that the transport will also dial a new connection if the old one is busy.

BTW, my branch seems to be working well and I'm not seeing the "established too late" error.

**Comment by oxtoacart** [comment] 2016-12-31 05:23
Still running strong.

**Comment by oxtoacart** [comment] 2017-01-03 19:54
Release 3.5.12 which is currently in QA contains a fix for this.

**Comment by myleshorton** [comment] 2017-01-04 01:05
3.5.12 is now live globally everyone, so people experiencing this bug should be automatically updated shortly (unless you're on OSX -- on OSX you'll temporarily have to update manually at getlantern.org or at https://github.com/getlantern/lantern.

**Comment by EdwardAutumn** [comment] 2017-01-04 01:06
Thanks for the effort.happy new year everyone.

**Comment by p3rcya** [comment] 2017-01-06 23:06
I'm still seeing this in 3.6.0 
<img width="567" alt="image" src="https://cloud.githubusercontent.com/assets/20512438/21735877/bab8e668-d421-11e6-9596-97285cc28f6c.png">

**Comment by myleshorton** [comment] 2017-01-06 23:13
Any possible regression here @oxtoacart? You didn't see the rest of the response posted earlier @p3rcya right? Chrome on Win10?

**Comment by oxtoacart** [comment] 2017-01-06 23:22
@p3rcya how long did it take before you got that response?

**Comment by p3rcya** [comment] 2017-01-06 23:24
Chrome on windows 10. I've submitted the logs

**Comment by oxtoacart** [comment] 2017-01-06 23:32
@p3rcya Looking at your logs, it looks like all of your proxies are failing ?!

**Comment by oxtoacart** [comment] 2017-01-06 23:35
I just ran with what's on devel (similar to 3.6.0) and all my proxies are connecting successfully.

**Comment by p3rcya** [comment] 2017-01-06 23:36
Hmm. Maybe something wrong with the VPN temporarily. Now it's fine. Sorry about the false alarm. But we can make the msg more user friendly?

**Comment by oxtoacart** [comment] 2017-01-06 23:37
@p3rcya Yes, can you please log something for the user-friendliness? The reason users see this message now is that previously, we never even answered Chrome and it would go on to try and bypass the proxy, which would either work or trigger a different message from the browser.

**Closed by p3rcya** 2017-01-06 23:36 UTC
