### ISSUE TITLE
Mobile - Checkout - Checkout allows me to try to pay for Lantern even though the exact same email address already has an annual plan

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3936] opened 2016-04-08 20:58 UTC
I signed up for an annual plan on desktop, then tried signing up for a monthly plan on mobile.  I would have expected to get an error message telling me that I'm already signed up, or even better just have the device automatically authorized for Lantern Pro.

Interestingly enough, I'm able to successfully complete the purchase (other than the problem with #3938).  Does this mean that I've been double charged?  Does my account now have 2 years worth of credit (I have no way of knowing because the UI doesn't show this anywhere).

**Comment by myleshorton** [comment] 2016-04-18 18:23
Hey @oxtoacart did you link your accounts in this case or no? I guess you entered your phone number for both. @uaalto in that case it seems like the server side should recognize the same phone number, link the accounts, and return some code indicating that action. The client would then just switch into pro-mode, shortcutting the signup process. Does that make sense? 

This would also require client side changes indicating the shift to pro @xiam and @todd.

**Comment by oxtoacart** [comment] 2016-04-18 18:27
@myleshorton I first tried linking, but that didn't work (see #3933).  I agree that the best experience here is for the checkout process to recognize that the phone number is already signed up and to switch into the device linking flow.

**Comment by todd** [comment] 2016-04-18 18:30
Hey guys - feel free to delete this comment once you've seen it. Any time you mention @todd, I get subscribed to the notifications for the particular PR/Issue you're discussing and I have to come to the thread and unsubscribe myself. I'm obviously not the @todd you're referencing and it's a minor nuisance to have to do this so frequently. Moving forward, would you mind mentioning the handle of the person you're actually referencing instead of mine?

Thanks.

**Comment by oxtoacart** [comment] 2016-04-18 18:38
@todd Sorry about that!  If you'd like, I can try blocking your user id from the getlantern org, which I think will disable the auto-watching thing in case we fat-finger stuff in the future.  Other than you not having access to our repos, I don't think this has any other bad side effects.  Shall I give it a shot?

**Comment by todd** [comment] 2016-04-18 18:41
Oh, I suppose I could just ignore this repo instead of you blocking me. That way if I ever want to come back and have a look, I'm not blocked. Maybe I could have fixed this myself all along! Thanks, anyway.

**Comment by oxtoacart** [comment] 2016-04-18 18:42
@todd No problem, sorry for the noise.

**Comment by myleshorton** [comment] 2016-04-18 18:43
Hey sorry @todd - my fault!

**Comment by uaalto** [comment] 2016-04-18 18:49
If a user tries to purchase from a new phone, we have no way to tell that is a new purchase or an existing user. For that, the user needs to link the device.
It is true that we could check if the phone is registered (we need to hold an index to search for this fast, but that is ok). However, this isn't a general solution with the current device registering approach: device linking is just done to one device, the one used for identification. This simplifies some things (we've discussed this in the past so I won't get into it here, but we can talk about it if we see a new need for this). As a conclusion, this means  that we don't have all user devices registered, and no way to be sure that the device belongs to the user, except for the case of the linked phone.
For that particular case, we could make a test that replies with an error -- "Purchasing with an already registered phone". In this case, we could move the user to the device recover screen, where a code will be sent to the phone, he/she can write it there and the device will be relinked.

**Comment by oxtoacart** [comment] 2016-04-18 18:52
To be clear, here is what I did:

1. Purchase Pro from Desktop, where I was asked for my phone number
2. Then purchase Pro from Mobile, specifying the exact same phone number I specified for desktop

So, it's not a case of multiple phones, it's a case of Desktop + 1 Phone

**Comment by oxtoacart** [comment] 2016-04-18 18:53
BTW, for people who use both desktop and mobile, I could imagine this being a pretty common flow.

**Comment by uaalto** [comment] 2016-04-18 18:54
Yes, for that case, is what I mention at the end of  my previous comment. I agree that we definitely need to catch that and send the user to the linking screen for the input code to be inserted.

**Comment by uaalto** [comment] 2016-04-18 19:00
One thing though. If the user needs to input the phone when doing the purchase, that phone should already be linked and this should never happen. We need to handle only the case where the user didn't verify the phone but the code was sent to the device.

I'm still waiting for my Android, I need to test it ASAP. The company sent a refund and cancellation notice after a few weeks waiting -- it was intended to be ready in LA.

**Comment by oxtoacart** [comment] 2016-04-18 19:04
@uaalto I don't understand your most recent comment.  When you say that the phone should already be linked, what do you mean?  Do you mean the Lantern App on the phone has already been linked, or just that our server has recorded the phone number?

**Comment by uaalto** [comment] 2016-04-18 19:07
Because I can't see the Android app right now, I don't know if we have 100% chances that the user had linked a phone just prior purchasing, even when done from desktop. In other words, can a user purchase without providing the phone at all from the desktop?

**Comment by myleshorton** [comment] 2016-04-18 19:09
@uaalto. You always need to provide a phone number to purchase on desktop.

**Comment by myleshorton** [comment] 2016-04-18 19:13
So the change would be to:

1. Auto-link a user who you see purchasing from a verified phone number we already know about
1. Return some different HTTP response code in that case
1. Modify the client to reflect that case

**Comment by oxtoacart** [comment] 2016-04-18 19:15
@myleshorton I don't think we can auto-link because we don't know if the person registering at that point is actually in possession of the phone number.  I think the API should return an error that indicates this phone number already has an account, and in response to that the UI should offer the user to link this device, at which point our standard linking flow kicks in.

**Comment by uaalto** [comment] 2016-04-18 19:18
Yeah that's my point -- that is the solution I described at the beginning.
This would handle the most typical case. But if a user also has a tablet, then would need to go through the linking process manually for that other device, and we wouldn't be able to catch a purchase from there and redirect to the linking screen.

**Comment by oxtoacart** [comment] 2016-04-18 19:19
@uaalto

> But if a user also has a tablet, then would need to go through the linking process manually for that other device, and we wouldn't be able to catch a purchase from there and redirect to the linking screen.

I don't understand.  Since we always require the user to enter a phone number during checkout, we should always be able to detect if someone is checking out with a phone number that's already got an account, right?

**Comment by uaalto** [comment] 2016-04-18 19:21
Yes, but a user can have several phone numbers. I do. The tablet example is the typical one. In this case, we don't have knowledge of that second phone number.
Another case would be multiple computers.

**Comment by oxtoacart** [comment] 2016-04-18 19:24
@uaalto Oh, I think I understand what you're saying.  If someone checks out with a different phone number, we can't detect that they already have an account.  I think that's fine, we just need to be clear with people that we identify their account based on their phone number.

**Comment by oxtoacart** [comment] 2016-04-18 19:26
And again, just to make sure that the scope of this specific ticket is clear, the bug is that someone is allowed to check out twice with the exact same phone number.  Other cases are interesting to consider as well (and maybe deserve some new tickets?), I just want to make sure that the primary goal doesn't get confused :)

**Comment by uaalto** [comment] 2016-04-18 19:26
Yes, that's it. I think is fine too, I was just bringing it up because the solution wouldn't handle this case, which might become common.

**Comment by uaalto** [comment] 2016-04-18 19:27
Yes, the bug is clear and logged here: https://github.com/getlantern/pro-server/issues/89

**Comment by myleshorton** [comment] 2016-04-18 19:53
> @myleshorton I don't think we can auto-link because we don't know if the person registering at that point is actually in possession of the phone number. I think the API should return an error that indicates this phone number already has an account, and in response to that the UI should offer the user to link this device, at which point our standard linking flow kicks in.

It depends where we do it right? If we do it when the phone number is verified, we do know they have the number. That's why I said we can do it when the user is **purchasing from a verified phone number**. If we just do it after the verification step, we can just treat that as a device-linking step instead. In the user flow that's also a pretty natural place to do it.

**Comment by oxtoacart** [comment] 2016-04-18 20:13
@myleshorton I'm not sure if we're talking about the same thing.  The scenario I'm talking about is as follows:

1. User opens desktop app
2. User purchases Pro, specifying phone 111-111-1111
3. User receives verification SMS on their phone with code AAAA
4. User enters code AAAA on desktop and completes checkout
5. User installs Lantern Mobile
6. User opens Lantern Mobile
7. User purchases Pro, specifying phone 111-111-1111

At this point, they have entered a "verified" phone number, but we don't actually know whether this the same person or somebody else who put in the number 111-111-1111.  So, we still have to go through the usual linking flow including sending a new SMS.  Thus, the flow should continue with:

8. Mobile tells user that this phone number already has an account, would he like to link his phone?
9. User says yes
10. User receives verification SMS on their phone number with code BBBB
11. User enters code BBBB on the linking verification screen on mobile
12. Mobile app is now linked to the same account

**Comment by myleshorton** [comment] 2016-04-18 20:27
Yeah good to be explicit, so I'm just saying we make the change on the server side one step later (i.e. once the phone is verified), which allows us to skip a couple of steps at the end, as in:

1. User opens desktop app
2. User purchases Pro, specifying phone 111-111-1111
3. User receives verification SMS on their phone with code AAAA
4. User enters code AAAA on desktop and completes checkout
5. User installs Lantern Mobile
6. User opens Lantern Mobile
7. User purchases Pro, specifying phone 111-111-1111
8. User receives verification SMS on their phone with code BBBB
9. User enters code BBBB 
10. Mobile app is now linked to the same account with according UI changes.

**Comment by oxtoacart** [comment] 2016-04-18 20:34
@myleshorton Ah, I get it.  I like it.  The only thing I would add is some sort of messaging before step 10 to alert the user to the fact that we just went ahead and linked their phone since that phone number already has an account.

**Comment by myleshorton** [comment] 2016-04-18 20:37
Yeah that makes sense @oxtoacart -- like just verify they actually want to link the account.

**Comment by uaalto** [comment] 2016-04-19 20:06
The pro server now looks at the phone before allowing any purchase. Some thoughts:

* We cannot enforce in the Pro server that this parameter is provided, since the endpoint is used for purchasing from all devices. We need the client to tell us that it is actually a phone, and the phone number. This is logged here: https://github.com/getlantern/pro-server/issues/91, but ultimately the Android client should populate it.
* It returns an error code, so the client can use it to redirect to the linking screen.

**Comment by oxtoacart** [comment] 2016-04-19 21:08
@uaalto re:

> We cannot enforce in the Pro server that this parameter is provided, since the endpoint is used for purchasing from all devices. We need the client to tell us that it is actually a phone, and the phone number. This is logged here: getlantern/pro-server-client#10, but ultimately the Android client should populate it.

I'm a little confused by this comment.  Both desktop and mobile require that you provide a phone number to sign up for pro.  It doesn't matter whether the device itself is a phone or not, you just need to be in possession of that phone number so that you can get an SMS.

**Comment by uaalto** [comment] 2016-04-19 23:14
We need to verify, but that's not enforced by the logic in the server, but rather because we are using that flow in the screens. The point is that the /purchase endpoint doesn't require the phone parameter to work, ATM (i.e. we don't need it for the purchase itself). And, the phone linking is done through 2 other endpoints, dedicated to that.
But we can make that parameter mandatory, and the problem would be gone. But:

* We have the assume then that all screen flows in all devices will always be able to provide that information (we'll have the phone nubmer).
* The user needs to have the phone verified before the /purchase endpoint is hit.

If we can guarantee this conditions, I think we can safely enforce this parameter in the /purchase endpoint.

**Comment by oxtoacart** [comment] 2016-04-20 01:51
@uaalto 

Per @myleshorton, we want the UI flow to be as follows:

1. User enters phone number
2. User receives SMS
3. User enters code
4. Lantern Mobile tells user that the phone number already has pro and that their phone has been linked to their pro account

At this point, we haven't even called the /purchase endpoint yet, right?  Don't we need /user-link-validate to return a special response code instead?

**Comment by uaalto** [comment] 2016-04-20 02:09
Currently, if you try to link a phone already linked (that is, 1), it will reply with an error to signal that the phone is already linked. So no need to go through 2-4 in that case. A different endpoint is provided for that, which allows recovering a device that was already linked. So, it would work like this:

1. User enters phone number for linking
2. The client receives a reply from the pro server signaling that the device is already linked.
3. The client asks for a code for re-linking the device (/user-link-request)
4. The user enters the code sent to the phone, using /user-validate.
5. No need to purchase because the client is now aware of being Pro and got the data from /user-validate.

All this functionality is already provided by the Pro server. The link-request endpoint is used when we already have the link established (checked at 1).

**Comment by oxtoacart** [comment] 2016-04-20 02:18
Cool, is that error "user-link-already-configured"?  I can't find where in the code (i.e. what endpoint) we're returning that.

**Comment by uaalto** [comment] 2016-04-20 02:30
Yes, that's the error. I just realized that I removed it to "fix" a bug where a user couldn't link a different device once one was linked. We obviously want both things -- allow new device linking but reply that when the same device is provided. I'll do that.

**Comment by uaalto** [comment] 2016-04-20 18:46
I've added this check, so the users can still change their linked device, but make sure that if the new one is the same that was linked, it will signal that error.

**Comment by oxtoacart** [comment] 2016-04-20 19:01
Thanks @uaalto !

**Comment by myleshorton** [comment] 2016-05-27 22:27
Wait is this one close then @uaalto?

**Comment by uaalto** [comment] 2016-06-01 16:20
Sorry @myleshorton I missed this comment. Currently discussing this on the list, but it shouldn't be a big one if requires more changes.

**Comment by sunshine19090** [comment] 2016-06-23 19:32
@oxtoacart Now that we have eliminated the phone verification process, can I close this?

**Comment by sunshine19090** [comment] 2016-06-23 19:35
@oxtoacart I came across this situation with email too. Ability to use the same email in both mobile and desktop to purchase. Anyway, the user is paying twice instead of authorizing(we provide three devices to authorize) and it doesn't look bad that way. What do you think?

**Comment by oxtoacart** [comment] 2016-06-23 19:57
@sunshine19090 It sounds like the fundamental problem still remains, so let's keep this open.

**Comment by myleshorton** [comment] 2016-06-23 20:03
Hey @uaalto so it seems like with emails we might want to kick them out to the device linking screen if we've already seen a purchase with that email address, something like that. What do you think?

**Comment by uaalto** [comment] 2016-06-23 20:51
Just logged it here https://github.com/getlantern/pro-server/issues/172 to add the functionality to the pro-server.

**Closed** 2016-06-27 21:25 UTC
Labels: P1
