### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by aixi** [getlantern/lantern#5528] opened 2016-12-28 09:48 UTC
HTTP/0.0 503 Service Unavailable Date: Wednesday, 28-Dec-16 17:46:44 CST Keep-Alive: timeout: 38 context deadline exceeded

**Comment by jingmingcn** [comment] 2016-12-28 15:59
I believe this issue will be fixed in the begin of the new year. The lantern team is enjoying the holiday.

**Comment by myleshorton** [comment] 2016-12-28 17:52
Thanks @aixi and @jingmingcn - we will look into this. I'm marking this particular ticket as a duplicate of #5526, but please be aware that we're working on it and will post updates in that ticket. If you guys can tell us any more information that would be very helpful, such as operating system, the frequency of this error, whether you're running pro or free, etc.

Thanks again.

**Closed by myleshorton** 2016-12-28 17:52 UTC
