### ISSUE TITLE
Don't empty the %APPDATA%\Lantern directory when uninstalling

### ISSUE THREAD

**Issue by yfdyh000** [getlantern/lantern#3607] opened 2016-02-19 08:14 UTC
It is an unexpected empty my files place on %APPDATA%\Lantern dir (some try and hacks for yaml).
While emptying it makes sense, but I hope to have a checklist for files be deleted and confirm for unexpected files when uninstalling. Automatic update within the software is correct, you don't empty it, but rename the exe file to ".old" and other files is retained.

As well as, the installer should not be starts uninstall and install automatically after launch it, it is an unexpected behavior, although very intelligent and automatic.

**Comment by fffw** [comment] 2016-02-19 08:43
@yfdyh000 Keeping old file might be useful for this special case but we don't want to add complexity to those who want a tool that just works. We don't even encourage you to mess with config files, but when you want to, you can always backup them manually.

**Comment by yfdyh000** [comment] 2016-02-19 08:49
Well, I understand, although it is an unexpected result for launch installer, automatic start uninstalling and delete files.

**Comment by myleshorton** [comment] 2016-02-19 19:33
I'm actually going to reopen this @fffw. When users install new versions, we should at least be preserving their settings.yaml file that will be introduced in 2.1.0 to preserve settings across runs and versions.

**Comment by sunshine19090** [comment] 2016-03-01 20:16
@myleshorton Do we intend to preserve the settings even after uninstalling an older version and then installing a new one?

**Comment by myleshorton** [comment] 2016-03-01 20:18
Yes. Part of the issue is that when you download a new version of Lantern,
it automatically uninstalls the old one even if you never uninstalled it
yourself, so that process would remove those files otherwise.

**Comment by sunshine19090** [comment] 2016-03-01 20:28
Okay, I tried a straight forward scenario to check if it is working and it failed. @myleshorton Let me know if this is not a proper scenario to test it.

Steps:
1. Uninstalled Lantern and removed the lantern folder under appdata
2. Now installed 2.0.15 and modified the setting to not run lantern on system startup.
3. While 2.0.15 is still running, I installed 2.1.0. When checked the settings, it turned on the Run lantern on system startup setting.

Or should I check for some other settings here?

**Comment by oxtoacart** [comment] 2016-03-01 21:47
@sunshine19090 I've noticed this same behavior for a long time.  I actually thought it was intentional.

**Comment by sunshine19090** [comment] 2016-03-01 21:55
@oxtoacart I am little confused here. First of all, I don't see a settings.yaml file under lantern folder. Secondly, are we talking about preserving the settings other than the settings screen seen in the lantern page?

**Comment by oxtoacart** [comment] 2016-03-01 22:01
@sunshine19090 If I understand this bug correctly, all settings (including run lantern on system startup) should be preserved.  Where are you looking for the yaml file?

**Comment by sunshine19090** [comment] 2016-03-01 22:02
Under appdata/roaming/lantern folder @oxtoacart

**Comment by myleshorton** [comment] 2016-03-02 18:06
Hey @sunshine19090 so to be clear we intend to support preserving settings even when users uninstall old versions of lantern *moving forward*. The nature of this bug is that it existed in all prior Lantern versions, so it won't work with existing previous versions of Lantern.

**Comment by sunshine19090** [comment] 2016-03-02 19:40
Okay @myleshorton. So I will be able to verify this if we have a new build for 2.1.0, right? 

Also, I just uninstalled 2.1.0 and the files that remain are logs folder and the lantern-2.1.0.yaml file under appdata/roaming/lantern folder. So is this the yaml file that stores the settings?

**Comment by sunshine19090** [comment] 2016-03-02 20:40
@myleshorton I am seeing the settings.yaml file now. Also, I verified that the settings are preserved by uninstalling and installing 2.1.0. It did work! Closing this now.

**Closed by sunshine19090** 2016-03-02 20:40 UTC
Labels: P1, QA

**Comment by myleshorton** [comment] 2016-03-02 20:47
Awesome @sunshine19090! Sorry for my previous misleading answer to your question =).
