### ISSUE TITLE
[bug] Lantern not getting past first screen in some cases

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#2157] opened 2015-01-11 19:49 UTC
Reported by a user in the English language forum:

"""
Just downloaded lantern - seeing this issue:

![screenshot 2015-01-02 23 11 27](https://cloud.githubusercontent.com/assets/2204867/5696471/ffd54fc4-99d2-11e4-9d78-93f607c17eb1.png)

Looks like the internationalization features aren't working..

It's also stuck on this screen.
"""

**Comment by myleshorton** [comment] 2015-01-12 16:57
This is what you see in IE as well. I believe it's related to the CSP checks and isn't related to internationalization.

**Comment by myleshorton** [comment] 2015-01-12 18:17
So the big question here is whether this ever happens outside of IE. Lantern should pop up a message asking the user to install Chrome if they don't have Chrome or FF, but @aranhoide can you ask the user if he/she only has IE or one of the IE derivatives, such as Browser123.

**Comment by myleshorton** [comment] 2015-01-12 18:19
Let's investigate in the short term. If it is in fact IE, we can probably push this out or create another messaging ticket.

**Comment by aranhoide** [comment] 2015-01-12 18:37
I just asked in the forums.

**Comment by SethArchambault** [comment] 2015-01-12 22:24
I was on Google Chrome on Mac - Mountain Lion when I encountered this error.

**Comment by myleshorton** [comment] 2015-01-12 22:36
Thanks @SethArchambault that's extremely useful. We'll escalate this. If you wouldn't mind helping us with some debugging, that would be incredible. Here's what would be really useful:

1. Edit the file at ~/.lantern/serverAddress so you can easily remember the prefix and port
1. Open Chrome manually to http://127.0.0.1:port_you_chose/prefix_you_chose/index.html
1. Open up the Chrome dev console (command-option J)
1. Reload the page
1. Tell us what errors you see in the console.

I'm happy to walk you through any of those steps more, as we're really eager to get to the bottom of this.

**Comment by myleshorton** [comment] 2015-01-15 23:06
Just realized this is a duplicate of #1734

**Closed by myleshorton** 2015-01-15 23:06 UTC
Labels: P1
