### ISSUE TITLE
Mobile - Unable to authorize mobile phone for Pro after Desktop purchase

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3933] opened 2016-04-08 20:47 UTC
I purchased Lantern Pro from the desktop version and successfully got into pro mode.  I then installed Lantern Pro on my Nexus 4, went to the "Authorize Device for Pro" menu option, entered my phone number and then entered the code from my SMS.  At this point, the UI returned to the form asking me for my phone number.

Oddly, after closing Lantern and coming back in, even though I still wasn't in Pro mode, the option to Authorize Device for Pro disappeared from the menu.  Even after manually terminating Lantern, the menu option was missing.  Only after uninstalling and reinstalling Lantern did the menu option come back.  So, it looks like the authorization succeeded partially.

**Comment by myleshorton** [comment] 2016-04-18 20:46
Thanks @oxtoacart. It would be good to test this in the other direction as well.

**Comment by oxtoacart** [comment] 2016-04-18 20:49
@myleshorton Makes sense.  Do you or @uaalto or @xiam know of a way that I can clear my account state so I could test this?

**Comment by xiam** [comment] 2016-04-25 14:40
@oxtoacart removing `settings.yaml` should be enough

**Comment by oxtoacart** [comment] 2016-04-25 15:10
Thanks @xiam!

**Comment by myleshorton** [comment] 2016-04-25 20:32
I experienced a version of this too, except it took me to the payment page after I entered my phone number for authorizing the device.

**Comment by atavism** [comment] 2016-04-25 20:37
@myleshorton And you already have an active Pro account, that you signed up with on desktop? If you check logcat, after you authorize your device, it should print out your current account status

**Comment by atavism** [comment] 2016-05-31 21:21
Closing this as I'm unable to reproduce with the latest build (new error handling has a check for this now and users will always be signed in that have an active account).

**Closed by atavism** 2016-05-31 21:21 UTC
Labels: P1
