### ISSUE TITLE
langern Beta5（Mac） 用一会就会导致打开部分网址空白。

### ISSUE THREAD

**Issue by An0nymous0** [getlantern/lantern#2602] opened 2015-06-01 02:01 UTC
langern Beta5（Mac） 用一会就会导致打开部分网址空白。
打开墙外网页显示无法浏览。 鼠标放到langern图标上右键。 langern就闪退了。

Langern Beta5 (Mac) use will lead to open some URL blank.
Open wall displays unable to browse a Web page. Your mouse to right click on the langern icon. Langern Flash back.

**Comment by fffw** [comment] 2015-06-01 08:11
@An0nymous0 Thank you for reporting it!

It must because Lantern crashed somehow. Could you try following to help us spot the cause?

1. Quit Lantern

2. Launch a terminal window and run `/Applications/Lantern.app/Contents/MacOS/lantern`. Lantern will print logs to terminal.

3. When you find the browser window turns to blank, take a look at the terminal window, and check if the process aborted.

4. Paste relevant logs here or compress and mail to team@getlantern.org if you are unsure.

**Comment by An0nymous0** [comment] 2015-06-01 08:24
@fffw  This is the blank log open tieba.baidu.com, currently the Lantern is not collapse.
===============================================================================
Jun 01 08:20:56.717 - flashlight.client: server.go:1777 http: Accept error: accept tcp 127.0.0.1:8787: too many open files; retrying in 5ms
Jun 01 08:20:56.722 - flashlight.client: server.go:1777 http: Accept error: accept tcp 127.0.0.1:8787: too many open files; retrying in 10ms
Jun 01 08:20:56.864 - yamlconf: yamlconf.go:214 Unable to read updated config from disk: Error reading config from /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: open /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: too many open files
Jun 01 08:20:56.866 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 188.166.51.160:443: too many open files
Jun 01 08:20:56.910 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.53.147:443
Jun 01 08:20:56.996 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 188.166.54.89:443: too many open files
Jun 01 08:20:57.013 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 188.166.35.97:443: too many open files
Jun 01 08:20:57.153 - flashlight.client: server.go:1777 http: Accept error: accept tcp 127.0.0.1:8787: too many open files; retrying in 20ms
Jun 01 08:20:57.174 - flashlight.client: server.go:1777 http: Accept error: accept tcp 127.0.0.1:8787: too many open files; retrying in 40ms
Jun 01 08:20:57.215 - flashlight.client: server.go:1777 http: Accept error: accept tcp 127.0.0.1:8787: too many open files; retrying in 80ms
Jun 01 08:20:57.297 - flashlight.client: server.go:1777 http: Accept error: accept tcp 127.0.0.1:8787: too many open files; retrying in 160ms
Jun 01 08:20:57.415 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 188.166.35.97:443: too many open files
Jun 01 08:20:57.461 - flashlight.client: server.go:1777 http: Accept error: accept tcp 127.0.0.1:8787: too many open files; retrying in 320ms
Jun 01 08:20:57.482 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.211.112:443
Jun 01 08:20:57.583 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 188.166.11.211:443: too many open files
Jun 01 08:20:57.785 - flashlight.client: server.go:1777 http: Accept error: accept tcp 127.0.0.1:8787: too many open files; retrying in 640ms
Jun 01 08:20:57.868 - yamlconf: yamlconf.go:214 Unable to read updated config from disk: Error reading config from /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: open /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: too many open files
Jun 01 08:20:58.313 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 188.166.41.178:443: too many open files
Jun 01 08:20:58.316 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 188.166.35.97:443: too many open files
Jun 01 08:20:58.320 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 178.62.211.95:443: too many open files
Jun 01 08:20:58.322 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 188.166.4.202:443: too many open files
Jun 01 08:20:58.868 - yamlconf: yamlconf.go:214 Unable to read updated config from disk: Error reading config from /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: open /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: too many open files
Jun 01 08:20:59.351 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.205.156:443
Jun 01 08:20:59.857 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.243.211:443
Jun 01 08:21:00.348 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.245.144:443
Jun 01 08:21:00.749 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.237.157:443
Jun 01 08:21:00.761 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 128.199.48.56:443: too many open files
Jun 01 08:21:00.928 - yamlconf: yamlconf.go:214 Unable to read updated config from disk: Error reading config from /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: open /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: too many open files
Jun 01 08:21:01.627 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.56.50:443
Jun 01 08:21:02.279 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.33.78:443
Jun 01 08:21:02.512 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 188.166.15.68:443: too many open files
Jun 01 08:21:02.987 - yamlconf: yamlconf.go:214 Unable to read updated config from disk: Error reading config from /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: open /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: too many open files
Jun 01 08:21:02.998 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.225.108:443
Jun 01 08:21:03.147 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.4.28:443
Jun 01 08:21:03.250 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 178.62.230.37:443: too many open files
Jun 01 08:21:03.759 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 178.62.245.62:443: too many open files
Jun 01 08:21:03.838 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.253.155:443
Jun 01 08:21:04.554 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.243.211:443
Jun 01 08:21:04.694 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.245.144:443
Jun 01 08:21:04.939 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.4.28:443
Jun 01 08:21:04.969 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.53.147:443
Jun 01 08:21:05.342 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 188.166.11.211:443: too many open files
Jun 01 08:21:05.903 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.209.215:443
Jun 01 08:21:07.239 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.8.124:443
Jun 01 08:21:07.323 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.8.124:443
Jun 01 08:21:08.214 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.209.215:443
===============================================================================

**Comment by fffw** [comment] 2015-06-01 08:47
Thank you so much @An0nymous0 ! It's a known issue https://github.com/getlantern/lantern/issues/2330 but yet to be resolved.

**Comment by An0nymous0** [comment] 2015-06-01 08:49
@fffw Here is another section of not feeling well log, Google has caught. 5 minutes at Google。At this point the Lantern has not collapsed，This command starts the Lantern strange not collapsing。
===============================================================================
Jun 01 08:44:29.572 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: EOF
Jun 01 08:44:29.892 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.8.12:443
Jun 01 08:44:31.558 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.226.28:443
Jun 01 08:44:31.777 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.226.28:443
Jun 01 08:44:31.867 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.195.239:443
Jun 01 08:44:32.252 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.213.97:443
Jun 01 08:44:32.667 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: EOF
Jun 01 08:44:33.001 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.35.97:443
Jun 01 08:44:33.284 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.213.97:443
Jun 01 08:44:33.725 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 178.62.217.121:443: too many open files
Jun 01 08:44:34.036 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.22.93:443
Jun 01 08:44:34.225 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.22.93:443
Jun 01 08:44:34.412 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.211.112:443
Jun 01 08:44:34.538 - yamlconf: yamlconf.go:214 Unable to read updated config from disk: Error reading config from /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: open /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: too many open files
Jun 01 08:44:35.539 - yamlconf: yamlconf.go:214 Unable to read updated config from disk: Error reading config from /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: open /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: too many open files
Jun 01 08:44:35.791 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 178.62.243.211:443: too many open files
Jun 01 08:44:36.179 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.56.50:443
Jun 01 08:44:36.320 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 188.166.25.167:443: too many open files
Jun 01 08:44:36.413 - flashlight.geolookup: geolookup.go:117 Unable to get current location: Could not get response from server: "Get http://geo.getiantem.org/lookup/: Unable to dial masquerade buzzsumo.com: dial tcp 108.162.202.208:443: too many open files"
Jun 01 08:44:36.413 - flashlight.geolookup: geolookup.go:121 Waiting 100ms before retrying
Jun 01 08:44:36.517 - flashlight.geolookup: geolookup.go:117 Unable to get current location: Could not get response from server: "Get http://geo.getiantem.org/lookup/: Unable to dial masquerade 2ch.hk: dial tcp 162.159.253.5:443: too many open files"
Jun 01 08:44:36.517 - flashlight.geolookup: geolookup.go:121 Waiting 200ms before retrying
Jun 01 08:44:36.544 - yamlconf: yamlconf.go:214 Unable to read updated config from disk: Error reading config from /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: open /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: too many open files
Jun 01 08:44:36.708 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.8.12:443
Jun 01 08:44:37.296 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.209.13:443
Jun 01 08:44:37.489 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.209.13:443
Jun 01 08:44:37.784 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.226.28:443
Jun 01 08:44:38.391 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.226.28:443
Jun 01 08:44:38.423 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.56.50:443
Jun 01 08:44:38.461 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.11.211:443
Jun 01 08:44:38.779 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 128.199.54.181:443
Jun 01 08:44:39.346 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.56.50:443
Jun 01 08:44:39.524 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 128.199.54.181:443
Jun 01 08:44:39.636 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 178.62.225.108:443: too many open files
Jun 01 08:44:39.636 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 178.62.245.144:443: too many open files
Jun 01 08:44:39.664 - yamlconf: yamlconf.go:214 Unable to read updated config from disk: Error reading config from /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: open /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: too many open files
Jun 01 08:44:39.985 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.234.129:443
Jun 01 08:44:40.570 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 178.62.245.182:443: too many open files
Jun 01 08:44:40.669 - yamlconf: yamlconf.go:214 Unable to read updated config from disk: Error reading config from /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: open /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: too many open files
Jun 01 08:44:40.676 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.4.202:443
Jun 01 08:44:41.673 - yamlconf: yamlconf.go:214 Unable to read updated config from disk: Error reading config from /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: open /Users/An0nymous/Library/Application Support/Lantern/lantern.yaml: too many open files
Jun 01 08:44:41.907 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.41.19:443
Jun 01 08:44:41.968 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 128.199.54.181:443
Jun 01 08:44:42.105 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 178.62.230.115:443: too many open files
Jun 01 08:44:42.181 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 128.199.54.181:443
Jun 01 08:44:42.344 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.227.165:443
Jun 01 08:44:42.518 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.209.13:443
Jun 01 08:44:42.599 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.226.28:443
Jun 01 08:44:42.711 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.31.196:443
Jun 01 08:44:42.942 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.41.19:443
Jun 01 08:44:42.944 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.21.122:443
Jun 01 08:44:43.411 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.41.19:443
Jun 01 08:44:43.656 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.227.165:443
Jun 01 08:44:43.805 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.8.12:443
Jun 01 08:44:43.916 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.54.156:443
Jun 01 08:44:44.532 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 128.199.48.56:443: too many open files
Jun 01 08:44:44.805 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 188.166.31.196:443
Jun 01 08:44:44.999 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 178.62.195.239:443
Jun 01 08:44:45.398 - balancer: balancer.go:90 Dialing tcp://api.shodan.io:443 with (trusted) chained proxy at 128.199.54.181:443
Jun 01 08:44:46.032 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 178.62.244.225:443: too many open files
Jun 01 08:44:46.032 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 178.62.223.98:443: too many open files
Jun 01 08:44:46.032 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 178.62.225.6:443: too many open files
Jun 01 08:44:46.032 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 178.62.224.81:443: too many open files
Jun 01 08:44:46.033 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 178.62.249.247:443: too many open files
Jun 01 08:44:46.033 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 188.166.46.179:443: too many open files
Jun 01 08:44:46.033 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 188.166.18.201:443: too many open files
Jun 01 08:44:46.033 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 188.166.6.11:443: too many open files
Jun 01 08:44:46.033 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 188.166.60.45:443: too many open files
Jun 01 08:44:46.033 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 178.62.215.72:443: too many open files
Jun 01 08:44:46.033 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 178.62.247.181:443: too many open files
Jun 01 08:44:46.034 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 188.166.8.124:443: too many open files
Jun 01 08:44:46.046 - balancer: dialer.go:132 Error on testing humans.txt: Get http://www.google.com/humans.txt: Bad status code on CONNECT response: 504

**Comment by myleshorton** [comment] 2015-06-17 17:50
Thanks @An0nymous0! As @fffw said, this should be fixed in our latest version. Closing as a duplicate of #2330. 

Can you try the latest version at:

ttps://s3.amazonaws.com/lantern/lantern-installer-qa.dmg

**Closed by myleshorton** 2015-06-17 17:50 UTC
