### ISSUE TITLE
Mobile - Some articles are missing their abstracts

### ISSUE THREAD

**Issue by percyalpha** [getlantern/lantern#4034] opened 2016-04-20 20:27 UTC
On Android,
1. Abstract of some articles are missing, e.g most recent articles on FtChinese, even though the RSS feed does include abstract. CDT export full article content, we can just truncate it as abstract. Currently, no abstract is shown. 

This is a specific ft Chinese article

```
<item>

 <title>
<![CDATA[ 腾讯董事长马化腾捐1亿腾讯股做慈善 ]]>
</title>
<description>
<![CDATA[
<img src="http://i.ftimg.net/picture/6/000060836_piclink.jpg"/><br/>唐•温兰伦敦报道 <br><p>中国最大互联网企业之一的董事长承诺向慈善事业捐赠逾20亿美元，此举将使他加入高科技领域最大慈善家马克•扎克伯格(Mark Zuckerberg)和比尔•盖茨(Bill Gates)的行列。</p> <p>腾讯控股(Tencent Holdings)昨日表示，创始人和首席执行官马化腾(Pony Ma)计划捐献1亿股腾讯股票给一家正在筹建中的“个人公益慈善基金”。马化腾此前建立了一家名为腾讯基金...
]]>
</description>
 <link>http://www.ftchinese.com/story/001067165</link>
<pubDate>Wed, 20 Apr 2016 11:25:53 GMT</pubDate>
 </item>
 
```

![image](https://cloud.githubusercontent.com/assets/7925929/14689312/a5762a70-06fb-11e6-92f2-f362f0456783.png)

**Comment by myleshorton** [comment] 2016-04-21 04:33
Thanks @percyalpha. These should really be two separate tickets though. Would you mind separating them?

**Comment by myleshorton** [comment] 2016-04-21 04:34
I'm thinking we can handle both of these on the server side @xiam. What do you think?

**Comment by fffw** [comment] 2016-04-21 07:32
The second one should be caused by string truncation at client side.

**Comment by xiam** [comment] 2016-04-21 15:56
I can take a look at 1, not sure on 2.

**Comment by myleshorton** [comment] 2016-04-21 18:49
I moved #2 to another ticket and will assign to you @fffw 

https://github.com/getlantern/lantern/issues/4049

**Comment by xiam** [comment] 2016-04-21 21:59
Hey @atavism, this is the ftchinese feed; I looked at the generated file and we have content for those entries on `content` and `contentSnippet`, could you check this particular feed and let me know if something seems wrong with that data? Thanks

**Comment by myleshorton** [comment] 2016-04-22 17:34
OK I'll assign this to @atavism for now. @atavism feel free to kick this back over to @xiam if it seems like it can't be solved on the client side.

**Comment by atavism** [comment] 2016-04-22 19:15
@xiam Thanks! It looks like a those ``content`` and ``contentSnippet`` entries contain image tags. How are you handling those on desktop? Could we strip them out on the server?

**Comment by xiam** [comment] 2016-04-22 19:19
I think @fffw is printing them as HTML. I can do the HTML stripping if you
like, not sure if that would have secondary effects.

**Comment by atavism** [comment] 2016-04-22 19:23
Yeah, that would be great. I think it should be fine. If you want to leave it the same on desktop, you could add a separate field.

**Comment by atavism** [comment] 2016-04-22 21:14
Ok, this should be fixed with https://github.com/getlantern/lantern/pull/4059

**Comment by sunshine19090** [comment] 2016-04-27 19:18
I am seeing abstract in all the articles in the english feed. @atavism  Is this specific to Chinese feed?

**Comment by atavism** [comment] 2016-04-27 19:20
Yes, I'm seeing summaries for all articles in the Chinese feed too. Think we can close this

**Comment by sunshine19090** [comment] 2016-04-27 19:21
Okay, thanks @atavism.

**Closed by sunshine19090** 2016-04-27 19:21 UTC
Labels: P1, QA

**Comment by myleshorton** [comment] 2016-04-27 20:38
And you guys specifically looked at the financial times feed right @atavism and @sunshine19090?

**Comment by atavism** [comment] 2016-04-27 20:41
@myleshorton Yep, the FT Chinese feed has summaries now too.

**Comment by myleshorton** [comment] 2016-04-27 21:12
Awesome @atavism thanks!
