### ISSUE TITLE
IE 11 sometimes displays an error opening Lantern page after restarting

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2719] opened 2015-07-12 17:25 UTC
Steps:

1. Make IE as default browser
2. In Lantern browser, change the setting to Run Lantern automatically on System Startup
3. Shut down the system
4. When IE opens (WiFi is already turned ON) the Lantern browser, it says "This page can't be displayed". Same goes for the manoto TV fb page.

I tried "Show Lantern" in system tray to reopen but it didn't work either. I had to quit Lantern and reopen it. That too didn't work. It worked only when I tried for the third time.  Let me know if you need the logs. Even the normal unblocked sites didn't open (google.com, gmail.com, yahoo.com etc.). That's confusing!!!

P.S: I checked in chrome and Lantern was proxying. It is just that it doesn't work in IE.

**Comment by myleshorton** [comment] 2015-07-12 20:10
Do you have any other circumvention or proxy tools installed on that machine @sheena3? Is it possible they're overriding Lantern's settings?

**Comment by sheena3** [comment] 2015-07-13 12:55
No @myleshorton, I don't have any other proxy tools installed in my machine. Also, this is happening in safari too. Checking in chrome now. Will update here.

**Comment by sheena3** [comment] 2015-07-13 13:57
Okay, the problem is only with IE and Safari. In all the other browsers, this functionality is working fine.

**Comment by myleshorton** [comment] 2015-07-13 16:12
Thanks @sheena3. What version of windows are you running? What version of IE and Safari?

**Comment by sheena3** [comment] 2015-07-13 17:35
Windows 8.1, IE 11 and safari 8.0

On Mon, Jul 13, 2015 at 9:42 PM, myleshorton <notifications@github.com>
wrote:

> Thanks @sheena3 <https://github.com/sheena3>. What version of windows are
> you running? What version of IE and Safari?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2719#issuecomment-120983244>
> .
>



-- 
Regards,
Sunshine

**Comment by myleshorton** [comment] 2015-07-13 17:45
OK thanks @sheena3! I'm definitely able to reproduce this at least some of the time. I'll keep working on it.

**Comment by myleshorton** [comment] 2015-07-13 18:30
Does this happen for you every time you restart @sheena3 or only some of the time? What is your DNS server set to?

I'm able to get this about one out of every 3 or 4 runs myself, currently just testing with IE.

**Comment by myleshorton** [comment] 2015-07-13 18:37
Interestingly I also periodically have this issue with IE on restart regardless of Lantern -- i.e. I get the "This page can't be displayed" message just on restart with Lantern not even installed, but with other browsers working.

**Comment by myleshorton** [comment] 2015-07-13 19:50
OK -- more info. The above finding was actually because Lantern's proxy settings were in effect on the machine. Chrome and FF detected that the proxy wasn't running at all and just bypassed it while IE, arguably correctly, just displayed a warning message.

**Comment by sheena3** [comment] 2015-07-14 16:35
For me, it happens every time that I restart or shutdown my system. Also, IE doesn't recognize that Lantern is running but other browsers does. So I couldn't access a blocked site in IE but I could access the same in other browsers. 

p.s: This happens only when IE is default browser.

**Comment by fffw** [comment] 2015-07-15 15:08
I still encounter this error on IE 11 + Win8.1 with new code. No web page can be open if I run Lantern manually after OS started up (without auto-start). About one minute later, IE works normally. It may be specific to my environment, but worth of inspection. It seems that IE doesn't retry PAC url.

**Comment by myleshorton** [comment] 2015-07-15 15:11
Interesting @fffw thanks. So Lantern does work with auto-start for you in that case, is that right?

If so, this sounds like a slightly different error -- basically Lantern doesn't work right away on IE with restart but with starting manually. Does that sound correct?

**Comment by fffw** [comment] 2015-07-15 15:24
Sorry for the ambiguity @myleshorton. auto-start doesn't work either. To conclude my finding: IE11 can't open any page if Lantern opens immediately or within 1 min after Win8.1 startup. Chrome can open http://127.0.0.1:16823/, blocked and non-blocked page at the same time.

**Comment by myleshorton** [comment] 2015-07-15 15:58
Gotcha thanks @fffw. And that's using the latest on valencia right? Or using http://lantern.s3.amazonaws.com/lantern-installer-2719.exe?

**Comment by sheena3** [comment] 2015-07-15 17:51
Works fine now.Closing!!

**Comment by myleshorton** [comment] 2015-07-15 17:52
Oh good! Thanks @sheena3!

**Comment by sheena3** [comment] 2015-07-30 18:06
Reopening this as I encounter this issue again.

I can reproduce this by running Lantern while restarting the system. This makes IE unable to open the pages for a while as @fffw commented. 

If Lantern is not running while restarting the system, then IE opens the pages normally.

**Comment by myleshorton** [comment] 2015-07-30 18:10
Thanks @sheena3! Is Lantern set to run automatically on startup?

**Comment by sheena3** [comment] 2015-07-30 18:20
No @atavism , it is not

**Comment by sheena3** [comment] 2015-07-30 18:21
I will check with the option enabled

**Comment by sheena3** [comment] 2015-07-30 18:21
sorry @myleshorton

**Comment by myleshorton** [comment] 2015-07-30 18:33
Great @sheena3. Yeah I'm curious if it works with Lantern set to run automatically on startup.

**Comment by sheena3** [comment] 2015-07-30 18:40
Same behavior @myleshorton. Even after setting Lantern to run automatically on system startup, IE is unable to open the sites for a while. And this happens only when I let Lantern run while restarting.

**Comment by myleshorton** [comment] 2015-07-30 18:43
Thanks @sheena3. So I realize we actually have duplicate tickets for this. I should have closed #2776 initially since it's newer, but now the more active discussion is happening there. Let's close this one and discuss further in #2776.

**Closed by myleshorton** 2015-07-30 18:43 UTC
Labels: P1

**Comment by sheena3** [comment] 2015-07-30 18:47
Cool - Thanks, @myleshorton!
