### ISSUE TITLE
Flashlight client errors responding with OK: Unable to respond OK: WSASend tcp 127.0.0.1:8787: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2429] opened 2015-04-22 21:44 UTC
Appearing in loggly:

```
flashlight.client: Unable to respond OK: WSASend tcp 127.0.0.1:8787: An existing connection was forcibly closed by the remote host.
```

**Comment by xiam** [comment] 2015-04-27 21:15
Got a bunch of those messages too:

Apr 27 21:14:54.079 - flashlight.client: handler.go:102 Unable to respond OK: write tcp 127.0.0.1:61555: broken pipe
Apr 27 21:14:55.574 - flashlight.client: handler.go:102 Unable to respond OK: write tcp 127.0.0.1:61648: broken pipe
Apr 27 21:14:56.262 - flashlight.client: handler.go:102 Unable to respond OK: write tcp 127.0.0.1:61739: broken pipe
Apr 27 21:14:56.721 - flashlight.client: handler.go:102 Unable to respond OK: write tcp 127.0.0.1:61807: broken pipe
Apr 27 21:14:57.042 - flashlight.client: handler.go:102 Unable to respond OK: write tcp 127.0.0.1:61831: broken pipe
Apr 27 21:14:57.846 - flashlight.client: handler.go:102 Unable to respond OK: write tcp 127.0.0.1:61865: protocol wrong type for socket
Apr 27 21:14:58.003 - flashlight.client: handler.go:102 Unable to respond OK: write tcp 127.0.0.1:61887: broken pipe
Apr 27 21:14:58.384 - flashlight.client: handler.go:102 Unable to respond OK: write tcp 127.0.0.1:61896: broken pipe
Apr 27 21:15:26.995 - flashlight.client: handler.go:102 Unable to respond OK: write tcp 127.0.0.1:62089: broken pipe

**Comment by uaalto** [comment] 2015-07-19 11:03
Appear related to this issue: https://github.com/getlantern/lantern/issues/2721
Better log now, we have the line of code: 
`flashlight.client: handler.go:116`

**Comment by uaalto** [comment] 2015-07-19 11:29
xiam's log also shows a line number, probably the same after some edits.

**Comment by uaalto** [comment] 2015-07-19 12:05
_An existing connection was forcibly closed by the remote host._ is Windows parlance for _broken pipe_.

**Comment by uaalto** [comment] 2015-07-23 11:44
Should be fixed by https://github.com/getlantern/lantern/pull/2794

**Comment by xiam** [comment] 2015-08-08 00:31
I'm still having some logs on 2.0.0:

```
{"extra":{"country":"IR","language":"en","logLevel":"ERROR","osArch":"386","osName":"windows","osVersion":"","timeZone":"IRDT","version":"2.0.0+stable (20150807.013721)"},"fullMessage":"ERROR flashlight.client: handler.go:96 Unable to respond OK: WSASend tcp 127.0.0.1:8787: An existing connection was forcibly closed by the remote host.\n","hostname":"hidden","instanceid":"00ff19b2e840","locationInfo":"ERROR flashlight.client","message":"WSASend tcp 127.0.0.1:8787: An existing connection was forcibly closed by the remote host.","timestamp":1438992472653}
```

**Comment by uaalto** [comment] 2015-08-11 10:36
Could this be that the browser timeouts this connection because of https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/flashlight/client/handler.go#L78?

Here we are just sending a 200 OK response with HTTP 1.1. That's all. If the browser supports the CONNECT verb correctly, is going to expect this response and then send the request to be tunneled. I've been testing this repeatedly with `curl`.

Maybe we could also add a way log also the browser/user agent?

**Comment by uaalto** [comment] 2015-08-11 10:50
I've done a quick test and could reproduce it on OSX (the _broken pipe_ version, which is just the same thing). Adding an artificial sleep before the respondOk call to allow the client program to timeout while waiting for this response.

Another way to trigger it would be aborting just before Lantern had the chance to send its response (simply closing the tab in case of a browser could trigger this).

I can think of different solutions:

* Ignore the error, because it just signals that the browser isn't accepting our response. It could be for many reasons out of our control.
* Set a more strict timeout in our dialer. This could end up in unnecessarily failed connections if the network is slow. I don't think we should tune the timeouts for this reason.
* Depending on the browser, we might be able to set timeouts accordingly. But my previous argument remains.

**Comment by uaalto** [comment] 2015-08-12 09:21
We could also respond 200OK sooner, ie if the balancer doesn't successfully dial in a given time, just respond 200OK and just let the balancer take over the connection as soon as is ready. The worst that could happen (all available dialers in the balancer timing out) wouldn't be any different from just losing the connection because we didn't respond 200OK in time. And we would be better off anyway, because the balancer could eventually succeed and continue.

**Comment by myleshorton** [comment] 2015-08-12 21:39
Yeah I like the idea of just preemptively responding OK. I was going to add
that we could also just time how long the method itself takes before
responding OK and add that to the error log, but that would also break the
Loggly log consolidation without us added some extra logic there.

So I vote for just preemptively responding OK, although I agree there are
cases outside of our control like the user closing the browser.

**Comment by uaalto** [comment] 2015-08-12 22:27
Perfect! Logging that sounds interesting too. If we just append the time it took to respond OK, we could append that to the error message string as extra information. Do you think that could help?

**Comment by myleshorton** [comment] 2015-08-13 13:26
Yeah I'm just worried about creating too many custom parsing rules for the loggly side. Maybe we just use a convention though? Something like $FIELD:VALUE$ would always just remove that from the log message and would make it a new field sent to loggly?

**Comment by uaalto** [comment] 2015-08-13 15:31
I see. Why do we need to send it as a new field? Wouldn't just appending the string to the error message help too? I don't know much about Loggly, but is it because it helps categorizing better if you add this as an extra field?

**Closed** 2015-08-17 18:32 UTC
