### ISSUE TITLE
Lantern UI can show "Waiting for Lantern" on launch indefinitely

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2799] opened 2015-07-23 03:03 UTC
I was seeing this on our Windows VPS. You want to take a peek @atavism? I launched from the Start menu.

**Comment by atavism** [comment] 2015-07-23 08:39
@myleshorton Sure. I haven't been able to reproduce this though. Does it happen only occasionally or under specific circumstances?

**Comment by myleshorton** [comment] 2015-07-23 13:52
It's happened to me a couple of times now. In that last case, I know I had other existing Lantern tabs open before opening Lantern. If I switched tabs and refreshed, all of them would refresh, but without some sort of trigger like that the frontend seemed to never be able to find Lantern. I'll keep an eye out for it too and will try opening the dev console to see if I can find out more.

**Comment by atavism** [comment] 2015-07-23 21:54
Yeah, I'm able to reproduce this now, and it seems to only happen, as you said, when existing Lantern tabs were already open. I wonder if something introduced [here](https://github.com/getlantern/lantern/pull/2794/files) is partially responsible. I'll keep investigating.

**Comment by uaalto** [comment] 2015-07-24 07:42
As I was reading about issue I also thought it could be related. The changes introduced in the Go part shouldn't affect at all, because they just should improve correctness slightly, but not produce any change in behavior. Then the part of the UI, which could be responsible, its new functionality should be triggered only if the user leaves the lantern web page.

**Comment by myleshorton** [comment] 2015-07-25 03:35
The other interesting aspect of this is that @uaalto's changes did not get in to any of the released betas yet @atavism. There may be multiple issues, but it does happen without those changes for sure.

**Comment by myleshorton** [comment] 2015-08-04 20:08
This is still happening quite a bit for me guys. Have either of you had a chance to look at it more @atavism or @uaalto? Seems like a pretty big issue right now.

**Comment by myleshorton** [comment] 2015-08-04 20:09
I'm actually going to move this to 2.0.0, as it's currently happening for me on about every other run.

**Comment by uaalto** [comment] 2015-08-04 20:33
I couldn't check it out, @myleshorton. But I can now that I have some progress on the Firetweet thing and a few other things in the queue for feedback.
One question, have you tried waiting a little bit? Does it finally connect in a minute or even less if you wait long enough? I have a couple of ideas that would be related to this.
It would be important to open access to config from where I am now (more details in email about Firetweet issue).

**Comment by myleshorton** [comment] 2015-08-04 20:47
That would be great. It does usually open eventually - maybe even always,
but it sometimes hangs for a good 20 seconds.

**Comment by fffw** [comment] 2015-08-05 07:02
I can't reproduce it from either my Windows VM or VPS. All tabs showed the notice when Lantern stoped, and refreshed when Lantern started again. The only thing I noticed is that IE11 on the VPS couldn't show Lantern page correctly. It shows well on IE10 on my VM, so I guess it's caused by the OS version on VPS, Windows Server 2012.

**Comment by uaalto** [comment] 2015-08-05 07:04
This is not a Windows related issue, or even browser-related. And it is very probably related to the websockets, from what I'm seeing in my tests.

**Comment by uaalto** [comment] 2015-08-05 10:00
This one is proving tough. I believe that the Go part is doing is job fine: using `nc` I can establish a manual websockets connection to the websockets server even if the web UI didn't connect and still shows the "waiting for Lantern" message:

```
nc 127.0.0.1 16823

GET /data HTTP/1.1
Host: 127.0.0.1:16823
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:39.0) Gecko/20100101 Firefox/39.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Sec-WebSocket-Version: 13
Origin: http://127.0.0.1:16823
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: AAy8VszSrZxmL/mOrIKJQw==
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
```

Returns the expected websocket data.

**Comment by uaalto** [comment] 2015-08-05 10:29
It actually might be the Go server. After testing it with Thor, I consistently get the errors below, and always the process gets stuck after ~100 connections for a while, in a manner resembling what happens to the browser.
I also discovered that if you close all tabs you restart the behavior.

```
Thor:                                                  version: 1.0.0

God of Thunder, son of Odin and smasher of WebSockets!

Thou shall:
- Spawn 4 workers.
- Create all the concurrent/parallel connections.
- Smash 500 connections with the mighty Mjölnir.

The answers you seek shall be yours, once I claim what is mine.

Connecting to ws://127.0.0.1:16823/data

  Opened 100 connections
  Opened 200 connections


Online               246739 milliseconds
Time taken           246739 milliseconds
Connected            234
Disconnected         0
Failed               407
Total transferred    334.41kB
Total received       25.74MB

Durations (ms):

                     min     mean     stddev  median max
Handshaking          109     56071     60284     401 121739
Latency              0       1             2       1 15

Percentile (ms):

                      50%     66%     75%     80%     90%     95%     98%     98%    100%
Handshaking          401     121506  121563  121602  121666  121697  121721  121725  121739
Latency              1       1       1       2       3       4       5       11      15

Received errors:

141x                 not opened
266x                 socket hang up
```

**Comment by uaalto** [comment] 2015-08-05 11:17
I solved the issue that caused the Thor errors: an improperly closed Websocket connection. Now it doesn't result in that faulty behavior where it can't connect to the websockets server after a few connections. But this darn bug remains!!

**Comment by myleshorton** [comment] 2015-08-05 13:19
Oh good investigating @uaalto! Does the browser dev console tell you anything useful? One trick is to open a separate browser with the dev console open, and just hit lantern at 127...

**Comment by uaalto** [comment] 2015-08-05 14:21
I keep getting
```
> var fd = new WebSocket("ws://127.0.0.1:16823/data");
GET http://127.0.0.1:16823/data [HTTP/1.1 403 Forbidden 3ms]
Firefox can't establish a connection to the server at ws://127.0.0.1:16823/data.
```
it's due to the origin restriction:

```
Aug 05 14:19:10.756 - 1m38s ERROR flashlight.ui: ws.go:58 Unable to upgrade /data to websocket: websocket: origin not allowed
```

How do you normally do it?

I'm able to connect with raw `nc` though, after just copying the http/websockets headers I got from wireshark.

**Comment by uaalto** [comment] 2015-08-05 14:31
I have a new theory of this thing. Is not nice, and I'm not fully satisfied, but this is what I got after the investigation:

This problem happens on Windows and OSX (haven't tried on Linux). It happens with Firefox. But **it doesn't happen** with Chrome or IE. At least I couldn't reproduce it after a gazillion times. If it gets reproduced just once, the theory doesn't work.

I think what we are suffering is a variation of:
https://bugzilla.mozilla.org/show_bug.cgi?id=765738
https://bugzilla.mozilla.org/show_bug.cgi?id=983243

I think so because 1) the behavior resembles so much the closing issue detected by Thor and 2) because I can't reproduce the bug with the other browsers, but I can do it consistently with Firefox. 
These are closed bugs, but they are precedents of the error.

**Comment by uaalto** [comment] 2015-08-05 14:35
Ok, this works:
```
var fd = new WebSocket("ws://127.0.0.1:16823/data", "http://127.0.0.1:16823");
```

**Comment by uaalto** [comment] 2015-08-05 14:41
By the way, I tried forcing closure of all websockets connection at Lantern exit, but that doesn't work either. This means the server makes sure of not leaving connections opened, so now it should be the browser the one leaving leftovers.

**Comment by myleshorton** [comment] 2015-08-05 15:25
Cool. I can confirm I saw it with FireFox only as far as I can recall. Does
the above fix it?

**Comment by uaalto** [comment] 2015-08-05 21:49
No, I didn't figure out the fix. I did fix the issue that looked so much like what we needed, but it doesn't work. I'm a bit lost at the moment. I have an idea of a workaround, but I'm not very confident on it.
At the moment, I really think this is a problem of Firefox, because the connections are working well at the Go websockets ui server, as shown by the test tools, and the other browsers. There is no reason why Firefox shouldn't connect, and everything else does connect. It is a problem that builds up as long as you keep piling up open tabs with lantern, otherwise it shouldn't happen.

**Comment by myleshorton** [comment] 2015-08-05 21:51
Cool. Does FireBug or anything on the browser side offer any clues?

**Comment by uaalto** [comment] 2015-08-05 21:59
I didn't manage to use the browser itself for inspection: I keep getting origin errors on the backend side (that could be removed for testing I believe). But `nc` shows that the connection on the backend is working well, since I can set the origin manually there after sniffing the websocket messages the browser itself sends. An important point is that every time the page on Firefox waits for connections, Chrome connects with no issue, and `nc` also gets a response instantly.

**Comment by uaalto** [comment] 2015-08-05 22:02
The network inspectors in chrome or firefox don't offer any clue because they just don't see any connection happening. They are unaware of what's going on.

**Comment by myleshorton** [comment] 2015-08-05 22:07
That in and of itself seems weird @uaalto. Do they see the connection when the bug doesn't occur?

**Comment by uaalto** [comment] 2015-08-05 22:14
The browser network inspector in Firefox (the only one failing, to be precise), doesn't show any connection until if succeeds to connect, just at the same time you see the page load properly as if everything went ok. The very weird thing is that Firefox "blocks" on those connections, and the blocking time is loosely proportional to the number of previously opened tabs, but the rest of tools (nc and Chrome) don't block at all and succeed happily. Safari just opens the same tab and works well too.

**Comment by myleshorton** [comment] 2015-08-05 22:17
Could we be hitting up against some per-domain/simultaneous connection issue? I wonder if bumping those up in about:config (search for connections) would make the problem go away, not as a solution but as a test. Then again I've seen it with just one tab open *I think*

**Comment by uaalto** [comment] 2015-08-05 22:26
_per-domain/simultaneous connection issue_: I looked for info on this but didn't succeed. I can try again this path.
You might have seen the one tab problem if it happened _after_ having many tabs opened and _if_ you didn't close _all_ of them. This is also what leads me to believe that something evil is going on _within_ Firefox.
Anyway, I should clear my mind a bit, because I'm fixating a lot on the idea of Firefox being the cause I don't want the other options to be discarded entirely.

**Comment by uaalto** [comment] 2015-08-05 22:30
more specifically: _per-domain_ issue is what I searched and didn't find much, also led by the belief that it doesn't seem very reasonable, so I should insist.
_simultaneous connection_ issue has been the bulk of my investigation, that's why I used Thor.

**Comment by uaalto** [comment] 2015-08-06 10:45
I thought this commit fixed it, but I didn't realize that I was also making the old tabs unable to connect. The new tab would always connect instantly this way, but at the cost of the rest of the tabs.
The problem seems to be that Firefox keeps the connections in a state that blocks itself from making new connections to the same websocket server. It cleans up the state after you close *all* connections (i.e. close all lantern tabs), and sometimes when you wait long enough to spawn Lantern again. This is Firefox's fault in my opinion, probably the result of some optimization.

**Comment by uaalto** [comment] 2015-08-06 11:13
This last commit seems to produce a better behavior. You shouldn't wait more than the refresh interval (5000ms ATM).
The concept is to make sure that we force closure of connections that failed to connect in 100ms, which avoids all those new connections piling up in each call to reconnect once we have a tab that is disconnected. That probably is be the source of the problem, which Chrome manages well, but Firefox doesn't.

It needs more testing though.

**Comment by uaalto** [comment] 2015-08-06 11:27
This change improves user experience, but there are still a few cases where it doesn't connect. Restarting flashlight after that gets it working, which previously didn't work. This is some progress.
All this is a workaround, though. So if we want to, we can just test that connection was done properly and just reload the page otherwise. I tested the idea and works, but some of the previously opened tabs end up displaying an error page.
We have also to consider that I'm doing all tests with 10 to 50 lantern tabs open, so this workaround would work for normal usage, I think.

**Comment by uaalto** [comment] 2015-08-06 11:34
I've committed this workaround idea, which produces some interesting results.
https://github.com/getlantern/lantern/tree/issue-2799

It is not perfect, but we could apply it only to firefox, so the rest of browsers work perfect and Firefox gets a better user experience.

Please try and let me know what you think. You should just set Firefox as the default browser, open lantern and close it around 20-30 times at least, without closing the tabs. This way you can get the feeling of what happens.

**Comment by uaalto** [comment] 2015-08-06 13:38
New set of tests. Still not there, and this looks more and more like a bug in Firefox.

**Comment by uaalto** [comment] 2015-08-06 14:25
This is the summary, @myleshorton:
This is already tested from many angles and possibilities. My conclusion is that Firefox doesn't handle multiple connections to the same websocket, at least on localhost. It doesn't matter how I force closing it.
The only way I found to avoid 100% this issue is to not try to reconnect automatically. My workaround seems to somewhat improve the situation, but not entirely overcome it.

**Comment by sheena3** [comment] 2015-08-06 17:57
@myleshorton @uaalto - I was able to reproduce this issue only in FF with previous 2.0.0 by installing Lantern while it is already running. I couldn't find any other ways to reproduce it.

After installing 2.0.0+stable, it is working fine in FF too. 

Are there any other possible scenarios in which Lantern waits indefinitely?

**Comment by uaalto** [comment] 2015-08-06 21:24
@myleshorton @sheena3 My current understanding of this issue is that is going to happen under some stress conditions (opening many tabs with lantern), but it is a bug in Firefox, or at least a limitation. I think websockets might not be well tested for the case where the same connection is established through different tabs.

**Comment by sheena3** [comment] 2015-08-07 17:07
Thanks @uaalto is it Lantern running in all the tabs or just some random websites with Lantern running in one of the tabs? I will see if I can reproduce this scenario.

**Comment by myleshorton** [comment] 2015-08-07 19:24
OK I'm moving this to 2.0.1, but I generally like the idea of working around it by just not doing the websocket reconnection stuff on FF.

**Comment by uaalto** [comment] 2015-08-07 23:56
@sheena3 they must be all lantern tabs. It's probably a corner case, but happens often while in development.

@myleshorton I've also investigated the option of just reopening within the same tab. Safari does this automatically. I couldn't find a reasonable and cross-browser way of doing this, though. I think also the last option you mention is best at the moment.

**Comment by uaalto** [comment] 2015-08-10 11:04
@myleshorton @sheena3 I confirmed this is a bug in Firefox. I managed to reproduce it with a small test case. I filed a bug on Bugzilla for Firefox [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1192773).

For now, we will avoid websocket reconnection for FF and keep tuned to the issue's progress.

**Comment by xiam** [comment] 2015-08-11 23:25
@myleshorton, @uaalto 

I tried to replicate this error without success using 2.0.0-beta and Firefox on Windows, do you have a consistent step-by-step way of reproducing it?

**Comment by xiam** [comment] 2015-08-11 23:32
I'm going to try with the [documented issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1192773) opened by @uaalto

**Comment by xiam** [comment] 2015-08-11 23:37
Nevermind, I've got it now after 15 tabs.

**Closed** 2015-08-13 15:32 UTC
Labels: P1
