### ISSUE TITLE
System tray menu options missing

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2369] opened 2015-04-09 02:49 UTC
With the latest beta release, when I click on the lantern icon in Ubuntu, I'm not seeing any menu options:

![image](https://cloud.githubusercontent.com/assets/6346213/7059592/65315fc2-de41-11e4-90a9-9c4916193d77.png)

**Comment by atavism** [comment] 2015-04-09 16:28
Actually, this is happening on Windows too.

**Comment by aranhoide** [comment] 2015-04-09 16:47
This will happen iff you don't have a VERSION environment variable set when building.

The `prod` build tag will not be set in that case.  I think @xiam is aware of the details on this and IIRC he has it fixed in some branch (?).  In the meanwhile, a workaround is setting VERSION when building.

Note also that while the text is not displayed the menu entries still work (not that this makes it less of a bug).

**Comment by xiam** [comment] 2015-04-09 16:57
I thought the meaning for `prod` was production, and if that's the case this should be working with and without `prod`. I guess this is caused by translations not being included in a non-prod release. Do you know what would be the easier way to include English in prod and non-prod builds?

**Comment by sheena3** [comment] 2015-04-09 17:00
May I know in which version this is happening? Because I used windows 7 as well as windows 8.1 while testing and it worked fine. Even I downloaded the latest beta from github and it is showing me the menu options.

**Comment by aranhoide** [comment] 2015-04-09 17:02
@sheena3 I don't think this is happening in any version we have deployed, only in developer builds we don't publish.

**Comment by aranhoide** [comment] 2015-04-09 17:05
@xiam does it hurt much to include all translations just like in `prod`?  In general I'd rather have as little difference as possible between production and debug builds (e.g., logging levels).

**Comment by xiam** [comment] 2015-04-09 17:17
I don't think it would hurt at all, but probably we should not just make all releases `prod` releases, it would make auto-updates interfere with our development for instance.

Besides auto-updates I located other two files using `prod`:

```
./src/github.com/getlantern/flashlight/ui/resources.go:// +build prod
./src/github.com/getlantern/flashlight/ui/resources_stub.go:// +build !prod
```

Do you know if the make any difference? If not we could either remove them or update `resources.go`, I think that's the origin of our issue.

**Comment by xiam** [comment] 2015-04-09 17:18
Sorry @aranhoide, you were referring to translations only. Yes I'd agree on including translations.

**Comment by aranhoide** [comment] 2015-04-09 17:24
Yeah, removing that `// +build prod` from places such as UI resources so those get included in development builds too sounds like a good idea.

*In the case of UI resources* an even better idea might be to remove them from headless builds, so instead of removing the `// +build prod` altogether I think we should replace them with `// +build !headless` (that is, put a `!` in headless where prod used to have none, and vice versa).

**Comment by xiam** [comment] 2015-04-09 18:43
Good idea, since I've been working on our build process and this is somewhat related I'll take this one too.

**Comment by myleshorton** [comment] 2015-04-09 18:48
I don't believe it's happening in any production version @sheena3

**Comment by atavism** [comment] 2015-04-09 21:01
Ok, setting the VERSION environment variable resolved it. BTW, if I want to re-generate the UI assets directory, I need to run ``UPDATE_DIST=true make docker-genassets`` -- maybe we just always do that when we ``make``? ``make clean`` could delete the directory too.

**Closed** 2015-04-10 15:59 UTC
Labels: P1
