### ISSUE TITLE
Stopped dialer is still working

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#4705] opened 2016-06-15 12:14 UTC
Should be replaced by new ones. It should be the reason why https://github.com/getlantern/lantern/pull/4634 failed CI.

```
Jun 15 10:41:04.413 - 0m4s DEBUG flashlight.client: balancer.go:40 Adding chained server: <masked>:443
Jun 15 10:41:04.413 - 0m4s DEBUG flashlight: flashlight.go:112 Applied updated configuration
Jun 15 10:41:04.413 - 0m4s DEBUG flashlight.client: balancer.go:59 Closed old balancer
Jun 15 10:41:04.413 - 0m4s TRACE balancer: dialer.go:77 Dialer (trusted) chained proxy at 45.55.184.76:443 [] stopped
Jun 15 10:41:30.594 - 0m30s DEBUG flashlight.client: chained.go:175 Error testing dialer 45.55.184.76:443 to http://www.google.com:80/index.html: Unable to dial server (trusted) chained proxy at 45.55.184.76:443 []: dial tcp 45.55.184.76:443: i/o timeout
...
Jun 15 10:42:00.598 - 1m0s TRACE balancer: dialer.go:153 Dialer (trusted) chained proxy at 45.55.184.76:443 [] consecutive failures: 4 -> 5 [detour=false op=proxied_dialer root_op=proxied_dialer]
```

**Comment by fffw** [comment] 2016-06-15 12:34
The sequence is:
1. Dialing through old balancer with no accessible proxy server(say if the previously assigned proxies are retired).
2. New configuration is fetched.
3. Old balancer is closed and new one starts working.
4. Old balancer's `Dial` is still working, desperately dialing same proxy `dialAttempts` times, then fail.

We need to avoid 4. So we should never close balancer. Instead, reinitialize it with new set of dialers, and having `Dial` pick dialers currently dialers instead of cached copy.

**Comment by myleshorton** [comment] 2016-06-15 15:21
This is interesting @fffw. Do you think this is causing issues from the user's perspective?

**Comment by fffw** [comment] 2016-06-16 01:20
Yeah, I think so @myleshorton . The initial pages won't open even with new proxy servers swapped in, until user refreshes the page manually. Chrome mitigates the pain by refreshing automatically when user clicks a previously failed tab.

**Comment by oxtoacart** [comment] 2016-06-16 11:32
@fffw The reason CI is failing is because of this - https://github.com/getlantern/lantern_aws/issues/209

**Comment by fffw** [comment] 2016-06-16 13:24
Yes, but if client can use the newly assigned proxy to redial, CI can pass even with broken fallbacks

**Comment by oxtoacart** [comment] 2016-06-16 13:27
@fffw Are you sure there's a problem here?  I put a 5 second sleep in the lantern_test.go before trying to proxy the request, and it worked.  I think it was just a race condition between when we got the updated config and when we tried to proxy.

**Comment by oxtoacart** [comment] 2016-06-16 13:29
@fffw Oh, I see what you're saying now.  You would like the new configuration to apply to existing Dial() calls.  I think that would be neat, but I don't think that's worth worrying about right now.  In particular, the existing Dial() call may finish retrying and give up before we get a new configuration, it's all just a question of timing.

**Comment by fffw** [comment] 2016-06-16 16:21
@oxtoacart It's probably more important than we thought consider the following facts.

1. With dual fetcher, the new config can be available at around 3s usually.
2. Current `chainedTimeout` is 30s (probably too large). Consider those extremely slow network, we can't reduce it to less than 10s. So it will take at least 30s for `bal.Dial` to fail because it will try 3 times. But if we always use up-to-date dialers, the connection can be made after 10s (if `chainedTimeout` is reduced 10s). BTW `obfs4DialFactory` doesn't specify a timeout.
3. There can be lots of applications accessing network during computer startup. Users are also highly likely to open pages immediately after launching Lantern. If Lantern has not being used for a couple of days, or if the censor blocks proxies very often, those applications or pages can fail.

It raises another more important change: We should not make Lantern available until at least one dialer is successfully checked. Not setting system proxy, not hide the spinner, etc., before it can actually work. That would solve many existing browser issues.

I agree they can be postponed in current sprint.

**Comment by oxtoacart** [comment] 2016-06-16 16:24
@fffw I really like the idea of not setting Lantern as the system proxy until we've made at least one successful connection.

**Comment by oxtoacart** [comment] 2016-06-16 16:27
Oh, regarding obfs4dialfactory - the new netx.Dial has a built-in timeout of 30 seconds.

**Comment by myleshorton** [comment] 2016-06-16 17:47
Yeah definitely not setting the system proxy until a successful dial is the way to go I agree, and I also agree we should probably hold off on this one until we get this version out!

**Comment by myleshorton** [comment] 2016-06-20 18:41
Yeah I'm seeing this in action right now @fffw, and it's definitely making me think it's a pretty big issue. For me my old dialer keeps dialing and failing for several minutes without ever trying a new server from the config-server.

**Comment by myleshorton** [comment] 2016-06-20 18:44
For me it also tries to redial 282 times in the first 3 minutes of running @fffw and @oxtoacart. Not totally crazy, but that's a lot considering it's failing every time.

**Comment by atavism** [comment] 2016-06-20 18:44
Yeah, same here, @myleshorton.

**Comment by myleshorton** [comment] 2016-06-20 18:45
I think to reproduce this you basically just need to run with bad bootstrap fallbacks.

**Comment by myleshorton** [comment] 2016-06-20 18:45
but blocked bootstrap fallbacks might cause it too...interesting @todd

**Comment by myleshorton** [comment] 2016-06-20 18:46
The biggest issue for me is that it seems to never even try the new proxy, even leaving aside the issue of continuing to try failing ones for a moment.

**Comment by myleshorton** [comment] 2016-06-20 18:47
As in, the new configuration doesn't seem to apply to _new_ dial calls in this case @oxtoacart.

**Comment by oxtoacart** [comment] 2016-06-20 18:48
@myleshorton Wait, you mean that your client never successfully connects to the new proxy?

**Comment by myleshorton** [comment] 2016-06-20 18:50
exactly @oxtoacart

**Comment by oxtoacart** [comment] 2016-06-20 18:52
@myleshorton You're seeing this in lantern-pro?

**Comment by myleshorton** [comment] 2016-06-20 18:53
Yeah, come to think of it @oxtoacart I think the reason I started hitting up against this so hard is that I started completely deleting my lantern config folder a bunch to fully reset stuff -- so there's no cached config on disk.

**Comment by myleshorton** [comment] 2016-06-20 18:55
Yeah -- this is really bad, especially for new users. I'm adding this to TO-DO.

**Comment by oxtoacart** [comment] 2016-06-20 19:07
@myleshorton I'm not seeing this.  I checked out [this commit](https://github.com/getlantern/lantern/commit/e9defbdbc7f52e882763b21dee4f50b78b2a1f5d) from before when I fixed the baked-in fallbacks.  I then deleted my local Lantern folder and started Lantern. I then immediately tried accessing whatismyipaddress.com from Chrome, which hung.  I saw a log message adding the bad baked in fallback, then a little later I saw a log message about adding the good fallback from the config server.  I tried reloading whatismyipaddress.com and it successfully showed my ip ad being in New York.

**Comment by myleshorton** [comment] 2016-06-20 19:09
Netx isn't in Lantern Pro yet right?

**Comment by oxtoacart** [comment] 2016-06-20 19:10
BTW, that behavior is consistent with what I saw in the lantern test failure.  When I added a time.Sleep(), it allowed the test to pick up the new config and succeed.

**Comment by oxtoacart** [comment] 2016-06-20 19:11
@myleshorton I don't know, when was the last time we merged from devel to pro?

**Comment by oxtoacart** [comment] 2016-06-20 19:23
@myleshorton This doesn't appear to be a problem with the configuration getting applied.  When I see this fail on the pro branch, I never get an updated configuration from the config server, and instead just the message `Config unchanged in cloud`.

**Comment by oxtoacart** [comment] 2016-06-20 19:26
Oh wait, before that I do see `Fetched cloud config`.

**Comment by oxtoacart** [comment] 2016-06-20 19:30
Interesting, it eventually worked, however 3 minutes elapsed between the message showing that we fetched a new cloud config and configured the proxy.

```
Jun 20 19:19:24.712 - 0m5s DEBUG flashlight.config: fetcher.go:219 Fetched cloud config [op=fetch_config root_op=fetch_config]
Jun 20 19:19:28.193 - 0m9s DEBUG flashlight: flashlight.go:108 Applying updated configuration
Jun 20 19:22:25.748 - 3m6s DEBUG flashlight.client: balancer.go:40 Adding chained server: xxx.xxx.xx.xxx
```

**Comment by myleshorton** [comment] 2016-06-20 21:21
So it turns out that latest issue was different but related to this ticket @fffw -- handled it separately though and keeping this one open.

**Comment by myleshorton** [comment] 2016-06-24 03:37
This does definitely continue to appear, however, most recently with the data cap where you don't get real cap data from an assigned proxy until well into your session. Looking at this logs we can see that it takes 20 seconds between getting a proxy from the config server and actually using that proxy. In practice that also means 20 seconds until we get data cap data.

```
Jun 24 03:23:25.081 - 0m4s DEBUG flashlight.config: fetcher.go:133 Got chained server: 104.131.82.167:443
Jun 24 03:23:25.997 - 0m5s DEBUG flashlight.client: balancer.go:40 Adding chained server: 104.131.82.167:443
Jun 24 03:23:46.206 - 0m25s DEBUG balancer: balancer.go:106 Dialing connect://play.google.com:443 with (trusted) chained proxy at 104.131.82.167:443 [] [detour=true op=proxied_dialer origin_host=play.google.com origin_port=443 root_op=proxy user_agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36]
```

**Comment by oxtoacart** [comment] 2016-06-24 03:43
Is that delay because we're continuing to dial new connections with the old dialer for 20 seconds, or is that delay because nothing tried to dial out for 20 seconds?

**Comment by fffw** [comment] 2016-06-24 03:44
I'm pretty close to get the fix out.

**Comment by fffw** [comment] 2016-06-24 10:46
@myleshorton can you try if it loads faster with https://github.com/getlantern/lantern/pull/4781?

**Comment by fffw** [comment] 2016-06-24 10:48
Oh the PR is not against lantern-pro, so you probably can't test the data cap thing without merging...

**Closed** 2016-07-05 16:02 UTC
Labels: P1
