### ISSUE TITLE
Web interface for customizing proxiedsites delta list, or an easy-to-use encrypted config editor

### ISSUE THREAD

**Issue by Artoria2e5** [getlantern/lantern#4970] opened 2016-07-09 15:26 UTC
getlantern/lantern-binaries#4 shows a case where some hand-editing in the delta list is required for functional operation without using global proxying. Since lantern 3.x, the config file is encrypted by default, making such hand-editing much harder. I hope that there can be a well-documented way to edit the specific config item easily.

**Comment by myleshorton** [comment] 2016-08-08 18:12
The hand editing I believe would just be overridden by global site updates @Artoria2e5, so would only last for about 24 hours. Are there specific sites you would like to see added?

**Comment by Artoria2e5** [comment] 2016-08-09 02:54
@myleshorton Nope, that's a very workspace-specific thing.

**Comment by p3rcya** [comment] 2016-08-09 02:57
We should allow users to edit blacklist https://github.com/getlantern/lantern/issues/5110

**Comment by myleshorton** [comment] 2016-08-09 05:55
I'm closing this as a duplicate of #2881. It's definitely on our radar though, @Artoria2e5, and is something we want to implement.

**Closed by myleshorton** 2016-08-09 05:55 UTC
