### ISSUE TITLE
We're sorry...

### ISSUE THREAD

**Issue by liushiwei** [getlantern/lantern#4817] opened 2016-06-28 06:17 UTC
We're sorry...

... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.

See Google Help for more information.

when i google something ,google show me this. why?

**Comment by p3rcya** [comment] 2016-06-28 06:33
Duplicate of https://github.com/getlantern/lantern/issues/4562

**Closed by p3rcya** 2016-06-28 06:33 UTC
