### ISSUE TITLE
Edge on Windows 10 can't open Lantern page through ui.lantern.io

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#4175] opened 2016-05-01 10:19 UTC
Seen from [devel forum](https://groups.google.com/forum/#!topic/lantern-devel/wldiALrygPM)

Browser tries to access `ui.lantern.io` directly, and gets DNS error page.
![](https://groups.google.com/group/lantern-devel/attach/1961206ae0d89/screen%20the%20page.jpg?part=0.1&authuser=0&view=1)

The requirement here is to make the Lantern UI work on Edge.  ui.lantern.io was the original approach, but if that can't be made to work reliably, maybe another approach is warranted.  Also, Edge is changing rapidly, so if we're lucky, the original restriction against visiting localhost is being removed.  Some research is in order before digging too deeply.

**Comment by oxtoacart** [comment] 2016-05-02 20:23
I'd estimate this at 2 story points.

**Comment by sunshine19090** [comment] 2016-05-02 21:02
@fffw Yeah I too saw this but I was able to directly access it using http://127.0.0.1:16823/ and that's why didnt ticket it. Is it necessary that we should only use ui.lantern.io?

**Comment by xiam** [comment] 2016-05-05 18:37
Hey @sunshine19090, could you help me checking this one?

**Comment by myleshorton** [comment] 2016-05-06 14:46
Do you think this is fixed as well @xiam?

**Comment by xiam** [comment] 2016-05-06 15:18
Yes, should be fixed too.

**Comment by sunshine19090** [comment] 2016-05-13 19:10
@xiam Sorry, closed this one by mistake. I still couldn't access http://ui.lantern.io in Edge, it takes me to the error page "Hmm, we can't reach this page".

**Comment by xiam** [comment] 2016-05-13 19:15
Bummer! thanks for testing @sunshine19090, could you send me a screencast privately?

**Comment by sunshine19090** [comment] 2016-05-13 19:30
@xiam, after a few more tries Lantern is now opening with ui.lantern.io. I think it got resolved after restarting both lantern and edge. Should I leave this open for you to analyse?

**Comment by xiam** [comment] 2016-05-13 19:33
It works for me, please reopen if you can find a way to reproduce the bug.
Thanks!

**Comment by sunshine19090** [comment] 2016-05-13 19:35
Yeah sure @xiam. Closing this now.

**Closed by sunshine19090** 2016-05-13 19:35 UTC
Labels: P2, QA
