### ISSUE TITLE
Typing an website address in the address bar of a Lantern browser returns to Lantern itself

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2721] opened 2015-07-12 17:52 UTC
I tried to open a website by typing it in the address bar in the Lantern browser. It just takes me back to http://127.0.0.1:16823/ . Is that how it is designed to work? I expected it to open the website that I wanted to visit.

**Comment by sheena3** [comment] 2015-07-12 17:54
This happens only in IE and FF.

**Comment by uaalto** [comment] 2015-07-14 08:14
What do you mean by _Lantern browser_? Do you mean that you cannot navigate to any site since the browser (IE and FF) will always redirect you to http://127.0.0.1:16823/?

**Comment by uaalto** [comment] 2015-07-14 08:15
Also, which version of Windows it is?

**Comment by sheena3** [comment] 2015-07-14 16:53
I mean the Lantern page http://127.0.0.1:16823/ and not the browser itself. I have so many tabs in the browser including the Lantern page. So, in the lantern page alone if I type any other address then it redirects me to http://127.0.0.1:16823/. In all the other tabs of the browser, it works fine.

**Comment by sheena3** [comment] 2015-07-14 16:55
I am using windows 8.1. IE 11 and FF 39.0

**Comment by uaalto** [comment] 2015-07-14 17:45
Thank you @sheena3, I'm going to try and reproduce it.

**Comment by uaalto** [comment] 2015-07-14 19:16
I can't reproduce this one. I've tried with Windows 8.1 and IE 11/FF 39.
One question, are you using a VM for testing this changes or your normal daily-use environment?

**Comment by uaalto** [comment] 2015-07-14 20:04
Windows weirdness... My test system updated and then I could reproduce the issue. But now, after I installed this one:
https://github.com/getlantern/lantern/issues/2719
I'm not able to reproduce it anymore. I'm wary of calling it a fix for this issue, but could you please check if you still get this behavior?

**Comment by sheena3** [comment] 2015-07-15 17:58
@uaalto yes, I too couldn't reproduce this in IE 11 now but FF remains the same. And I am not using VM for windows 8.1.

**Comment by uaalto** [comment] 2015-07-16 08:23
Thanks @sheena3. This is a weird error.
I indeed could reproduce it once more in FF, but now I can't after +5 tries. This error doesn't sound like something that the browser could be caching, but still it might be just gone after https://github.com/getlantern/lantern/issues/2719. In any case, I think it is related to this one: https://github.com/getlantern/lantern/issues/2741, because I got that error (exactly once) while playing with this one.
But still the question remains, why would Lantern redirect to localhost:lantern-port then?

**Comment by uaalto** [comment] 2015-07-16 08:34
Oh, one bit of interesting information: when this happened, if I tried again it then worked. Could you try this one @sheena3? Thanks a lot for your help by the way. These sort of errors are a nightmare to debug.
Anyone else tried this one?

**Comment by uaalto** [comment] 2015-07-16 13:18
One more data point: I could reproduce it once on Linux (Ubuntu) with Firefox. I think all these errors are manifestations of the same root cause, and probably a synchronization issue of some sort:

https://github.com/getlantern/lantern/issues/2719
https://github.com/getlantern/lantern/issues/2741
https://github.com/getlantern/lantern/issues/2721

**Comment by myleshorton** [comment] 2015-07-17 22:02
I'm unable to reproduce this one unfortunately guys. @sheena3 if you're still consistently able to make this happen, would you mind sending a screencast? I'm just wondering if I'm doing something slightly differently.

**Comment by uaalto** [comment] 2015-07-18 19:03
I was able to reproduce this one now many times in a row. This is logged once every time you attempt to go to an URL within the Lantern home tab:
```
Jul 18 18:51:35.129 - 0m21s ERROR flashlight.client: handler.go:116 Unable to respond OK: WSASend tcp     127.0.0.1:8787: An established connection was aborted by the software in your host machine.
```

This error comes out of Windows. The underlying error code is WSAECONNABORTED.

**Comment by uaalto** [comment] 2015-07-19 12:19
See https://github.com/getlantern/lantern/issues/2429 for progress on this last error. While on the path for this hunt, I believe is not a symptom but not the root cause.

**Comment by uaalto** [comment] 2015-07-19 12:51
This error seems to be recurrent when this happens:
```Jul 19 12:49:55.801 - 0m53s DEBUG flashlight.ui: ws.go:125 Error writing to UI websocket: close sent for: http:/127.0.0.1:16823/data```

Now the previous error has disappeared with https://github.com/getlantern/lantern/pull/2769

**Comment by uaalto** [comment] 2015-07-20 10:22
Working on this branch: https://github.com/getlantern/lantern/tree/issue-2721

**Comment by uaalto** [comment] 2015-07-20 10:45
There seems to be two different situations in which this happens. One of them produces this other error:
```
Jul 20 10:44:30.459 - 1m11s DEBUG flashlight.client: handler.go:118 Error piping data from client to proxy:
```
This is produced by coded I added in order to capture errors at that point.

**Comment by uaalto** [comment] 2015-07-20 10:56
I'm making some progress, but still unable to isolate it completely. I have a strong suspicion that Websockets are the cause.
```
Jul 20 10:54:58.656 - 0m17s ERROR flashlight.client: handler.go:107 Unable to respond OK: WSASend tcp 
```

**Comment by uaalto** [comment] 2015-07-20 10:58
Full chain of events:
```
Jul 20 10:54:55.672 - 0m14s DEBUG flashlight.ui: ws.go:129 Error writing to UI "websocket: close sent" for: http:/127.0.0.1:16823/data

Jul 20 10:54:58.656 - 0m17s ERROR flashlight.client: handler.go:107 Unable to respond OK: WSASend tcp 127.0.0.1:8787: An established connection was aborted by the software in your host machine.

Jul 20 10:55:05.674 - 0m24s DEBUG flashlight.ui: ws.go:129 Error writing to UI "websocket: close sent" for: http:/127.0.0.1:16823/data
```

**Comment by uaalto** [comment] 2015-07-20 11:03
So, more than the Websockets being the cause, they are always interacting with the issue. The problem seems to be that something causes the browser to cut off connection with the proxy, but besides the Websocket connections being there always when this happens, I have no conclusion on the root cause.

**Comment by uaalto** [comment] 2015-07-20 11:18
IE is not producing this behavior anymore, but it produces also this log lines:

```
handler.go:125 Error piping data from proxy to client: WSASend tcp 127.0.0.1:8787: An existing connection was forcibly closed by the remote host.
Jul 20 11:14:15.333 - 0m18s DEBUG flashlight.client: handler.go:125 Error piping data from proxy to client: WSASend tcp 127.0.0.1:8787: An existing connection was forcibly closed by the remote host.

handler.go:118 Error piping data from client to proxy: WSARecv tcp 127.0.0.1:8787: An existing connection was forcibly closed by the remote host.
```

**Comment by uaalto** [comment] 2015-07-20 11:41
I'm pretty confident at this point that the issue is caused by the browser forcibly closing the connection, which happens only with WebSockets present. Something in WS side is not being handled well, or maybe the websockets implementations Lantern depends on is broken.

**Comment by uaalto** [comment] 2015-07-20 11:48
Nah, websockets implementation is not the issue. :(

The WSASend/WSARecv are the only clues at the moment...

**Comment by myleshorton** [comment] 2015-07-21 13:09
Wow so this isn't actually related to websockets @uaalto? I was going to say we could have the backend explicitly send a closing signal over the websocket channel on any close signal, but that won't solve it if it's not the problem!

**Comment by uaalto** [comment] 2015-07-21 13:59
Scratch all that. I've been registering some thoughts here, but the situation as it stands now is same as we discussed: it's the Javascript side of the UI that's causing this. The Go side doesn't seem to be doing anything wrong.

**Comment by uaalto** [comment] 2015-07-21 18:35
Ok. I have a high degree of confidence on the diagnosis and the cure. I can reproduce it and avoid it now.
But I need some help verifying @myleshorton and @sheena3. These 2 files executables should produce the following results:

* https://s3-eu-west-1.amazonaws.com/uaalto/lantern_windows_386_evil_2721.exe
+95% of the time should redirect, reproducing this bug

* https://s3-eu-west-1.amazonaws.com/uaalto/lantern_windows_386_good_2721.exe
Should not trigger this bug.

**Comment by sheena3** [comment] 2015-07-21 18:44
Will update you in few mins @uaalto

On Wed, Jul 22, 2015 at 12:05 AM, Ulysses Aalto <notifications@github.com>
wrote:

> Ok. I have a high degree of confidence on the diagnosis and the cure. I
> can reproduce it and avoid it now.
> But I need some help verifying @myleshorton
> <https://github.com/myleshorton> and @sheena3 <https://github.com/sheena3>.
> These 2 files executables should produce the following results:
>
>    -
>
>
>    https://s3-eu-west-1.amazonaws.com/uaalto/lantern_windows_386_evil_2721.exe
>    +95% of the time should redirect, reproducing this bug
>    -
>
>
>    https://s3-eu-west-1.amazonaws.com/uaalto/lantern_windows_386_good_2721.exe
>    Should not trigger this bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2721#issuecomment-123431049>
> .
>



-- 
Regards,
Sunshine

**Comment by sheena3** [comment] 2015-07-21 18:57
@uaalto I am getting the message that the .exe is not commonly downloaded and could be dangerous. If I try to proceed with the installation, windows is preventing from starting Lantern.

**Comment by sheena3** [comment] 2015-07-21 18:57
![discard](https://cloud.githubusercontent.com/assets/11394369/8809796/69246494-3008-11e5-90ce-75e55ad62643.png)

**Comment by sheena3** [comment] 2015-07-21 18:58
![preventing](https://cloud.githubusercontent.com/assets/11394369/8809825/9768dbdc-3008-11e5-8fbd-a39e067adab5.png)

**Comment by uaalto** [comment] 2015-07-21 19:24
Thanks @sheena3. It's not an installable, just the executable. You can go to the Lantern installation directory and substitute. If the same blue screen appears you just have to click "more info" and then allow it to run.

**Comment by uaalto** [comment] 2015-07-21 19:26
Maybe I should have made installables for this situation. @myleshorton is the __release-qa__ make task inteded for this purpose?

**Comment by myleshorton** [comment] 2015-07-21 19:33
The release-qa task is to release binaries to qa that we actually think
will go into production ultimately.

If you want to build installers you could just use make package-win though
(I think that's right).

On Tue, Jul 21, 2015 at 12:26 PM, Ulysses Aalto <notifications@github.com>
wrote:

> Maybe I should have made installables for this situation. @myleshorton
> <https://github.com/myleshorton> is the *release-qa* make task inteded
> for this purpose?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2721#issuecomment-123454076>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by uaalto** [comment] 2015-07-21 19:35
Thanks @myleshorton.
@sheena3 were you able to run the executable or do you need an installer?

**Comment by myleshorton** [comment] 2015-07-21 19:46
My network is crazy slow right now but I'm testing this as well. So far the first definitely reproduced it consistently.

**Comment by myleshorton** [comment] 2015-07-21 19:53
Yup the good one works and the bad one doesn't for me for sure @uaalto!

**Comment by uaalto** [comment] 2015-07-21 20:01
Awesomeness!! :)

The fix comes next in a commit. I'm having a problem though with this: for some reason, `make windows` is not updating the `/dist` dir of the UI. I think it should however. I did however updated the javascript build system (gulp tasks) so it worked by manually running it, but I have that in the ARM lantern branch. What do you think if we merge that one so I run the `/dist` generation properly without messing too much with git history?

**Comment by myleshorton** [comment] 2015-07-21 20:04
You can do:

```
UPDATE_DIST=true make package-windows
```

or if you want to just update dist separately (which technically makes sense for the PR):

```
UPDATE_DIST=true make genassets
```

**Comment by xiam** [comment] 2015-07-21 20:04
@uaalto Can you try this?

```
UPDATE_DIST=true make windows
```

**Comment by uaalto** [comment] 2015-07-21 20:14
Yeah it's building! Thank you!! I think I actually did this before :D

**Comment by uaalto** [comment] 2015-07-21 20:33
A purely javascript-side solution. I think this is all there is to this issue. The bug works like this:

1. The User navigates away from the Lantern UI
2. The Lantern UI triggers the onClose() callback because websockets connection has been lost. This is OK.
3. The onClose() handler sets a timer that will retry connecting. Lantern is ready to be connected again, as it should be. This is OK.
4. Sometimes the web unloading (i.e. going to the next page) takes longer than the interval set for reconnection tries. This is OK (it can happen).
4. When this happens, Firefox on Windows decides that it should actually what the code says and just connect to Lantern again.

This is browser-dependent, because a browser could just decide that if the user left intentionally, it should avoid interaction with current web page, even if is not unloaded yet.

So this code forces this.

**Comment by uaalto** [comment] 2015-07-21 21:47
@sheena3 The installer with the working version: https://s3-eu-west-1.amazonaws.com/uaalto/lantern-installer-issue-2721.exe

**Comment by sheena3** [comment] 2015-07-22 15:55
Works perfect!

**Comment by myleshorton** [comment] 2015-07-22 19:00
Hey @uaalto this code is still on a branch somewhere right? I'm just going to re-open until we actually merge it in.

**Comment by uaalto** [comment] 2015-07-22 19:35
Yes @myleshorton , I've just opened a pull request here: https://github.com/getlantern/lantern/pull/2794
I've realized I've been merging there as well the changes for #2429, since was part of the research to discover this bug.

**Closed** 2015-07-22 19:47 UTC
Labels: P1, QA
