### ISSUE TITLE
IE sometimes gets into completely broken state

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2741] opened 2015-07-15 22:36 UTC
Related to #2719. It always shows "This page can't be displayed".

When in this state, if you change the system proxy settings to not use the PAC file, it works for unblocked sites.

**Comment by uaalto** [comment] 2015-07-16 08:31
I could reproduce it just once, after +10 tries. The very nature of this error leads me to believe it is related to the race condition you've been working on @myleshorton. It also makes me think it is related to https://github.com/getlantern/lantern/issues/2721, due to its similar behavior and reproducibility.

**Comment by uaalto** [comment] 2015-07-16 08:33
I could reproduce it just once, after +10 tries. The very nature of this error leads me to believe it is related to the race condition you've been working on @myleshorton. It also makes me think it is related to https://github.com/getlantern/lantern/issues/2721, due to its similar behavior and reproducibility.

**Comment by myleshorton** [comment] 2015-07-17 20:28
I agree @uaalto -- I think #2721 could actually be a great clue. I'm going to try to reproduce that.

**Comment by myleshorton** [comment] 2015-07-18 14:18
Hey @fffw and @uaalto have either of you been checking your logs while testing this? I'm curious if some of these issues like these ```GetAddrInfoW``` errors might be related. Can you try just grepping for ERROR in your log if you're able to get this again (I haven't been able to get into this state since my changes to the startup race stuff).

**Comment by uaalto** [comment] 2015-07-18 16:54
Nope, sorry. I could reproduce all these glitches very few times, and it became especially hard after the latest changes. Among the initialization issues that we've been having, particularly this one has occurred just once or twice in my case.
What I was trying to figure out in my latest investigation is the defect that redirects the user to the same lantern home page when they write any arbitrary address in that tab. I want to see what's the exact signal that the browser receives from Lantern to produce such result. As weird as it seems, it appears to be a reload of the page, or a redirect, but I don't think this is the reason.

Anyway, this other issue I'm talking about may or may not be related to the issue in this thread. I'll do a bunch of runs now and try to get a log.

**Comment by uaalto** [comment] 2015-07-19 12:16
Has any of you been able to reproduce it after https://github.com/getlantern/lantern/issues/2719 closed?

**Comment by uaalto** [comment] 2015-07-19 12:42
15 tries, 2 reboots. I would close this as _not reproducible_. I've used the version with @myleshorton changes and my latest additions too.

**Comment by myleshorton** [comment] 2015-07-20 19:38
I know @fffw was able to get into this state even after my changes. Are you still able to reproduce it @fffw? Maybe it has something to do with actually running in a censored region?

**Comment by fffw** [comment] 2015-07-21 02:25
IE can open Lantern page as well as other pages during OS startup now. I think the change @uaalto made in https://github.com/getlantern/lantern/pull/2769 resolves it! Bravo!

**Closed by fffw** 2015-07-21 02:25 UTC
Labels: P1
