### ISSUE TITLE
Lantern blocks other apps' connection to the Internet except Chrome.

### ISSUE THREAD

**Issue by Chigogo** [getlantern/lantern#3289] opened 2015-10-28 11:54 UTC
OS: Mac OS X El Capitan
Lantern: 2.0.10

When lantern run in the background for some time, the safari or iTunes or Mac App Store, whatever, will not be able to connect to the Internet, even when you have cleared out all the checkboxes in the proxy configuration panel.

It seems like an old issue:https://groups.google.com/forum/#!topic/lantern-users-zh/a6VkwiZb_uQ

**Comment by myleshorton** [comment] 2015-10-28 21:05
Thanks @Chigogo. So this only happens after running Lantern for awhile, is that correct? It works at the beginning but then stops working? I wonder if those apps don't respect the PAC file or something like that.

**Comment by Chigogo** [comment] 2015-10-30 14:35
Yes, I noticed that  this only happens after running Lantern for a while. 
In fact, we want that Lantern won't auto-set the pac proxy at launching time. Cause we often use browser-level proxy plug-in. And the provided Pac file is not suitable for Chinese users.

**Comment by myleshorton** [comment] 2015-11-02 22:12
Thanks @Chigogo. Approximately how long does it take for Lantern to start failing?

In terms of the pac file, the other aspect of it is that Lantern's pac file is very dynamic -- i.e. it will add sites that it knows are *not blocked* to the list of sites to access directly.

**Comment by Chigogo** [comment] 2015-11-04 06:13
I solve that problem by putting lantern running in the Windows which is inside the Parallel Desktop. Thus, lantern will not have effects on the OS X system.

**Comment by yuansf** [comment] 2015-11-23 09:22
I have same issue.
China
OS: Mac OS X El Capitan
Lantern: 2.0.10
Safari and App Store can not use network,iTerm/Chrome/Firefox/Opera/QQ/WeChat can use.

**Comment by lionhylra** [comment] 2015-12-17 17:17
I have the same issue. Is there any solution?

**Comment by wishsoul** [comment] 2016-01-03 05:39
I have the same issue. Is there any solution?

![2016-01-03 13 37 36](https://cloud.githubusercontent.com/assets/6064240/12077451/400ee4e6-b21f-11e5-93fe-44c7937ef126.png)

**Comment by wutaizeng** [comment] 2016-02-20 08:54
+1

**Comment by Chigogo** [comment] 2016-02-23 04:32
@wishsoul 
@lionhylra 
The solution Can be found on ManYouIT. Use WeChat to search for that.

**Comment by fffw** [comment] 2016-04-22 02:20
It should be caused by detour incorrectly detect the site as being blocked. With upcoming detour improvements, and the `manage system proxy` option, it can be resolved. Close this to avoid duplication.

**Closed by fffw** 2016-04-22 02:20 UTC

**Comment by Chigogo** [comment] 2016-05-03 07:49
Thanks.
