### ISSUE TITLE
Lantern crashes in Ubuntu 32-bit after changing the DNS server to block all sites

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2647] opened 2015-06-16 18:44 UTC
After changing the DNS server to point to our fake DNS server, I couldn't launch lantern.

Steps:
1. Change the DNS server to block all sites.
2. Verify without lantern that the sites are not accessible.
3. Now launch lantern

Lantern appears and then disappears immediately from the system tray without launching in the browser.

Let me know if more details are needed.

**Comment by fffw** [comment] 2015-06-17 02:32
@sheena3 Did it occur only if you changed DNS server to fake one?

Hopefully there are a few logs (if it found some error condition and quit gracefully) you can collect.

Logged a new ticket https://github.com/getlantern/lantern/issues/2648 to add global panic handler so we can have log even if it panics.

**Comment by xiam** [comment] 2015-06-17 02:43
This is probably related to https://github.com/getlantern/lantern/issues/2482

**Comment by sheena3** [comment] 2015-06-17 15:29
Yes @fffw, it happened only when I changed the DNS server. Yeah, I can send you the log.

**Comment by fffw** [comment] 2015-06-18 01:30
Below is the relevant log. For readability, I separated them into blocks with blank lines.

```
...
Jun 16 17:44:53.530 - DEBUG flashlight: flashlight.go:345 No exit func remaining, exit now

Jun 16 18:01:32.301 - DEBUG i18n: translate.go:102 Setting locale en_US
Jun 16 18:01:32.419 - DEBUG flashlight: flashlight.go:166 ---- flashlight version: 2.0.0-beta6, release: 2.0.0-beta6, build date: 20150607.213203 ----
Jun 16 18:01:32.421 - DEBUG flashlight.config: config.go:177 Placing configuration in /home/sunshine/.lantern
Jun 16 18:01:32.725 - DEBUG i18n: translate.go:102 Setting locale en_US
Jun 16 18:01:32.770 - DEBUG flashlight: flashlight.go:166 ---- flashlight version: 2.0.0-beta6, release: 2.0.0-beta6, build date: 20150607.213203 ----
Jun 16 18:01:32.770 - DEBUG flashlight.config: config.go:177 Placing configuration in /home/sunshine/.lantern
Jun 16 18:01:33.777 - DEBUG yamlconf: yamlconf_disk.go:50 Configuration changed on disk, applying
Jun 16 18:01:34.150 - DEBUG yamlconf: yamlconf_disk.go:50 Configuration changed on disk, applying
Jun 16 18:01:34.553 - DEBUG flashlight.statreporter: statreporter.go:84 Stat reporting turned off
Jun 16 18:01:34.555 - DEBUG flashlight: flashlight.go:143 Running proxy
Jun 16 18:01:34.588 - DEBUG flashlight.statreporter: statreporter.go:84 Stat reporting turned off
Jun 16 18:01:34.594 - DEBUG flashlight: flashlight.go:143 Running proxy
Jun 16 18:01:34.718 - DEBUG flashlight: flashlight.go:345 No exit func remaining, exit now
Jun 16 18:01:34.876 - DEBUG flashlight: flashlight.go:345 No exit func remaining, exit now

Jun 16 18:02:04.524 - DEBUG i18n: translate.go:102 Setting locale en_US
Jun 16 18:02:04.643 - DEBUG flashlight: flashlight.go:166 ---- flashlight version: 2.0.0-beta6, release: 2.0.0-beta6, build date: 20150607.213203 ----
Jun 16 18:02:04.645 - DEBUG flashlight.config: config.go:177 Placing configuration in /home/sunshine/.lantern
Jun 16 18:02:04.851 - DEBUG yamlconf: yamlconf_disk.go:50 Configuration changed on disk, applying
Jun 16 18:02:05.141 - DEBUG flashlight.statreporter: statreporter.go:84 Stat reporting turned off
Jun 16 18:02:05.141 - DEBUG flashlight: flashlight.go:143 Running proxy
Jun 16 18:02:05.143 - DEBUG flashlight: flashlight.go:345 No exit func remaining, exit now

Jun 16 18:03:59.491 - DEBUG i18n: translate.go:102 Setting locale en_US
Jun 16 18:03:59.643 - DEBUG flashlight: flashlight.go:166 ---- flashlight version: 2.0.0-beta6, release: 2.0.0-beta6, build date: 20150607.213203 ----
Jun 16 18:03:59.645 - DEBUG flashlight.config: config.go:177 Placing configuration in /home/sunshine/.lantern
Jun 16 18:04:00.037 - DEBUG yamlconf: yamlconf_disk.go:50 Configuration changed on disk, applying
Jun 16 18:04:00.065 - DEBUG flashlight.statreporter: statreporter.go:84 Stat reporting turned off
Jun 16 18:04:00.066 - DEBUG flashlight: flashlight.go:143 Running proxy
Jun 16 18:04:00.067 - DEBUG flashlight: flashlight.go:345 No exit func remaining, exit now

Jun 16 18:05:09.643 - DEBUG i18n: translate.go:102 Setting locale en_US
Jun 16 18:05:09.657 - DEBUG flashlight: flashlight.go:166 ---- flashlight version: 2.0.0-beta6, release: 2.0.0-beta6, build date: 20150607.213203 ----
...
```

We can have some clues:
1. Logs from `18:01:32.301` to `18:01:34.876` are interleaved, which means two Lantern instance was launched simultaneously (clicked twice).
2. ["Lantern stopped" message](https://github.com/getlantern/lantern/blob/release-2.0.0-beta6/src/github.com/getlantern/flashlight/flashlight.go#L92) didn't get logged, even for normal exiting. It's because we [closed logging too soon](https://github.com/getlantern/lantern/blob/release-2.0.0-beta6/src/github.com/getlantern/flashlight/flashlight.go#L103).
3. [ `log.Fatal()`](https://github.com/getlantern/lantern/blob/release-2.0.0-beta6/src/github.com/getlantern/flashlight/flashlight.go#L90) will not get logged to file for same reason as 2.
4. [exit handler](https://github.com/getlantern/lantern/blob/release-2.0.0-beta6/src/github.com/getlantern/flashlight/flashlight.go#L344) was called, which means it didn't panic.

I created a hot fix PR to beta 6 at https://github.com/getlantern/lantern/pull/2653 so we can capture the concrete error.

**Comment by myleshorton** [comment] 2015-07-02 22:23
I'm unable to reproduce this with the latest code on Ubuntu 14.04 and the latest code on Valencia. Closing for now!

**Closed by myleshorton** 2015-07-02 22:23 UTC
Labels: P1
