### ISSUE TITLE
Edge on Windows 10 can't open Lantern page

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3363] opened 2015-12-23 09:02 UTC
![image](https://cloud.githubusercontent.com/assets/10410437/11973519/3a778966-a996-11e5-9f3c-6963d94495cb.png)

[http://localhost:16823]() can be opened instead. `curl 127.0.0.1:16823` also works. `http://127.0.0.1:16823` can be opened in Chrome as well.

Edge 20.10240.16384.0, running from MsEdge + Win 10 Vagrant package downloaded from https://dev.windows.com/en-us/microsoft-edge/tools/vms/mac/.

**Comment by cloudhan** [comment] 2016-02-21 07:08
Windows App does not allow loopback connection since Windows 8, you should add exemption for the specific app to allow it connect to localhost
check this link
[](https://msdn.microsoft.com/en-us/library/windows/apps/hh780593.aspx)

you can also use this utility on Win10
[Windows 8 Loopback Exemption Manager](https://loopback.codeplex.com/)

**Comment by sunshine19090** [comment] 2016-03-01 19:49
![image](https://cloud.githubusercontent.com/assets/11394369/13439610/2b0542be-dfa3-11e5-859f-0c121dddc0a8.png)

Mobile Ad: If I enter ui.lantern.io

![image](https://cloud.githubusercontent.com/assets/11394369/13439705/8f4f4378-dfa3-11e5-9ddf-f5e75c100967.png)

Settings:

![image](https://cloud.githubusercontent.com/assets/11394369/13439717/9c702176-dfa3-11e5-8dc0-ce840ed11ac2.png)

**Comment by oxtoacart** [comment] 2016-03-01 20:07
@sunshine19090 What steps do I have to take to get the mobile ad to show up in Edge?

**Comment by sunshine19090** [comment] 2016-03-01 20:09
@oxtoacart I just opened lantern in private window.

**Comment by oxtoacart** [comment] 2016-03-01 20:10
Thanks @sunshine19090!

**Comment by oxtoacart** [comment] 2016-03-01 20:39
The 127.0.0.1 url doesn't work in Edge because of a new feature of modern style Windows applications called "network isolation".  Internet Explorer is unaffected by network isolation.  This is the whole reason that we use ui.lantern.io for Edge.

**Comment by oxtoacart** [comment] 2016-03-01 21:01
@sunshine19090 Weird, I can't reproduce.  Does this happen for you consistently?

![screen shot 2016-03-01 at 3 00 21 pm](https://cloud.githubusercontent.com/assets/5000654/13441753/7f6cad90-dfbe-11e5-8802-edd2c63097e8.png)

**Comment by sunshine19090** [comment] 2016-03-01 21:08
Yes @oxtoacart. Each and every time I refresh or use show lantern.

**Comment by myleshorton** [comment] 2016-03-01 21:27
Does Edge have a developer console? Seems like some of those requests
aren't working for whatever reason.

On Tue, Mar 1, 2016 at 1:09 PM, sunshine19090 <notifications@github.com>
wrote:

> Yes @oxtoacart <https://github.com/oxtoacart>. Each and every time I
> refresh or use show lantern.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/3363#issuecomment-190905996>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by sunshine19090** [comment] 2016-03-01 21:38
Closing this ticket as I am able to open the Lantern page in edge browser now. New ticket is raised for the text issue #3687.

**Closed** 2016-03-01 21:38 UTC
Labels: P1, QA
