### ISSUE TITLE
Text in Edge browser is not displayed properly in Windows 10

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3687] opened 2016-03-01 21:37 UTC
![image](https://cloud.githubusercontent.com/assets/11394369/13442736/891be056-dfb2-11e5-811a-765dbbf0c25e.png)

![image](https://cloud.githubusercontent.com/assets/11394369/13442746/94892b60-dfb2-11e5-992e-0219f98dc1e7.png)

![image](https://cloud.githubusercontent.com/assets/11394369/13442751/99ece786-dfb2-11e5-8828-894549be2cbe.png)

**Comment by oxtoacart** [comment] 2016-03-01 21:54
@sunshine19090 To confirm, this is not specific to Edge, right?

**Comment by sunshine19090** [comment] 2016-03-01 21:58
It is specific to Edge @oxtoacart. Firefox and Chrome in Windows 10 is good.

**Comment by oxtoacart** [comment] 2016-03-01 22:01
Ah, got it, thanks!

**Comment by oxtoacart** [comment] 2016-03-02 14:40
This looks very much like #3503

**Comment by oxtoacart** [comment] 2016-03-02 14:45
@sunshine19090 Since I can't reproduce this, would you mind seeing what you can find in the developer tools console?  I suspect that there's a JavaScript error happening.  You can't open the console in Private mode, but you can get the ad to come up in regular mode by first clearing all browsing data from the Settings -> Advanced menu.

**Comment by sunshine19090** [comment] 2016-03-02 19:24
@oxtoacart  I don't see anything in the console. It is blank. I did use normal window. 

![image](https://cloud.githubusercontent.com/assets/11394369/13472330/3eef55d2-e069-11e5-8a01-422dac12bb1b.png)

**Comment by myleshorton** [comment] 2016-03-02 19:46
Hmnn...unfortunately my own Windows 10 VM appears to be corrupt, but I can join the party as soon as I'm able to download it.

**Comment by fffw** [comment] 2016-03-04 06:14
Edge 20.10240.16384.0 on Win 10 VM didn't exhibit this behaviour, for both 0303 and 0227 build of Lantern 2.1.0.

This issue should be caused by Javascript error but that can't explain why console is blank.

**Comment by oxtoacart** [comment] 2016-03-04 14:26
@fffw Thanks for checking!  @sunshine19090 out of curiosity, how does Lantern 2.0.16 do on your test machine with Edge?

**Comment by myleshorton** [comment] 2016-03-04 18:18
I'm also not seeing this in win 10 Enterprise N with Edge 25.10586.0.0. @sunshine19090 and @oxtoacart

**Comment by oxtoacart** [comment] 2016-03-04 18:32
Thanks for checking @myleshorton!  Given that this seems to be fairly isolated to a specific installation, should we ignore for now?

**Comment by sunshine19090** [comment] 2016-03-04 19:05
I upgraded my system from win 8.1 to win10 to verify this issue. Could it be a reason? 

@oxtoacart Anyway, I checked 2.0.16 and it also has the same problem but I got a console error for 2.0.16. I will check once again for the latest build.

![image](https://cloud.githubusercontent.com/assets/11394369/13537274/fe58f294-e1f8-11e5-9c18-88563de2ba14.png)

**Comment by sunshine19090** [comment] 2016-03-04 19:09
@oxtoacart and @myleshorton I got this from the latest build.

![image](https://cloud.githubusercontent.com/assets/11394369/13537382/9170568a-e1f9-11e5-80e4-e3a7d332835b.png)

**Comment by oxtoacart** [comment] 2016-03-04 19:13
@sunshine19090 That's very helpful!  I'm guessing by the LANG_ID in the URL that we failed to identify the user's language.

@atavism @xiam Any insights?

**Comment by xiam** [comment] 2016-03-04 19:36
I'll take this one @oxtoacart, @sunshine19090

**Comment by oxtoacart** [comment] 2016-03-04 21:25
@xiam Thanks!

**Comment by oxtoacart** [comment] 2016-03-09 18:09
@xiam Any news on this?  Anything I can help with if you want to point me in the right direction?

**Comment by myleshorton** [comment] 2016-03-09 18:14
I think @xiam is tied up with pro stuff. This worked fine for me in Edge on Win10, so I'm moving it to 2.1.1 for now.

**Comment by oxtoacart** [comment] 2016-03-09 18:20
@sunshine19090 mentioned that her machine might be using the India flavor of English, so it's possible that our code doesn't work if a non en_US flavor is used.  I'm just guessing though.

**Comment by xiam** [comment] 2016-03-09 22:10
Hey @oxtoacart, sorry still have not checked this one (working on pro), I think it has to do something with the angular translation library we use (angular-translate), we currently don't have a Hindi translation and for some reason it's not falling back to English. Had a similar problem with Safari in the past and solved it with a library update.

**Comment by oxtoacart** [comment] 2016-03-09 22:14
Thanks @xiam!

**Comment by sunshine19090** [comment] 2016-03-29 20:21
This still looks the same in my system. I checked the system settings for language and it is English (India).

**Comment by sunshine19090** [comment] 2016-03-30 19:52
@myleshorton This works fine after I changed my region to English(United States). Not sure how many users might get affected by this issue. So moving the priority to P3.

**Comment by myleshorton** [comment] 2016-04-27 19:45
@sunshine19090 what language was your system set to before you set it to english?

**Comment by sunshine19090** [comment] 2016-04-27 19:58
@myleshorton It was English(India). I still have my language set to English (India) and now I don't see any problem. Also, I noticed that I am able to open lantern page using http://127.0.0.1:16823 instead of ui.lantern.io in Edge browser. In previous releases, I wouldn't be able to use the former.

**Closed** 2016-04-28 04:28 UTC
Labels: P3
