### ISSUE TITLE
Detour is not working in Windows 7

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4356] opened 2016-05-23 19:37 UTC
Under blocked conditions (using fake DNS), I couldn't access geoiptool.com, slack, amazon etc., but able to access it immediately after turning on Proxy all traffic. This happens even after restarting my system. 

Under blocked conditions in Windows 10, lantern identifies and proxies geoiptool.com, slack and amazon as well even without turning on proxy all traffic.

**Comment by fffw** [comment] 2016-05-24 09:10
@sunshine19090 Unfortunately I couldn't reproduce. On my Win7 VM with DNS manually set to fake ones like `1.2.3.4`, any site was not able to open without Lantern running (expected). The screen is as below. Did you see the same screen when sites failed to open?
![image](https://cloud.githubusercontent.com/assets/10410437/15498094/948b4f0c-21d0-11e6-9bdc-d7cbcac56c02.png)

But when Lantern was running (no matter proxy all or not), all sites can be open. I tried IE 10, Firefox 39 and Chrome 44.

What's your exact steps to use fake DNS? Maybe I need to follow the same to reproduce.

**Comment by sunshine19090** [comment] 2016-05-24 18:33
@fffw I am able to reproduce it again. 

With DNS blocking and lantern not running, I see the below page when accessing slack.

![image](https://cloud.githubusercontent.com/assets/11394369/15515435/16efe99a-21a3-11e6-825d-d00dbcf75e5c.png)

I see the same page with lantern running when proxy all traffic option is turned off.

For DNS blocking, I use the fake DNS by modifying it in Network and sharing center - selecting my wifi connection properties and modifying the IPV4 DNS address manually.

**Comment by myleshorton** [comment] 2016-05-24 22:52
And this was working in 2.2.4 @sunshine19090?

**Comment by sunshine19090** [comment] 2016-05-24 23:15
No @myleshorton, in the before releases under blocked condition I wouldn't be able to access sites that are not in the default whitelist without using proxy all traffic but @oxtoacart pointed out to me that detour is supposed to let the user access all sites irrespective of the proxy all traffic option under blocked condition when I raised the issue 3900 in 2.1.2 release and I think he made some changes to that, not sure though. So, as per my understanding now Windows 10 and Ubuntu proxies all sites under blocked condition but windows 7 still behaves the same. That's why I raised this ticket. Please correct me if I am wrong in my understanding about detour.

**Comment by sunshine19090** [comment] 2016-05-24 23:17
This is probably still a bug in Mac. I will test it today night.

**Comment by fffw** [comment] 2016-05-24 23:42
@sunshine19090 Could you send your logs directly to me?

**Comment by sunshine19090** [comment] 2016-05-25 00:51
Sent it @fffw

**Comment by fffw** [comment] 2016-05-25 02:43
Thanks @sunshine19090 

I think I know the reason. The fake DNS resolves every site to 127.0.0.1, which actively closes any incoming connections immediately. It causes [`Write`](https://github.com/getlantern/lantern/blob/release-2.3.0/src/github.com/getlantern/detour/detour.go#L292) to fail and return error directly (only `Read` has the logic to detect blockage).

It rarely happens in reality, as it always takes some time for the Lantern client to notice a connection being closed, so `Write` should hardly fail. I should've found it out earlier as both detour and the fake DNS has been there for more than 1 year.

I guess we could have the fake DNS point any sites to itself, which has no 80/443 port open.

The new detour should not have the problem as it always writes parallel if possible, but it's not merged yet.

**Comment by sunshine19090** [comment] 2016-05-25 04:54
@fffw That makes sense but if that is the case then how it works fine in Windows 10 and Ubuntu?

**Comment by fffw** [comment] 2016-05-25 04:59
@sunshine19090 Actually I don't know. As it's very time sensitive, so maybe `Read` is called first when you were testing on Windows 10 and Ubuntu? Could you try the old fashion trick to modify /etc/hosts directly and point the site to an IP without HTTP server running (the IP of fake DNS, for example) ?

**Comment by sunshine19090** [comment] 2016-05-25 05:34
@fffw I completed testing this functionality in Mac and detour works fine. The problem is only with Windows 7. Should I try the older method in win 7 or win 10?

**Comment by fffw** [comment] 2016-05-25 07:25
Oh @sunshine19090 I mean on Win 7 on which test failed.

**Comment by myleshorton** [comment] 2017-08-04 18:50
I should close this right @fffw?

**Comment by myleshorton** [comment] 2017-08-04 18:51
Closing for now...

**Closed by myleshorton** 2017-08-04 18:51 UTC
Labels: P1

**Comment by joesis** [comment] 2017-08-04 23:58
Thanks @myleshorton . Yeah it doesn't seem to be an issue in the field.
