### ISSUE TITLE
lantern not work on ubuntu

### ISSUE THREAD

**Issue by imasood** [getlantern/lantern#3441] opened 2016-01-26 09:02 UTC
lantern isn't work for me on ubuntu 15.10
where is problem?

thanks

**Comment by SmilingNavern** [comment] 2016-01-26 22:54
Could you please elaborate? what do you mean by don't work? How can i reproduce your problem?(provide required steps)

**Comment by imasood** [comment] 2016-01-27 22:32
when i click on lantern icon, program runs correctly but when i try to open twitter or facebook I get an error in chrome.
thanks

**Comment by kashu** [comment] 2016-02-19 12:52
Go to Chrome/Chromium --> Extentions --> SwitchyOmega --> PROFILES

![](http://ww3.sinaimg.cn/large/9c4ddab1jw1f14xshkt8nj20rw0lcgsk.jpg)

or 

![](http://ww1.sinaimg.cn/large/9c4ddab1jw1f14xsq79t2j20rw0lc0xb.jpg)

**Comment by uaalto** [comment] 2016-04-27 16:07
Thank you for posting this instructions @kashu !
I'll be closing this because we have no more news from the op and there wasn't any information that we could use to actually identify a bug.

**Closed by uaalto** 2016-04-27 16:07 UTC
