### ISSUE TITLE
Did anybody have this question that after uninstall lantern could not surf the internet via Mac

### ISSUE THREAD

**Issue by wonderLiu** [getlantern/lantern#3369] opened 2015-12-26 08:30 UTC
the OSX is the newest version 10.11.2 ,and the lantern is 2.0.10。

**Comment by enolate** [comment] 2016-02-19 12:35
I have the same problem. Did you eventually come up with a solution?

**Comment by xiam** [comment] 2016-02-19 14:03
Can you try going to **System Preferences**, **Network**, your network interface and the Proxies tab so see if there's something odd?

Mine looks like this:

![screen shot 2016-02-19 at 6 41 50 am](https://cloud.githubusercontent.com/assets/385670/13177516/39abc468-d6df-11e5-83ca-6464a76b5dd7.png)

**Comment by enolate** [comment] 2016-02-20 01:33
Mine had a tick on automatic proxy configuration. I unticked it, but still no connection via safari. It seems that only chrome can still access internet.

**Comment by wonderLiu** [comment] 2016-02-21 07:22
try to add the following DNS  numbers
199.91.73.222
178.79.131.110

**Comment by myleshorton** [comment] 2016-02-23 05:32
I suspect this is related to #3039. Does `sudo killall -9 networkd` in terminal fix the problem @enolate or @wonderLiu?

**Comment by enolate** [comment] 2016-02-23 07:31
I found #3039 as well, but before I tried that, I restarted my Mac and somehow the internet worked again. I can still use Lantern, and after I shut Lantern down I still have access to the Internet. I don't know how it was fixed, but if this problem happens again, I will try this sudo command and see if it works.

**Comment by myleshorton** [comment] 2016-02-23 17:07
Great thanks @enolate. Yeah I think there's something specific that triggers it, but I'm still not sure what. So it makes sense that it wouldn't happen every time.

**Comment by myleshorton** [comment] 2016-02-26 19:26
Marking as a duplicate of #3039

**Closed by myleshorton** 2016-02-26 19:26 UTC
Labels: P1
