### ISSUE TITLE
[flashlight] Unable to upload files to GitHub

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2184] opened 2015-01-22 17:42 UTC
For example, try to upload a build of flashlight to a GitHub release while running over flashlight.  It uploads some data, but then the connection resets before it finishes.

**Comment by myleshorton** [comment] 2015-01-22 17:43
Interesting. So it's pretty likely this applies to any site and not just to GitHub right?

**Comment by oxtoacart** [comment] 2015-01-22 17:47
> Interesting. So it's pretty likely this applies to any site and not just to GitHub right?

Oddly enough, I'm able to upload a 7MB flashlight build to drive.google.com.

**Comment by myleshorton** [comment] 2015-01-22 17:49
Strange. Is that how big flashlight is now?

**Comment by oxtoacart** [comment] 2015-01-22 17:53
> Strange. Is that how big flashlight is now?

No, that was an old build that I had lying around.  A recent build is around 13-17MB depending on platform, uncompressed.

**Comment by myleshorton** [comment] 2015-01-22 18:01
Interesting. Looks like about 6MB UPXed. Any idea how much of that is Natty?

**Comment by oxtoacart** [comment] 2015-01-22 18:06
Based on natty's object file, I'm guessing that about 10MB of that is Natty.

**Comment by oxtoacart** [comment] 2015-01-24 04:26
I see an error like this in the client log when this happens:

```
enproxy: Failing on Dest: s3.amazonaws.com:443    ProxyHost: fl-singapore-001-37.getiantem.org    Unable to issue write request: Bad response status for read: 502 Bad Gateway
```

**Comment by oxtoacart** [comment] 2015-01-24 04:50
GitHub file uploads go to Amazon S3.  I see this on the fl-singapore-001-37 server log, which could be related:

```
Jan 24 04:24:09 fl-singapore-001-37 flashlight: enproxy: Responding Bad Gateway: Unable to write to connOut: write tcp 54.231.244.8:443: broken pipe
```

**Comment by oxtoacart** [comment] 2015-01-24 04:52
I see similar errors about 2-3 times per hour on that server.

**Comment by oxtoacart** [comment] 2015-01-24 05:22
I bet something along the way (probably CloudFlare) is buffering the upload.  From Amazon's perspective, it looks like something opened a connection, did the TLS handshake, and then just sat there doing nothing.  At some point, Amazon times out the connection, and our upload fails.

**Comment by myleshorton** [comment] 2015-03-01 08:44
This one's still an issue right @oxtoacart?

**Comment by oxtoacart** [comment] 2015-03-01 09:06
Yup.

**Comment by oxtoacart** [comment] 2015-03-03 08:05
I just tried uploading a small image to GitHub and that didn't work either.

**Comment by fffw** [comment] 2015-03-05 13:40
I just successfully uploaded a 3.9MB dmg to GitHub. By watching detour log, the writes to s3.amazonaws.com are pretty normal.

**Comment by oxtoacart** [comment] 2015-03-05 13:56
@fffw Thanks!  I did run into this just a few days ago, so I there's definitely still some diagnosing to do.

**Comment by xiam** [comment] 2015-06-10 18:49
Testing upload.

![testpic](https://cloud.githubusercontent.com/assets/385670/8091115/6c4c3156-0fa1-11e5-8001-9499d7f61df8.png)

**Comment by xiam** [comment] 2015-06-10 18:51
Tried with a 9M file.

![screen shot 2015-06-10 at 1 49 14 pm](https://cloud.githubusercontent.com/assets/385670/8091139/a94bd3ba-0f77-11e5-8c78-3d3ca1e0cd48.png)

**Comment by xiam** [comment] 2015-06-10 19:03
Also tried with a couple of files more, 20M and 9M on a release page.

![screen shot 2015-06-10 at 2 00 25 pm](https://cloud.githubusercontent.com/assets/385670/8091365/14724b46-0f79-11e5-94a6-6d881a40837a.png)

**Comment by aranhoide** [comment] 2015-06-10 19:34
Should we close this until someone reports it again, then?

**Comment by myleshorton** [comment] 2015-06-11 02:53
My guess is it works with chained proxies but not with domain fronting. Can you try turning chained proxies off @xiam?

**Comment by xiam** [comment] 2015-06-12 18:58
Good idea @myleshorton, I did try with domain fronting only and it indeed does not work when the request takes more than ~30s, I also used a simulated slow network for this test. It works for smaller uploads though.

The Github UI acted weird too:

![screen shot 2015-06-12 at 1 28 20 pm](https://cloud.githubusercontent.com/assets/385670/8137336/4138b85a-1108-11e5-815c-b501771bc8a6.png)

This is the most relevant part of the log:

```
Jun 12 18:47:45.117 - DEBUG detour: detour.go:284 Error while write 32768 bytes to github-cloud.s3.amazonaws.com:443 detoured: EOF
Jun 12 18:47:45.122 - DEBUG balancer: balancer.go:96 Dialing tcp://github-cloud.s3.amazonaws.com:443 with (trusted) fronted proxy at nl.fallbacks.getiantem.org:443 using masquerade set cloudflare
```

I don't know if the `32768` bytes is of any actual significance, it's the upper limit of an signed 16bit integer, but maybe that's just the size of the chunk we tried to write.

This is the full log since I started the upload until Github gave up trying:

```
Jun 12 18:47:00.943 - DEBUG enproxy: conn_impl.go:45 Proxy connection to api.github.com:443 via 108.162.201.108:443 idle for 10s, closing
Jun 12 18:47:01.105 - DEBUG fronted: dialer.go:231 Dialing geo.getiantem.org:80 with direct domain fronter
Jun 12 18:47:04.867 - DEBUG balancer: balancer.go:96 Dialing tcp://github.com:443 with (trusted) fronted proxy at nl.fallbacks.getiantem.org:443 using masquerade set cloudflare
Jun 12 18:47:04.915 - DEBUG fronted: dialer.go:231 Dialing geo.getiantem.org:80 with direct domain fronter
Jun 12 18:47:05.758 - DEBUG balancer: balancer.go:96 Dialing tcp://logs-01.loggly.com:443 with (trusted) fronted proxy at nl.fallbacks.getiantem.org:443 using masquerade set cloudflare
Jun 12 18:47:05.799 - DEBUG fronted: dialer.go:231 Dialing geo.getiantem.org:80 with direct domain fronter
Jun 12 18:47:07.627 - DEBUG fronted: dialer.go:231 Dialing geo.getiantem.org:80 with direct domain fronter
Jun 12 18:47:08.759 - DEBUG fronted: dialer.go:231 Dialing geo.getiantem.org:80 with direct domain fronter
Jun 12 18:47:12.606 - DEBUG balancer: balancer.go:96 Dialing tcp://live.github.com:443 with (trusted) fronted proxy at nl.fallbacks.getiantem.org:443 using masquerade set cloudflare
Jun 12 18:47:13.645 - DEBUG balancer: balancer.go:96 Dialing tcp://github-cloud.s3.amazonaws.com:443 with (trusted) fronted proxy at nl.fallbacks.getiantem.org:443 using masquerade set cloudflare
Jun 12 18:47:14.911 - DEBUG enproxy: conn_impl.go:45 Proxy connection to www.google.com:80 via 141.101.120.108:443 idle for 10s, closing
Jun 12 18:47:16.470 - DEBUG balancer: balancer.go:96 Dialing tcp://sd.symcd.com:80 with (trusted) fronted proxy at nl.fallbacks.getiantem.org:443 using masquerade set cloudflare
Jun 12 18:47:16.606 - Jun 12 18:47:16.607 - DEBUG fronted: dialer.go:231 Dialing geo.getiantem.org:80 with direct domain fronter
DEBUG fronted: dialer.go:231 Dialing geo.getiantem.org:80 with direct domain fronter
Jun 12 18:47:27.653 - DEBUG flashlight.config: config.go:348 Checking for cloud configuration at: https://config.getiantem.org/cloud.yaml.gz
Jun 12 18:47:27.666 - DEBUG fronted: dialer.go:231 Dialing config.getiantem.org:80 with direct domain fronter
Jun 12 18:47:28.946 - DEBUG fronted: dialer.go:231 Dialing geo.getiantem.org:80 with direct domain fronter
Jun 12 18:47:29.768 - DEBUG flashlight.config: config.go:370 Config unchanged in cloud
Jun 12 18:47:36.089 - DEBUG balancer: balancer.go:96 Dialing tcp://live.github.com:443 with (trusted) fronted proxy at nl.fallbacks.getiantem.org:443 using masquerade set cloudflare
Jun 12 18:47:45.117 - DEBUG detour: detour.go:284 Error while write 32768 bytes to github-cloud.s3.amazonaws.com:443 detoured: EOF
Jun 12 18:47:45.122 - DEBUG balancer: balancer.go:96 Dialing tcp://github-cloud.s3.amazonaws.com:443 with (trusted) fronted proxy at nl.fallbacks.getiantem.org:443 using masquerade set cloudflare
Jun 12 18:47:48.070 - DEBUG balancer: balancer.go:96 Dialing tcp://sd.symcd.com:80 with (trusted) fronted proxy at nl.fallbacks.getiantem.org:443 using masquerade set cloudflare
Jun 12 18:47:48.095 - DEBUG fronted: dialer.go:231 Dialing geo.getiantem.org:80 with direct domain fronter
Jun 12 18:47:53.623 - DEBUG enproxy: conn_intf.go:239 Failing on Dest: github-cloud.s3.amazonaws.com:443    ProxyHost: fl-nl-20150318-010.getiantem.org    Unable to issue write request: Bad response status for read: 502 Bad Gateway
Jun 12 18:47:53.624 - DEBUG enproxy: conn_intf.go:239 Failing on Bad response status for read: 502 Bad Gateway
Jun 12 18:48:04.133 - DEBUG fronted: dialer.go:231 Dialing geo.getiantem.org:80 with direct domain fronter
Jun 12 18:48:08.060 - DEBUG balancer: balancer.go:96 Dialing tcp://live.github.com:443 with (trusted) fronted proxy at nl.fallbacks.getiantem.org:443 using masquerade set cloudflare
```

Out of curiosity I also tested on the same slow network with the same file but with chained proxies enabled, the upload took about 4 minutes but it did work in the end.

This is probably related to https://github.com/getlantern/lantern/issues/2436

**Comment by myleshorton** [comment] 2015-06-13 03:55
Interesting @xiam thanks! Does that log appear right at 30s exactly? I.e. this log in particular?

```
Jun 12 18:47:45.117 - DEBUG detour: detour.go:284 Error while write 32768 bytes to github-cloud.s3.amazonaws.com:443 detoured: EOF
```

If so then one of our timeouts seems almost certainly to blame unless that's some timeout on their or CloudFlare's end of course, but it's hard to imagine what those would be. Could of course be on the flashlight server side as well, but if it's right on 30 seconds that's a pretty good clue.

**Comment by xiam** [comment] 2015-06-15 16:24
Hey @myleshorton,

I did a bunch of other tests today to see with more detail whether this correlation exists or not. From the logs I extracted 3 lines:

* L1: First contact with github-cloud.s3.amazonaws.com.
* L1: First detour failure.
* L2: Second detour failure.

```
Jun 15 15:30:45.643 - DEBUG balancer: balancer.go:96 Dialing tcp://github-cloud.s3.amazonaws.com:443 with
Jun 15 15:31:03.066 - DEBUG detour: detour.go:284 Error while write 32768 bytes to github-cloud.s3.amazonaws.com:443
Jun 15 15:31:36.723 - DEBUG detour: detour.go:284 Error while write 32768 bytes to github-cloud.s3.amazonaws.com:443
```

Time between L1 and L2 | Time between L2 and L3
----------------------------------|---------------------------------
18s | 33s

```
Jun 15 15:33:19.931 - DEBUG balancer: balancer.go:96 Dialing tcp://github-cloud.s3.amazonaws.com:443 with
Jun 15 15:33:37.229 - DEBUG detour: detour.go:284 Error while write 32768 bytes to github-cloud.s3.amazonaws.com:443
Jun 15 15:34:08.697 - DEBUG detour: detour.go:284 Error while write 32768 bytes to github-cloud.s3.amazonaws.com:443
```

Time between L1 and L2 | Time between L2 and L3
----------------------------------|---------------------------------
18s | 31s

```
Jun 15 15:36:23.821 - DEBUG balancer: balancer.go:96 Dialing tcp://github-cloud.s3.amazonaws.com:443
Jun 15 15:36:40.234 - DEBUG detour: detour.go:284 Error while write 32768 bytes to github-cloud.s3.amazonaws.com:443
Jun 15 15:37:11.575 - DEBUG detour: detour.go:284 Error while write 32768 bytes to github-cloud.s3.amazonaws.com:443
```

Time between L1 and L2 | Time between L2 and L3
----------------------------------|---------------------------------
17s | 31s

```
Jun 15 15:39:36.043 - DEBUG balancer: balancer.go:96 Dialing tcp://github-cloud.s3.amazonaws.com:443 with (trusted)
Jun 15 15:39:54.058 - DEBUG detour: detour.go:284 Error while write 32768 bytes to github-cloud.s3.amazonaws.com:443
Jun 15 15:40:26.362 - DEBUG detour: detour.go:284 Error while write 32768 bytes to github-cloud.s3.amazonaws.com:443
```

Time between L1 and L2 | Time between L2 and L3
----------------------------------|---------------------------------
18s | 32s

It looks like a pattern! But note that it's slightly different from the first logs I got, maybe the network speed has something to do with it, not sure. I'm going deeper into this one to determine if this is something we can fix or not.

**Comment by myleshorton** [comment] 2015-06-15 17:11
Very interesting @xiam thanks! My guess is this is some subtle bug in enproxy that would be super valuable to fix, so I think this is time very well spent.

**Comment by xiam** [comment] 2015-06-20 01:15
If a client is on a slow network and tries to send a large chunk of data, the time it takes to send the data to the fronted proxy (client -> cdn -> proxy) affects the time the proxy starts sending data to the destination server. Amazon S3 is kind of impatient and just closes the connection if nothing is received from the other end in more than ~15s.

I went step by step and confirmed Ox's supposition:

1. A client sends a request to a fronted proxy and it opens a nproxy lazy connection to *A*.
1. The client requests some readings from *A*.
1. The proxy reads from *A* and sends data to the client.
1. The client decides to send a large chunk of data, in a slow connection this may take let's say 20s.
1. *A* decides to drop the connection since it has not read a single byte in more than 15s.
1. The Client finishes sending the chunk of data, and enproxy tries to send something to *A* just to discover *A* decided to close the channel. (broken pipe)
1. enproxy does not know what to do and just replies with a 502 error.

Now I am looking at the way enproxy prepares requests, I think that if I can reduce the buffer size and send requests more often the proxy will receive data faster and that will prevent S3 from closing the connection. The problem with that is that each send chunk will carry a constant overhead (enproxy headers). I tested some modifications on that front and found that the upload bar kept growing a bit more longer, that was a positive change but at the end the connection was dropped too, maybe I just need to experiment more in order to find a proper combination between buffer size and timeouts...

**Comment by xiam** [comment] 2015-06-24 23:10
Still no success with this one, team. 

We have less than 20s to feed s3 with a constant amount of bytes, it does not have to be the whole uploaded file, it only needs to be a constant amount, in my testing I've observed than when S3 detects many sudden stops or changes of speed that last a few seconds it drops the connection and that's precisely the thing enproxy does.

With the current enproxy implementation, a connection to S3 is opened in flashlight server's side, this connection is held open and it pipes the incoming content to the destination server (when it has something to pipe), but sometimes it's just sits there waiting for a long time for a message to arrive.

On the client side, enproxy splits the file upload into many small parts and for each one of them it creates a POST request that first goes to the fronted intermediary and then to the flashlight server. If I understand correctly, each POST requests carries an overhead of SSL headers and HTTP headers, besides the actual content the client wants to send and uses one TCP connection. 

If you're requesting small files or if you're on a fast network this is more difficult to notice because either the speed of the network or the size of the small file account for the timeouts the fronted intermediary and the destination server may have, but on a slow network each part takes a longer time to pass from the client to the fronted intermediary then to the flashlight server and finally to the destination server. Also note that the fronted intermediary may force the current part to be complete before passing it to flashlight.

What about the dynamic body size idea?

Using a small bodySize didn't work because more parts (and their corresponding overhead) were required for each part and S3 experienced more pauses between many small parts.

Using a large bodySize didn't work because a larger part required more time to be completely sent, a single long pause.

What about strategies?

The streaming strategy didn't work because yes, the client may be streaming but the fronted intermediary is the first one in the chain that is receiving the chunked HTTP transfer and it waits for the transfer to be complete before passing it to the flashlight server, so it's not really end to end streaming. I also tried without the fronted intermediary by uploading a file that was impossible to upload on a normal test and it worked slowly, but it eventually failed with bigger files.

The buffering strategy also didn't work because it caused more pauses between each part, they were smaller pauses but S3 didn't like them either.

Actually, the streaming strategy performed a bit better than the buffering strategy, I guess that was because S3 prefers a few longer pauses instead of many small ones.
 
Probably enproxy is just not the right approach for slow networks. I'm putting my hope on websockets, which should also represent a speed bump, since they would require significally less overhead to work.

**Comment by oxtoacart** [comment] 2015-06-25 17:50
@xiam Amazing troubleshooting!  Is it possible that this behavior varies by CDN?  I seem to remember that one of the CDNs I tested seemed to buffer uploads to a certain limit (like 1 MB) and then started streaming them.

**Comment by xiam** [comment] 2015-06-25 18:41
It is really nice to read you @oxtoacart!

Yes, I think this behaviour can be different depending on the CDN, in fact, the streaming strategy (slowly) works if we take the CDN out of the equation and use a direct connection to the fronted server.

What do you think of using websockets? Some CDNs are already allowing them.

**Comment by myleshorton** [comment] 2015-06-25 19:15
What's up @oxtoacart!?! Great seeing you one here!

The other aspect of this @xiam is that the streaming versus buffering strategies were created explicitly in response to what specific CDNs support, namely Fastly versus CloudFlare. I believe Fastly supports streaming while CloudFlare does not.

**Comment by oxtoacart** [comment] 2015-06-25 23:56
@xiam @myleshorton It's fun chatting again!

@xiam I think if CDNs are starting to support websockets, those are a really interesting option.  As you say, they remove a lot of the fixed overhead.  I am surprised that the streaming strategy seems slow when bypassing the CDN - sounds like that might be a bug, since in the best case scenario it should theoretically be able to handle the entire interaction with just a single HTTP request.  Of course, take everything I say with a grain of salt since it's been long enough for my memory to degrade significantly :)

@myleshorton Yup, that's why we created the multiple strategies.  I think it's actually CloudFlare that supports streaming, but I don't remember for sure.  There was a spreadsheet with characterizations of the different CDNs floating around Google Drive once upon a time...

Hope ya'll are doing well!

**Comment by myleshorton** [comment] 2015-06-26 22:33
> @xiam @myleshorton It's fun chatting again!

Yes it is!! Thanks for clarifying on the CloudFlare streaming front too -- I actually just saw that in one of the earlier drafts of the domain fronting paper that was recently published.

I agree the websocket approach is promising guys.

**Comment by myleshorton** [comment] 2015-07-13 19:59
Closing this and opening a separate websocket ticket.

**Closed by myleshorton** 2015-07-13 19:59 UTC
Labels: P1
