### ISSUE TITLE
tlsdialer_test.go:224: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2858] opened 2015-07-30 21:35 UTC

**Comment by uaalto** [comment] 2015-07-31 14:46
This error was caused by an error that was handled and *should be ignored*. Fixed on the branch that introduced it.

**Comment by myleshorton** [comment] 2015-08-06 23:02
https://travis-ci.org/getlantern/lantern/builds/74462953

**Comment by uaalto** [comment] 2015-08-07 07:54
It was a different error, but we can use this issue. I'm going to rename issue to the error.

**Comment by uaalto** [comment] 2015-08-07 09:27
Not reproducible locally, after 100 runs.

**Closed** 2015-08-07 19:33 UTC
Labels: P1
