### ISSUE TITLE
In Mac, Lantern is proxying all traffic by default even when the option is disabled.

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3250] opened 2015-10-10 02:20 UTC

**Comment by fffw** [comment] 2015-10-10 07:58
It should not happen theoretically. Which site were you visiting? I guess it might took more than 3 seconds to connect to the site so Lantern considered it as being blocked?

**Comment by sunshine19090** [comment] 2015-10-12 20:40
Am not sure.It is little confusing in Mac. I tried two scenarios to check this. One without fake DNS and the other is with fake DNS.

Without fake DNS: Even if I select proxy all traffic, then too geoiptool.com and speedtest.net are showing local ip. It is interesting that speedtest.net is included in the default list but still showing local ip. In this scenario, I expected that geoiptool.com and speedtest.net to show up remote ip as I am using proxy all option.

With Fake DNS: Even if I am not enabling proxy all traffic, geoiptool.com is showing remote ip. And speedtest.net keeps showing local ip irrespective of what I select. In this scenario, I expected that geoiptool.com page wouldn't be loading as that is the case when I work with Windows.

Let me know if you need more info.

**Comment by Roeis** [comment] 2015-10-18 15:12
have the same problem. OS X EI. can we set a manual list to decide which site need Lantern?

**Comment by myleshorton** [comment] 2015-10-19 18:27
My guess is that this is related to #3267. Were you using multiple windows by chance @sunshine19090?

**Comment by myleshorton** [comment] 2015-10-19 18:30
You also might need to hard refresh your browser @sunshine19090 to bypass the browser cache. Command-Shift-R should do it. Otherwise I'm not able to reproduce this.

**Comment by myleshorton** [comment] 2015-10-19 18:38
Are you on El Capitan as well @sunshine19090?

**Comment by myleshorton** [comment] 2015-10-19 18:39
Oh and thanks @Roeis. This is happening consistently for you on 2.0.9, is that right?

**Comment by sunshine19090** [comment] 2015-10-19 18:53
No @myleshorton, I am using OS X Yosemite. By multiple windows(or tabs), do you mean too many lantern pages or just multiple windows of same browser? I might have used multiple tabs with just one lantern tab - not sure though.

**Comment by myleshorton** [comment] 2015-10-19 20:01
I mean multiple Lantern windows, either in tabs or windows themselves.

**Comment by sunshine19090** [comment] 2015-10-20 00:09
Yeah, you are right @myleshorton. It happens only when I open Lantern more than once (In safari, lantern page just gets refreshed and doesn't open a new lantern tab). If Lantern is run just once, then the proxy all works just fine but have to close and reopen a new tab - refreshing doesn't work for me.

**Comment by myleshorton** [comment] 2016-02-29 21:58
I haven't been able to reproduce this. Closing!

**Closed by myleshorton** 2016-02-29 21:58 UTC
Labels: P1
