### ISSUE TITLE
Reverts back to default settings when lantern is opened newly or using "show lantern"

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2480] opened 2015-05-06 17:58 UTC
Steps:

1. Change the settings by unchecking the "Securely report anonymous usage statistics to contribute to Lantern more info" and then close.
2. Now open a new lantern browser. Default setting appears i.e., the checkbox for "Securely report anonymous usage statistics to contribute to Lantern more info" is ticked.

User settings is not saved.

**Comment by fffw** [comment] 2015-05-08 08:24
I can't reproduce it follow the steps on beta 5. When I unchecked the option, it remains unchecked on newly opened page through "Show Lantern", or the one opened after Lantern restart.

The only occurrence is when I open multiple page, uncheck the option on one page, it is still checked on other pages, e.g., it doesn't get auto-refreshed. I think it's acceptable.

**Comment by sheena3** [comment] 2015-05-08 16:39
That is not what I am seeing. I rechecked this.

If it would help, I am testing in windows 8.1 and using chrome browser.

**Comment by sheena3** [comment] 2015-05-11 17:45
@fffw This happens only in chrome browser. In IE and Firefox, it works as expected.

**Comment by myleshorton** [comment] 2015-05-12 05:09
I also can't reproduce this either on Chrome or FireFox @sheena3. I wonder if it might be an issue with bad permissions from a previous Lantern install. Can you try completely deleting the folder at:

c:\Users\your_user_name\AppData\Roaming\Lantern

and running again?

**Comment by sheena3** [comment] 2015-05-12 18:51
Yes, that worked. But I still feel that this is a bug. How would the user know that they have to delete the Lantern folder completely before installing the new version?

**Comment by myleshorton** [comment] 2015-05-13 16:55
The only reason you would have to delete the folder is if you had installed a previous, unreleased version of Lantern that used admin privileges on that folder, making it impossible for newer versions to overwrite the file to save your settings. 

Very weird you're still seeing it with beta 5 though. I'm still unable to reproduce that. Maybe send me your logs?

**Comment by myleshorton** [comment] 2015-05-13 16:59
Wait never mind @sheena3 -- I was just able to make this happen as well. I'll work on it.

**Comment by myleshorton** [comment] 2015-05-13 19:51
This issue is really inconsistent -- sometimes it happens and sometimes it doesn't my guess is there's some sort of race condition on startup. 

To check if it's working relatively easily, you can do:

```
tail -f ~/Library/Logs/Lantern/lantern.log | grep Apply
```

while running. Each time you toggle the settings, you should see two Apply logs. When it doesn't work, you don't see those. Punting to beta 7 since this is clearly an issue but not as important as some of the other issues on the table associated with core functionality.

**Comment by myleshorton** [comment] 2015-05-21 18:44
I'm seeing this with proxyAll as well -- moving to beta 6 since it's definitely a problem.

**Comment by xiam** [comment] 2015-05-21 22:26
I still can't reproduce. It could be a Javascript problem too, did anyone saw if the browser's console printed anything?

**Comment by xiam** [comment] 2015-05-21 22:29
Also, are the Kb/s indicator or the map lights changing? Probably the UI is not communicating with the Lantern backend.

**Comment by xiam** [comment] 2015-05-22 00:53
Tested on Linux too but still unable to reproduce. I could not find any obvious clues in the code either but I think this could be related to a communication loss between the client and the Lantern backend. It would be very useful to know if you suspect the UI is not getting any updates at all, besides the config thing, then we could use a different approach.

**Comment by myleshorton** [comment] 2015-05-22 04:22
I'm able to reproduce this quite often on OSX and Windows, @xiam, so why don't I just take this one and see if I can figure it out? It'll be very difficult to fix without reproducing.

**Comment by xiam** [comment] 2015-05-22 13:34
@myleshorton Yeah, I think it would be great!

I just tested again both beta5 and the most recent build in OSX and I am still not able to trigger this bug.

I'm attaching the logs I got with the current valencia branch, maybe we can spot some differences:

Box checked:

```
May 22 13:30:27.682 - yamlconf: yamlconf_disk.go:84 Configuration changed programmatically, saving
May 22 13:30:27.747 - proxiedsites: proxiedsites.go:118 Configuration unchanged
May 22 13:30:27.747 - flashlight.statreporter: statreporter.go:84 Stat reporting turned off
May 22 13:30:27.747 - flashlight.client: client.go:88 Configure() called
May 22 13:30:27.749 - flashlight.client: client.go:93 Client configuration unchanged
May 22 13:30:27.749 - flashlight.logging: logging.go:90 Logging configuration unchanged
May 22 13:30:27.749 - flashlight.autoupdate: autoupdate.go:42 Autoupdate configuration unchanged
```

Box unchecked:

```
May 22 13:30:32.929 - flashlight.analytics: analytics.go:96 Successfully stopped analytics service
May 22 13:30:32.941 - yamlconf: yamlconf_disk.go:84 Configuration changed programmatically, saving
May 22 13:30:33.000 - proxiedsites: proxiedsites.go:118 Configuration unchanged
May 22 13:30:33.000 - flashlight.statreporter: statreporter.go:84 Stat reporting turned off
May 22 13:30:33.000 - flashlight.client: client.go:88 Configure() called
May 22 13:30:33.003 - flashlight.client: client.go:93 Client configuration unchanged
May 22 13:30:33.003 - flashlight.logging: logging.go:90 Logging configuration unchanged
May 22 13:30:33.003 - flashlight.autoupdate: autoupdate.go:42 Autoupdate configuration unchanged
```

**Comment by myleshorton** [comment] 2015-05-28 18:12
This should be all set now.

**Closed by myleshorton** 2015-05-28 18:12 UTC
Labels: Lantern 2.0, P1

**Comment by sheena3** [comment] 2015-05-28 18:14
@myleshorton is this ready to test ?

**Comment by myleshorton** [comment] 2015-05-28 18:17
There's no released version with that fix yet but will be testable with
beta 6.

On Thu, May 28, 2015 at 11:14 AM, sheena3 <notifications@github.com> wrote:

> @myleshorton <https://github.com/myleshorton> is this ready to test ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2480#issuecomment-106544439>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89
