### ISSUE TITLE
config.go:310 Could not fetch cloud config Unexpected response status: 503

### ISSUE THREAD

**Issue by uaalto** [getlantern/lantern#3170] opened 2015-09-18 12:27 UTC
```
{"extra":{"country":"","language":"zh","logLevel":"ERROR","osArch":"386","osName":"windows","osVersion":"","sessionUserAgents":"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; 360space): 13 requests; Microsoft-CryptoAPI/6.1: 3 requests; Post: 7 requests; Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E): 25 requests; Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1): 20 requests; ","timeZone":"CST","version":"2.0.6 (20150915.042827)"},"fullMessage":"ERROR flashlight.config: config.go:310 Could not fetch cloud config Unexpected response status: 503\n","hostname":"hidden","instanceid":"c87b5b26-921c-4154-9d59-54933430ff7d","locationInfo":"ERROR flashlight.config","message":"config.go:310 Could not fetch cloud config Unexpected response status: 503","osversion":"Windows 7 / Windows Server 2008 R2, SP1","timestamp":1442578343813}
```

**Comment by myleshorton** [comment] 2016-02-24 21:01
The latest version of this is on a different line in config.go:

```
config.go:246 Could not fetch cloud config Unexpected response status: 503
```

**Comment by myleshorton** [comment] 2016-09-07 21:54
Marking as duplicate of #3983 (the version of this from after fetcher.go was factored into a separate class).

**Closed by myleshorton** 2016-09-07 21:54 UTC
Labels: P2
