### ISSUE TITLE
No account management screen? 

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4777] opened 2016-06-23 23:06 UTC
![image](https://cloud.githubusercontent.com/assets/7925929/16323032/7d949a94-395c-11e6-8364-a7bafc399a10.png)

@myleshorton build 0623

**Comment by myleshorton** [comment] 2016-06-23 23:22
Thanks @p3rcya this is a duplicate of https://github.com/getlantern/lantern-desktop-ui/issues/139

**Closed by myleshorton** 2016-06-23 23:22 UTC
Labels: P1
