### ISSUE TITLE
IE 11-  Opens the browser but displays that "The page cannot be displayed" while opening on system start up

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2513] opened 2015-05-13 17:35 UTC
Steps:

1. Make IE as default browser.
2. Open lantern, change the setting to run lantern on system start up.
3. Restart the system.
4. Wifi connection is up before the lantern browser opens but still says that the page cannot be displayed. However, if I use show lantern to open the browser again, it works fine.

Note: Am unable to use the tab that is opening at the start up, it says "The page cannot be displayed" for all the websites. Once I start using a new tab, it is working fine.

**Comment by sheena3** [comment] 2015-06-10 17:16
Reopening this ticket.

I made IE as default browser and checked all the options in settings screen. Now when I restarted the system, it opens the browser but unable to open any websites (Just says that the page cannot be displayed). I tried in chrome to open gmail and it worked. 

I had to disconnect my wifi and connect it back to make it work in IE.

**Comment by myleshorton** [comment] 2015-07-13 20:03
Closing as a duplicate of #2719, as there's more discussion there.

**Closed by myleshorton** 2015-07-13 20:03 UTC
Labels: P2
