### ISSUE TITLE
Stupid team have lost the faith, turning a p2p free software into vps+charing version 

### ISSUE THREAD

**Issue by jxmlhdf** [getlantern/lantern#4942] opened 2016-07-08 02:12 UTC

**Comment by jxmlhdf** [comment] 2016-07-08 02:12
#4941

**Comment by myleshorton** [comment] 2016-07-08 02:42
Hi @jxmlhdf thank you for your feedback. The Lantern team has very much not lost faith, however, and we are more committed than ever to building the best possible tool to end censorship on the internet. The paid version is a fundamental part of that, as it's impossible to build great things with zero resources. We hope that you can understand that and believe that with this paid version future versions of Lantern will be even better, including the free version of Lantern.

**Closed** 2016-07-08 02:49 UTC

**Comment by myleshorton** [comment] 2016-07-08 02:57
@jxmlhdf I know you are a longtime Lantern user who has helped out with issues for many years. We don't want to lose you as a part of Lantern. I realize the recent changes have been a bit abrupt, but we really are trying to do what is best for the future of Lantern and the internet. How can we win back your faith in Lantern?

**Comment by frustreated** [comment] 2016-07-08 03:15
without lantern，we can not buy lantern.that's the point!

**Comment by CHN008** [comment] 2016-07-08 03:17
为什么不换回之前的p2p形式呢

**Comment by myleshorton** [comment] 2016-07-08 03:17
You're saying because Lantern's been having some issues recently right @frustreated? We're working hard on fixing all of the problems, and they're only related to the paid version in the sense that we've been very focused on getting this new version out so have maybe not done quite as many of the little things we normally do to make sure the normal version of Lantern is working great. That will change though -- it will be back up and reliable soon.

**Comment by myleshorton** [comment] 2016-07-08 03:18
We will very likely bring back p2p elements soon @CHN008, as there are certain elements of p2p we strongly believe will make Lantern much better in the coming year.

**Comment by JohnJZ** [comment] 2016-07-08 03:40
Either latern 2 or lantern 3 don't work today. So it seems it s not the problem of the new version? I feel like getting to know if it is because some technical issues of latern itself or the working of GFW?

Beside, peronally, I never believe free dinners will really cost you nothing. Hope the team are really working on promoting the latern effectiveness as they are telling us.

**Comment by p3rcya** [comment] 2016-07-08 03:54
I've posted explained why we are charging a fee in details here https://github.com/getlantern/forum/issues/362 please take a look

**Comment by myleshorton** [comment] 2016-07-08 04:03
Thanks @JohnJZ. We have been experiencing several issues over the past several days. If you are experiencing problems, can you please send:

1) What the problem is
2) What operating system you're on
3) What browser you're using
4) Please send your logs to me at myles@getlantern.org following these instructions:

https://github.com/getlantern/lantern/wiki/Emailing-lantern-logs

**Comment by maximdx** [comment] 2016-07-08 05:41
I think it's reasonable to pay for the better experience and I support for the non-free version.
Hope you can work this out as soon as possible. I had very good experience when I was using lantern!

**Comment by t3573393** [comment] 2016-07-08 05:52
i just want to get the point to point version , where is the code branch , we can use in this branch, thanks.

**Comment by myleshorton** [comment] 2016-07-08 05:56
Thanks @maximdx -- we hope to have things back up and working normally again very soon.

One major problem with the p2p versions @t3573393 is that they rely on users in uncensored regions running Lantern to act as access points. Currently by far most of our users are in censored regions.
