### ISSUE TITLE
IE can't open any site after logging off Windows with Lantern is running

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2776] opened 2015-07-21 03:04 UTC
Found while testing https://github.com/getlantern/lantern/issues/2741. Can be reproduced as following:

1. Open Lantern and de-select "Run on system start" option.
2. Restart Windows, or logout and login again.
3. Launch IE to visit any site.

That's because Lantern didn't have a chance to call `pacOff()` during system logout. Solution might be similar to https://github.com/getlantern/lantern/issues/2648, but with signal handler.

Alternatively we can find a way to let IE ignore bad PAC url, if any, as Chrome and Firefox can handle this situation.

**Comment by myleshorton** [comment] 2015-07-21 03:50
Interesting. I suspect @uaalto's changes for #2669 might do the trick too. That branch should be merged soon.

**Comment by fffw** [comment] 2015-07-21 04:56
It may be a bit different on Windows. Windows never triggers `SIGTERM`, it sends `WM_QUIT` instead.  Currently, the only place we handle Windows messages is in `systray`.

**Comment by fffw** [comment] 2015-07-21 04:59
Ref https://msdn.microsoft.com/en-us/library/xdkz3x12.aspx#code-snippet-2

**Comment by xiam** [comment] 2015-07-22 16:40
Bummer, still happening after #2669 

![screen shot 2015-07-22 at 11 39 08 am](https://cloud.githubusercontent.com/assets/385670/8831188/4c559a0a-3066-11e5-9ed2-e10c9be0dcdd.png)

**Comment by uaalto** [comment] 2015-07-22 16:46
@xiam Maybe you can try with this https://github.com/getlantern/lantern/commit/8bcc8431c493a331d44847049d290655e871f5d0, or even a slightly more aggressive code that runs the `exit(nil)` even if recover doesn't return `nil`?

**Comment by xiam** [comment] 2015-07-22 18:06
@uaalto The problem seems to be that the application is just killed without any kind of warning.

I am testing with a very simple snippet apart from Lantern:

```go
package main

import (
        "log"
        "os"
        "os/signal"
        "syscall"
)

func main() {
        log.Println("Waiting...")
        ch := make(chan os.Signal)
        signal.Notify(ch, syscall.SIGINT, syscall.SIGTERM)
        log.Println(<-ch)
}
```

When logging off the expected signal is not received (on Windows).

**Comment by xiam** [comment] 2015-07-22 18:11
@fffw do you think we can handle this within the systray code?

**Comment by fffw** [comment] 2015-07-22 18:18
@xiam Yes it's the only way I can think of for now. `systray` calls back to go code to clean up gracefully in the `WM_DESTROY` handler.

**Comment by myleshorton** [comment] 2015-07-22 18:27
QAing this might rely on first fixing #2791 @sheena3

**Comment by xiam** [comment] 2015-07-27 12:25
I've been dealing with this for a while, because this is a pretty annoying problem which is so easy to replicate:

* Run Lantern.
* Click start menu > Log Off.
* Log in again with the same user.
* Open IE.

It happens to me all time.

Following this guide I managed to capture an event of this kind (log off) on Windows XP:

https://support.microsoft.com/en-us/kb/310153

However, the same does not apply to Windows 7. I found that the shutdown behaviour changed since Vista:

https://msdn.microsoft.com/en-us/library/ms700677

I *think* that the above link provides what we need to detect an event of this kind, I'm going to try testing that and, if I succeed then I'll need a way to connect that event to the Lantern cleanup routine, any thoughts on the best way to do that?

**Comment by xiam** [comment] 2015-07-27 12:29
> Alternatively we can find a way to let IE ignore bad PAC url, if any, as Chrome and Firefox can handle this situation.

@fffw That also sounds like a good solution, do you have any tip on how to do that?

**Comment by fffw** [comment] 2015-07-27 13:28
@xiam I didn't find any method. It may not even possible to do that.

**Comment by fffw** [comment] 2015-07-27 13:59
@xiam I guess [`SetConsoleCtrlHandler `](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686016(v=vs.85).aspx) is more suitable and simpler for console program.

golang runtime has a [`SetConsoleCtrlHandler ` handler](http://golang.org/src/runtime/os_windows.c#L511), but it ignores CTRL_CLOSE_EVENT, CTRL_LOGOFF_EVENT, and CTRL_SHUTDOWN_EVENT. There's an existing issue https://github.com/golang/go/issues/6948 but it seems they don't plan to add it. By adding our own handler, it should be resolved.

**Comment by fffw** [comment] 2015-07-27 14:14
I don't have access to my Windows VM now but should be able to work on it tomorrow, unless @xiam you likes to play around with it.

**Comment by myleshorton** [comment] 2015-07-27 18:06
Hey @fffw what happened to the idea of capturing this from the system tray and notifying Lantern? I.e. in somewhere like:

https://github.com/getlantern/systray/blob/master/systray/systray/systray.cpp#L54

Add handling for WM_CLOSE and WM_QUIT and whatever else. Would that not work?

**Comment by xiam** [comment] 2015-07-27 18:10
Hey @myleshorton,

I already tried that but it only works on Windows XP (see details in my [previous message](https://github.com/getlantern/lantern/issues/2776#issuecomment-125186651)). I'm trying now with the [ShutdownBlockReason*](https://msdn.microsoft.com/en-us/library/ms700677) functions to see if I can get any further.

**Comment by myleshorton** [comment] 2015-07-27 18:20
So trying to add the new messages from Vista didn't work? Like WM_ENDSESSION? I didn't see the resolution to your proposal from that comment. Can you not still capture those same events from the system tray?

**Comment by xiam** [comment] 2015-07-27 18:26
@myleshorton Yes, none of these events aren't sent to the application, `WM_ENDSESSION` included.

According to the "Application Shutdown Changes" page, things changed started with Windows Vista:

> Also note that if your application has no visible top-level windows, it must use this API if it needs to successfully block shutdown. Such applications will automatically be terminated if they block shutdown without using the API.

Lantern has no visible windows and it's killed by the system without a warning.

Following the page I already managed to block the shutdown sequence on Windows 7 for a few seconds, I still don't find a complete solution, though.

**Comment by xiam** [comment] 2015-07-27 18:32
> Can you not still capture those same events from the system tray?

Yes, I gave up trying to making this work with Go, I'm working directly with the systray.

**Comment by xiam** [comment] 2015-07-28 00:38
I connected the `WM_QUERYENDSESSION` event to a new `OnExit` handler in the systray package, and I prevented the logoff window from killing Lantern:

![screen shot 2015-07-27 at 7 23 41 pm](https://cloud.githubusercontent.com/assets/385670/8920903/0feec342-3495-11e5-89f6-a22c6b539623.png)

However the `pacOff()` function does not work in this state:

```
Jul 28 00:21:54.753 - 0m33s DEBUG flashlight: pac.go:152 Unsetting lantern as system proxy
Jul 28 00:21:54.765 - 0m33s ERROR flashlight: pac.go:169 Unable to unset lantern as system proxy: Unable to execute C:\Users\John\AppData\Roaming\byteexec\pac-cmd.exe: exit status -1073741502
```

I suspect that new process creation is restricted when logging off, or maybe something else needs to be fixed within the pac command? I'll investigate more on this topic.

**Comment by xiam** [comment] 2015-07-28 01:21
I think we can also try calling `InternetSetOption` directly from systray.

**Comment by myleshorton** [comment] 2015-07-28 04:17
Oh very interesting @xiam! The pac code is honestly small enough that we could just automatically statically link the relevant functions to the system tray code without much trouble I think.

**Comment by xiam** [comment] 2015-07-28 15:59
> The pac code is honestly small enough that we could just automatically statically link the relevant functions to the system tray code without much trouble I think.

@myleshorton I thought that too and I tried but I still can't make it work. Maybe I am missing something else.

Here's the branch I am working on: [wip-2776-xiam](https://github.com/getlantern/lantern/tree/wip-2776-xiam)

Here is the [pacOff()](https://github.com/getlantern/lantern/blob/e5ab500041916020e55bf4d5ef51fe634ca22bdb/src/github.com/getlantern/systray/systray/systray/systray.cpp#L123) function. 

I'm using Visual Studio Community 2015, I had to update the `.sln` file to this VS version and it still compiles fine.

I order to build and replace the DLL code I added a (temporary) helper script `./rebuild-2776.sh` that I always execute after building the DLL.

For testing purposes I ask the DLL to print some messages to the console.

```
Jul 28 15:28:24.338 - 0m14s DEBUG flashlight: flashlight.go:382 Calling exit func
DEBUG flashlight: flashlight.go:382 Calling exit func
DEBUG flashlight: flashlight.go:382 Calling exit func
DEBUG flashlight: pac.go:152 Unsetting lantern as system proxy
DEBUG enproxy: conn_impl.go:45 Proxy connection to www.google.com:80 via 162.159.241.93:443 idle for 10s, closing
DEBUG enproxy: conn_impl.go:45 Proxy connection to www.google.com:80 via 162.159.241.54:443 idle for 10s, closing
ERROR flashlight: pac.go:169 Unable to unset lantern as system proxy: Unable to execute C:\Users\John\AppData\Roaming\byteexec\pac-cmd.exe: exit status -1073741502

DEBUG flashlight: pac.go:155 Unset lantern as system proxy
DEBUG flashlight: flashlight.go:385 No exit func remaining, exit now
DEBUG flashlight: flashlight.go:102 Lantern stopped
GOT SIGNAL 36
GOT SIGNAL 129
GOT SIGNAL 131
GOT SIGNAL 1
WM_CREATE
GOT SIGNAL 59
GOT SIGNAL 17
WM_QUERYENDSESSION
```

My test routine is very manual, after building the DLL and rebuilding Lantern I execute the `test-2776.sh` script to catch the output to a `log.txt` file, which I am watching with `tail -f` over a ssh session.

Then I press the *Start Menu* -> *Log off* menu action, I expect the `WM_QUERYENDSESSION` [message](https://github.com/getlantern/lantern/blob/e5ab500041916020e55bf4d5ef51fe634ca22bdb/src/github.com/getlantern/systray/systray/systray/systray.cpp#L82) to be printed and that happens, the pacOff functions exists with 0, so thats fine...

```
Jul 28 15:45:21.540 - 0m9s DEBUG flashlight: flashlight.go:382 Calling exit func
DEBUG flashlight: flashlight.go:382 Calling exit func
DEBUG flashlight: flashlight.go:382 Calling exit func
DEBUG flashlight: pac.go:152 Unsetting lantern as system proxy
ERROR flashlight: pac.go:169 Unable to unset lantern as system proxy: Unable to execute C:\Users\John\AppData\Roaming\byteexec\pac-cmd.exe: exit status -1073741502

DEBUG flashlight: pac.go:155 Unset lantern as system proxy
DEBUG flashlight: flashlight.go:385 No exit func remaining, exit now
DEBUG flashlight: flashlight.go:102 Lantern stopped
GOT SIGNAL 36
GOT SIGNAL 129
GOT SIGNAL 131
GOT SIGNAL 1
WM_CREATE
GOT SIGNAL 59
GOT SIGNAL 17
WM_QUERYENDSESSION
pacOff(): 0
```

But after logging in again, the damn IE still fails.

I also added a new [systray.AtExit](https://github.com/getlantern/lantern/blob/e5ab500041916020e55bf4d5ef51fe634ca22bdb/src/github.com/getlantern/systray/systray.go#L61) function for systray, which is called from the [systray_menu_quit](https://github.com/getlantern/lantern/blob/e5ab500041916020e55bf4d5ef51fe634ca22bdb/src/github.com/getlantern/systray/systray/systray/systray.cpp#L87) function pointer. The systray.AtExit function is just bound to [a call to exit(nil)](https://github.com/getlantern/lantern/blob/e5ab500041916020e55bf4d5ef51fe634ca22bdb/src/github.com/getlantern/flashlight/systray.go#L31) which is also executed:

```
DEBUG flashlight: pac.go:152 Unsetting lantern as system proxy
ERROR flashlight: pac.go:169 Unable to unset lantern as system proxy: Unable to execute C:\Users\John\AppData\Roaming\byteexec\pac-cmd.exe: exit status -1073741502
``` 

If we remove the call to [systray_menu_quit](https://github.com/getlantern/lantern/blob/e5ab500041916020e55bf4d5ef51fe634ca22bdb/src/github.com/getlantern/systray/systray/systray/systray.cpp#L87) then the "Waiting for Lantern" screen will pop up, but still, the pac settings are not removed.

@fffw, @myleshorton I'll continue digging on this but it would be awesome if you could help me checking out my branch. Thanks!

**Comment by xiam** [comment] 2015-07-28 17:25
I am pretty sure the `pacOff()` function is working, if I call it from any other place, such as when clicking the "Show Lantern" menu action, it effectively removes pac settings.

```
		case WM_MENUCOMMAND:
			{
				int menuId = GetMenuItemId(wParam);
				if (menuId != -1) {
					printf("pacOff(): %d\n", pacOff());
					printf("menu item id: %d\n", menuId);
					systray_menu_item_selected(menuId);
				}
			}
			break;
```

**Comment by myleshorton** [comment] 2015-07-28 17:31
> But after logging in again, the damn IE still fails.

And the proxy settings are what they were before right, i.e. they're still set to use Lantern's pac file on restart even though pacOff() returned an exit code of 0?

**Comment by xiam** [comment] 2015-07-28 17:41
> And the proxy settings are what they were before right, i.e. they're still set to use Lantern's pac file on restart even though pacOff() returned an exit code of 0?

Yes @myleshorton, even though pacOff() returns 0. 

![screen shot 2015-07-28 at 12 37 54 pm](https://cloud.githubusercontent.com/assets/385670/8938653/837ea8aa-3525-11e5-9ec4-bfe516097761.png)

The only exception is when I attach `pacOff()` to the `WM_MENUCOMMAND` event so that it runs when I click "Show Lantern", in that case proxy settings are effectively removed.

**Comment by xiam** [comment] 2015-07-28 17:42
Hmm... maybe that "Automatically detect settings" checkbox could be useful.

**Comment by xiam** [comment] 2015-07-28 17:52
Yay, it looks like checking "Automatically detect settings" fixes the whole problem with IE, even though the Address remains in the same place. That "Automatically detect settings" checkbox is not enabled by the pac-cmd, I think we can try and see.

**Comment by myleshorton** [comment] 2015-07-28 18:12
Interesting. So maybe "Automatically detect settings" triggers it to work similar to Chrome or FF where it doesn't use the proxy if the proxy isn't there. Something like that?

**Comment by xiam** [comment] 2015-07-28 18:34
Yeah! This is great. IE now detects when the proxy is not responding and tries accessing the site directly. :-). I tested the log off routine and IE continued working, even thought the pac settings where still as Lantern left them. In one on my tests IE showed the "This page can't be displayed" message but after a couple of seconds and clicking "refresh" the message was gone.

**Comment by myleshorton** [comment] 2015-07-28 18:54
Oh cool! OK let's just use that then. That sound ok @fffw?

**Comment by xiam** [comment] 2015-07-28 19:32
After further testing I found that this is not working every time. I don't know why, sometimes it works and sometimes it doesn't, for no apparent reason.

I've noticed that if I open the "LAN Settings" and click OK it starts to work again, even without changing anything.

My current wip is here: https://github.com/getlantern/lantern/tree/issue-2776

Maybe we need to play a bit more with the [available settings](https://msdn.microsoft.com/en-us/library/windows/desktop/aa385145(v=vs.85).aspx) for network configuration.

**Comment by fffw** [comment] 2015-07-29 01:29
I guess that opening the "LAN Settings" page and clicking OK will trigger a recheck of LAN setting, though login to windows will not!

I did incorrectly think that "Automatically detect settings" can resolve this issue, even created https://github.com/getlantern/lantern/issues/2746#issuecomment-122149321 to attempt. Now at least we know neither `AUTO_PROXY_FLAG_ALWAYS_DETECT` nor `PROXY_TYPE_AUTO_DETECT` can fix it.

@xiam What you faced is a bug of IE. From http://blogs.msdn.com/b/ieinternals/archive/2013/10/11/web-proxy-configuration-and-ie11-changes.aspx, section "IE10+ Regression on System Shutdown", it says "No fix for this issue (also present in IE11) is yet available", and the workaround is not simple.

I'm curious why no user ever reported this. They accustomed to open LAN setting and toggle the checkbox manually when it happens?

**Comment by xiam** [comment] 2015-07-29 17:07
Thanks a lot @fffw, now we have the reason for the pac-cmd's code not working on system shutdown. At least we already know that's a dead end.

> Unfortunately, as a part of this update, a regression was inadvertently introduced. **Code that attempts to change the WinINET proxy setting during a system shutdown (like Fiddler’s shutdown code, for instance) will find that the APIs return success, but upon restart you will see that the proxy settings change was discarded**. No fix for this issue (also present in IE11) is yet available. 

> I'm curious why no user ever reported this. They accustomed to open LAN setting and toggle the checkbox manually when it happens?

I don't know either but I think that it is not too evident that this problem is caused by Lantern, I mean, Lantern is not running, it looks like and IE problem.

@fffw, @myleshorton I think we should think of another strategy here, could we permanently attach Lantern at startup just to clean pac settings? And then make it exit, unless the user explicitly wants to run Lantern at startup. I think we could also attach a `.bat` script that would call `pac.exe off` everytime the system starts or a users logs in. It's not the best solution and I frankly don't like it, but I think we don't have too many options to choose from.

**Comment by myleshorton** [comment] 2015-07-30 18:13
Interesting @xiam, and thanks for that great reference @fffw. I agree just always running on startup and cleaning up if necessary and then shutting down if Lantern is not set to run on startup sounds like a good approach. I like it.

In 2.0.0 I added the -startup flag whenever Lantern is run on system startup, so we now know when it's run at startup. So we should be able to implement a solution like the above without too much trouble. Great thinking @xiam!

**Comment by xiam** [comment] 2015-07-30 18:46
Great, I'll take another stab at it using the proposed workaround.

**Comment by xiam** [comment] 2015-07-30 23:00
Instead of messing with `-startup` I added a new `-clear-proxy-settings` option that does exactly what we need. When the user checks "Run Lantern on system start" we set the registry key that uses the `-startup` flag, and when that setting is unchecked the registry we set the `-clear-proxy-settings` flag instead.

Now, I only need to set the `-clear-proxy-settings` into the registry when Lantern runs for the first time. I think this would be a case for the upcoming `.lanternrc` file so I'll wait for that PR to be able to use it and finish this issue.

I tested with log off and restart and it solved the problem, finally.

I only did this fix for Windows because that's the platform that is failing.

**Comment by xiam** [comment] 2015-07-30 23:03
Current wip https://github.com/getlantern/lantern/tree/issue-2776-clean-on-start (I'll clean up my other branches once we finish and test the current fix)

**Comment by xiam** [comment] 2015-07-30 23:10
Oh, I think we can also use the installer to set the registry key. https://github.com/getlantern/lantern/pull/2856

**Comment by sheena3** [comment] 2015-08-21 18:28
I am working on IE 11. It is still showing "This page can't be displayed" when restarting the system while Lantern is running. It takes a while for IE to work normal.

**Comment by sheena3** [comment] 2015-08-21 18:33
This is working fine when I Logout with Lantern running and then login.

**Comment by sheena3** [comment] 2015-08-21 18:34
Should I close this and re-open 2719?

**Comment by myleshorton** [comment] 2015-08-24 20:27
I can't reproduce this one either @sheena3. I'm running Windows 8.1 and IE 11. How about you?

**Comment by sheena3** [comment] 2015-08-25 17:27
I am using the same @myleshorton.

These are the steps that I followed,

1. Make IE default browser
2. Run Lantern and make sure that Run Lantern automatically on system start up is enabled, (FYI - I had proxy all traffic option disabled when doing this test if it will make any difference)
3. Restart the system 
4. Lantern starts running and can be seen in the system tray
5. Use 'Show Lantern' to open the browser.

When IE opens, it displays that the page can't be displayed.

**Comment by DavidSuccess** [comment] 2015-08-26 04:06
Win Start -->run-->regedit
-->HKEY_CURRENT_USER-->software-->Microsoft-->Windows-->Internet Settings

delete AutoConfigUrl
delete ProxyServer
reset value of ProxyEnable to 0

2015-08-26 1:27 GMT+08:00 sheena3 <notifications@github.com>:

**Comment by myleshorton** [comment] 2016-04-26 14:31
Hey @sunshine19090 I'm wondering if this one is still an issue. Can you still reproduce this based on your last comment?

**Comment by sunshine19090** [comment] 2016-04-26 18:02
Nope @myleshorton. I haven't come across this issue in 2.1.0 or releases after that. But I still see this happeneing in Edge and Safari after restarting but not consistent.

**Comment by myleshorton** [comment] 2016-04-26 19:08
OK should we close this one then and open others as they pop up @sunshine19090?

**Comment by sunshine19090** [comment] 2016-04-26 19:10
Yeah, I agree @myleshorton. I think we already closed the other ones. I will check it out.

**Closed by sunshine19090** 2016-04-26 19:10 UTC
Labels: P1, QA
