### ISSUE TITLE
[mobile] sign in to pro not working 

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4752] opened 2016-06-21 18:32 UTC
Heres how i found this issue, I bought pro, then signed out.   I then went "sign in to Pro" on the menu and entered my email.  After this i just got a "processing request" notification, and the spinner, but nothing changed it just kept spinning. 
@atavism @myleshorton

**Comment by sunshine19090** [comment] 2016-06-21 18:46
Duplicate of #4737.

**Closed** 2016-06-21 18:46 UTC
Labels: duplicate
