### ISSUE TITLE
Exclude certain requests from bandwidth tracking

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#4602] opened 2016-06-09 04:35 UTC
Can we exclude specific requests from counting toward total bandwidth usage? For instance, the newsfeed is ~ 1MB, and it's refreshed every time the app is opened. This contributes significantly to the user's available free monthly data.

**Comment by oxtoacart** [comment] 2016-06-09 22:25
Duplicate of https://github.com/getlantern/lantern/issues/4508

**Closed by oxtoacart** 2016-06-09 22:25 UTC
