### ISSUE TITLE
Add errcheck, go vet, go xxx -race, etc to git hooks

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2787] opened 2015-07-21 21:55 UTC

**Comment by uaalto** [comment] 2015-07-22 11:32
go test -race it's very nice, but it takes long. There are two hooks I would set up: pre-commit and pre-push.

* pre-commit: run things like go fmt, errcheck and go vet (and possibly go lint?)
* pre-push: run go test -race.

Also, the hooks can't be added to the repo AFAIK (to avoid them installed silently I believe). So I would just add them to a folder called git-hooks and expect the users to just copy them to .git/hooks.

What do you think about these approaches?

**Comment by myleshorton** [comment] 2015-07-22 13:03
I actually wouldn't be against just universally applying them in the committed hooks. What don't you like about that?

I think we could also consider generally building with ```go build -race``` or ```go run -race``` while in development. For example, running Lantern just now with ```go build -race``` flagged race conditions in the local stats serving, logging, and geolookup. We might get those during tests, but might not. Maybe both?

**Comment by uaalto** [comment] 2015-07-22 13:30
You mean everything in pre-commit?
The only argument against that is the time it may take to run all tests, but I'm ok with it.

**Comment by uaalto** [comment] 2015-07-26 11:57
I will add these hooks after these issues (https://github.com/getlantern/lantern/issues/2807 and https://github.com/getlantern/lantern/issues/2808) are done, as it seems to me that it makes more sense to provide them with a code base that actually passes.

**Comment by uaalto** [comment] 2015-07-26 12:01
Just confirming with you @myleshorton:

* Everything in a pre-commit hook sounds right? (just taking into account the time it will take to do so, although I can add a filter so only changed packages are tested).
* Does providing the hooks inside a `/git-hooks` folder seem right, or do you think there is a better place for it? A second option would be to provide the files (namely just one if there only pre-commit hooks) in `/`.

**Comment by uaalto** [comment] 2015-07-27 09:45
This project would be a perfect fit: https://github.com/maruel/pre-commit-go

**Comment by myleshorton** [comment] 2015-07-28 18:59
Hey sorry for the delay @uaalto. I would not do the tests pre-commit sorry. Maybe just pre-push? Thanks!

**Comment by uaalto** [comment] 2015-07-28 21:14
Sure! That's what I believe too, otherwise it will bring too much overhead into the development process. I made this preliminary version. You only need to save it as .git/hooks/pre-push
Actually, if you want it to be pre-commit, just rename it (it's better if you want to try it out without actually pushing).

I could also add `go test -race`. What do you think?

```
﻿#!/bin/sh

# Git pre-push hook for the Lantern project
#
# Maintainer Ulysses Aalto
# uaalto@getlantern.org

# Exit immediately if a command exits with a non-zero status.
set -e

cd src/github.com/getlantern

which errcheck >/dev/null || (echo "Unable to find errcheck, please install it: \`go get github.com/kisielk/errcheck\`" && exit 1)
which golint >/dev/null || (echo "Unable to find golint, please install: \`go get -u github.com/golang/lint/golint\`" && exit 1)

echo "\033[0;34m*** Running errcheck ***\033[0m" && \
for dir in *; do
  errcheck github.com/getlantern/$dir || \
    echo "\033[0;31merrcheck returned error analyzing the package '$dir'\033[0m" && \
    echo "Please, fix and push again" && \
    exit 1
done
echo "\033[1;34merrcheck run successfully\033[0m"

echo "\033[0;34m*** Running Go vet ***\033[0m" && \
for dir in *; do
  go vet github.com/getlantern/$dir || (\
    echo "\033[0;31mgo vet returned error analyzing the package '$dir'\033[0m"
    echo "Please, fix and push again" && \
    exit 1)
done
echo "\033[1;34mGo vet run successfully\033[0m"

echo "\033[0;34m*** Running Golint ***\033[0m" && \
for dir in *; do
  golint github.com/getlantern/$dir || (\
    echo "\033[0;31mgo vet returned error analyzing the package '$dir'\033[0m"
    echo "Please, fix and push again" && \
    exit 1)
done
echo "\033[1;34mGo vet run successfully\033[0m"

```

**Comment by myleshorton** [comment] 2015-07-28 21:18
Nice! I didn't know about ```set -e``` -- cool.

I would say either "xxx run successful" or "xxx ran successfully" instead of "xxx run successfully" but otherwise looks great!

**Comment by uaalto** [comment] 2015-07-28 21:21
:) fixed typo.

Two quick questions:
* Should I add `go test -race`?
* About distribution: what do you think about saving this file in the root folder and adding instructions to copy it manually in the README? This way it would be optional. Or did you have any other approach in mind?

**Comment by myleshorton** [comment] 2015-07-28 21:26
I think we be a little bit dictatorial and should just put it in the repo in the /hooks directory. That would work right?

What about go test -race in a pre-push? Or maybe we run it manually? Try it and see if it's too annoying perhaps?

**Comment by uaalto** [comment] 2015-07-28 21:35
The problem is that the /hooks directory is not committed into the public repo. So we need some form of manual installation. That is as simple as copying the file, of course.

One possibility I was thinking about is running `go test -race`, as well as the other commands just in those folders we have changes. I'll try to figure out if there is a reasonable way to do that.

**Comment by uaalto** [comment] 2015-07-28 22:21
I think we really can't enforce hooks: https://stackoverflow.com/questions/3703159/git-remote-shared-pre-commit-hook

**Closed** 2015-08-07 19:58 UTC
Labels: P2
