### ISSUE TITLE
Ubuntu - Lantern is not running automatically after system start up even when it is set to run on system start up

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3547] opened 2016-02-10 21:27 UTC
Checked with both chrome and Firefox.

**Comment by rushcheyo** [comment] 2016-02-11 05:24
Not only Ubuntu, But also OS X.

**Comment by kashu** [comment] 2016-02-19 12:42
I have been using Lantern for half a year.
This startup method always works for my Xubuntu 14.04.3 and I think you will like it.
```
/usr/bin/nohup sh -c "/bin/sleep 8 && /usr/lib/lantern/lantern.sh -addr 0.0.0.0:8787 -startup=true -role=client &> /dev/null" &> /dev/null
```
![](http://ww1.sinaimg.cn/large/9c4ddab1gw1f14xguqpk6j20qw0d17aq.jpg)

**Comment by noob9527** [comment] 2016-04-23 15:24
@kashu 

能解释下 "-role=client" 这个参数的作用吗?,我加上这个参数后无法启动lantern

我的lantern版本是2.1.2
OS版本是 ubuntu16.04

**Comment by kashu** [comment] 2016-04-23 21:59
把这个参数删了，不要加

**Comment by uaalto** [comment] 2016-04-26 23:37
issue review: agreed wirh priority

**Comment by uaalto** [comment] 2016-04-27 15:32
Duplicate of https://github.com/getlantern/lantern/issues/3505
Closing this, the other is older.

**Closed by uaalto** 2016-04-27 15:32 UTC
Labels: P1
