### ISSUE TITLE
There is no information about the promotion that is applied at the end of purchasing pro

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4734] opened 2016-06-20 21:09 UTC
I used referral code while selecting 2 year plan. After check out, I get the thank you message but no information about the promotion that is applied.  The new account management screen doesn't have this detail (ticketed separately).

@Derekf5 @carsonefv @p3rcya @myleshorton

**Comment by p3rcya** [comment] 2016-06-20 22:59
Yeah, it should say something like, thank you for purchasing Lantern Pro, you and your friend each get 3 months free added to your plan.

**Comment by Derekf5** [comment] 2016-06-21 14:32
This is spec'd out in #4577 and #4683 for mobile.

**Comment by myleshorton** [comment] 2016-06-21 22:00
Yup this is a duplicate of #4577

**Closed by myleshorton** 2016-06-21 22:00 UTC
Labels: Design
