### ISSUE TITLE
Update cloud config to include `trusted` field to servers

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2534] opened 2015-05-17 01:00 UTC
At least cloud.2.0.0-nl.yaml.gz doesn't have `trusted` field. It prevents plain http sites from being proxied.

@aranhoide From my impression, you already updated some cloud config file. Seems I remembered incorrectly?

**Comment by aranhoide** [comment] 2015-05-17 02:07
I updated cloud.default.yaml.gz and cloud.cn.yaml.gz, which were the ones supposed to be used by beta5, which IIRC is the one where `trusted` was introduced.

Now we're changing the configurl to `https://config.getiantem.org/cloud.yaml.gz`, which includes `trusted` fields.  https://github.com/getlantern/lantern/pull/2522 changes lantern-android to use this new URL, so it should fix this issue.

**Comment by aranhoide** [comment] 2015-05-17 02:08
Since I think only lantern-android was pointing to cloud.2.0.0-nl.yaml.gz, I'll mark this as PENDING MERGE.  Feel free to unmark if this comes up in any other context.

**Comment by fffw** [comment] 2015-05-17 11:48
Thanks @aranhoide

**Comment by myleshorton** [comment] 2015-05-18 18:20
I'm confused how this might have happened then, especially if that was the cause of the proxy errors @sheena3 saw. If she's running beta 5, that would hit the new URLs. Maybe they still wouldn't correctly override the ones on disk, or maybe she's using an outdated custom lantern.yaml?

**Comment by aranhoide** [comment] 2015-05-18 18:33
She would hit the old URLs because the `cloudconfig` URL in her old lantern.yaml would override the built-in one.

So, come to think about it, we really need to update cloud.2.0.0-nl.yaml.gz to

- point to the new one

- have its own servers as `trusted: true` so the new one can be fetched.

This can be done by uploading the latest cloud.yaml.gz with the 2.0.0-nl name and with the cloudconfig overriden.  I'll just do this.

**Comment by aranhoide** [comment] 2015-05-18 18:40
I just did as in the previous comment.  This should be fixed; let's reopen if it ever happens again.

**Closed by aranhoide** 2015-05-18 18:40 UTC
Labels: P1, PENDING MERGE

**Comment by myleshorton** [comment] 2015-05-18 18:43
Awesome @aranhoide thanks!
