### ISSUE TITLE
Lantern has been interfered by GFW  in China

### ISSUE THREAD

**Issue by jxmlhdf** [getlantern/lantern#2931] opened 2015-08-13 02:50 UTC
Lantern has been blocked since this morning in China
Hope the next version will be most faster and more stability

**Comment by fffw** [comment] 2015-08-13 03:23
@jxmlhdf From real time monitor, Lantern still works in China. What's your finding by saying Lantern has been blocked?

**Comment by jxmlhdf** [comment] 2015-08-13 03:53
This morning Lantern start to randomly selected different regions servers results in extreme slow connection speed, moreover, there are evidences shown that JP server has been interfered results in lantern's IP has switched in between two IP address instantly

**Comment by myleshorton** [comment] 2015-08-13 03:57
@jxmlhdf Lantern will often switch the server you connect to, and I wouldn't associate that with blocking. Are you still able to access blocked web sites.

**Comment by jxmlhdf** [comment] 2015-08-13 04:31
Thanks for all the feedback, the slowly connection speed may caused by the instability of JP sever.
It is recommenced that close this issue

**Comment by jxmlhdf** [comment] 2015-08-13 10:27
It is obvious that GFW began to interfered Lantern JP server results in Lantern connect EU server instantly . The connection speed now is extreme slowly

**Comment by fffw** [comment] 2015-08-13 10:48
We spotted severe packet loss from certain place to Lantern JP server. It depends on where you are and which ISP you are using. You can ping the server ip assigned to your Lantern instance to make sure the slowness is not caused by network congestion.

**Comment by jxmlhdf** [comment] 2015-08-13 11:20
Thank for your feedback, the suspected ISP in China is "China Unicom". The place where has packet loss is southeast of China. Hope team could figured the way to prevent this issue occur

**Comment by jxmlhdf** [comment] 2015-08-13 11:26
![screen shot 2015-08-13 at 19 22 17](https://cloud.githubusercontent.com/assets/12945364/9248759/327b62da-41f1-11e5-9785-2ab4eb14f6e1.png)

**Comment by jxmlhdf** [comment] 2015-08-13 11:40
![screen shot 2015-08-13 at 19 40 29](https://cloud.githubusercontent.com/assets/12945364/9248962/2e13c5c8-41f3-11e5-8fe6-70d787fa2ed4.png)

**Comment by aranhoide** [comment] 2015-08-13 18:29
@jxmlhdf just checking: are things any better if you stop lantern and start it again, or do you get exactly the same problems?

**Comment by aranhoide** [comment] 2015-08-13 20:41
@jxmlhdf another thing: are you using any VPN?  If you visit whatismyip.com what IP do you get reported (please don't say that here; reply to aranhoide@getlantern.org istead)?

**Comment by myleshorton** [comment] 2015-08-19 20:58
From our reports it sounds like this was a temporary network disruption, but feel free to open it again @jxmlhdf

**Closed by myleshorton** 2015-08-19 20:58 UTC
