### ISSUE TITLE
User report slow speed even after purchasing Pro

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4885] opened 2016-07-03 06:38 UTC
3.0.2 85.8KB/s while 20160621is 2MB/s
![image](https://cloud.githubusercontent.com/assets/7925929/16544128/f507e326-40ad-11e6-90d7-a0d532bbdc54.png)

![image](https://cloud.githubusercontent.com/assets/7925929/16544132/0621f48a-40ae-11e6-87d8-2b9adf83b43f.png)

User reported on https://github.com/getlantern/forum/issues/272#issuecomment-230138134

**Comment by fffw** [comment] 2016-07-03 09:43
One clue is that user was initially assigned 6 servers at 0m4s, but got 1 server from the config at 1m24s. Trying to dig more from the logs.

**Comment by fffw** [comment] 2016-07-03 09:56
The good news is: I can see it locally, should be not difficult to debug.

**Comment by fffw** [comment] 2016-07-03 10:03
Ok so the config is correct when fetching through DDF, but not when fetching from CloudFlare. I guess it's lacking of some headers.

**Comment by fffw** [comment] 2016-07-03 11:58
Working on a fix of https://github.com/getlantern/http-proxy-lantern/issues/44, which should fix the main cause of this issue.

**Comment by myleshorton** [comment] 2016-07-03 15:02
Oh that could explain it fully @fffw - it works with ddf but not CF, so
would have worked at least sometimes in staging.

**Comment by p3rcya** [comment] 2016-07-08 18:47
Another user upload logs for both win and android here https://github.com/getlantern/forum/issues/411#issue-164513002

**Comment by GD-HBX** [comment] 2016-07-09 06:20
from [getlantern/forum#411 (comment)](https://github.com/getlantern/forum/issues/411)：
Telecommunications speed is very slow, please solve!
It looks like our local ISP is limiting your purchase VPS network speed, because I use other shadowsocks (Japan VPS provider) speed faster than you, do not know how your server is assigned.
![ma](https://cloud.githubusercontent.com/assets/3373783/16686203/1a104c46-4543-11e6-8bd8-595df9d55dfc.png)
Comparison of different devices in the same network:
Telecom:
 [Android_lantern_Telecom.log.txt](https://github.com/getlantern/forum/files/354092/Android_lantern_Telecom.log.txt)
 [win_lantern_Telecom.log.txt](https://github.com/getlantern/forum/files/354093/win_lantern_Telecom.log.txt)

CMCC（Android not work，only win work）:
 [Android_lantern_CMCC_notwork.log.txt](https://github.com/getlantern/forum/files/355421/Android_lantern_CMCC_notwork.log.txt)
 [win_lantern_CMCC_work.log.txt](https://github.com/getlantern/forum/files/355422/win_lantern_CMCC_work.log.txt)

Another Android news flow has bug, watching the news into a return to the list of news flow must become blank and then refreshes the news flow. This bug has been loop ...!

From Google Translation

**Comment by p3rcya** [comment] 2016-07-09 06:23
@GD-HBX Thanks for the log. As for the android newsfeed, the current version has it by default off but we'll look into it as well.

**Comment by p3rcya** [comment] 2016-07-09 06:56
User reported android version is slow for accessing Google Play or videos https://github.com/getlantern/forum/issues/446#issue-164653691 log has been sent in app

**Comment by p3rcya** [comment] 2016-07-09 18:06
More log on slow speed even after purchasing pro
https://github.com/getlantern/forum/issues/451#issuecomment-231547008

**Comment by p3rcya** [comment] 2016-07-10 01:21
More complaint https://github.com/getlantern/forum/issues/466#issue-164693152 no log yet

**Comment by comkinfisher** [comment] 2016-07-10 07:24
![image](https://cloud.githubusercontent.com/assets/20350563/16712149/280e16c0-46b0-11e6-87bd-187ebb86f432.png)

[lantern update.txt](https://github.com/getlantern/lantern/files/355883/lantern.update.txt)

first, thanks for the fix last night (if there was one) :D, I was able to watch youtube at stable 720p resolution since 11pm in China.

However, another speed issue started since 7am this morning, as you can see from the pic, 144p resolution is as clear as  I can get so far, 

not sure what caused this problem but it seems lantern slows my entire network somehow, so I'm uploading my log now, hope can help out in some way.

**Comment by p3rcya** [comment] 2016-07-10 07:35
More log 
[log.zip](https://github.com/getlantern/lantern/files/355903/log.zip)

**Comment by p3rcya** [comment] 2016-07-10 07:46
More log: 
[lantern - 副本.txt](https://github.com/getlantern/lantern/files/355907/lantern.-.txt) from https://github.com/getlantern/forum/issues/478

**Comment by p3rcya** [comment] 2016-07-10 08:02
More log https://github.com/getlantern/forum/issues/480#issuecomment-231576034

**Comment by p3rcya** [comment] 2016-07-10 08:03
If this issue is caused by network conditions, please check https://github.com/getlantern/lantern-internal/issues/36

**Comment by comkinfisher** [comment] 2016-07-10 08:11
page 404 please check

**Comment by p3rcya** [comment] 2016-07-11 18:47
More complaints with log https://github.com/getlantern/forum/issues/475#issuecomment-231782139

**Comment by p3rcya** [comment] 2016-07-12 04:56
More log https://github.com/getlantern/forum/issues/358#issuecomment-231937072

**Comment by p3rcya** [comment] 2016-07-12 08:16
More log https://github.com/getlantern/forum/issues/538

**Comment by myleshorton** [comment] 2016-07-12 16:22
Are you able to reproduce this one @p3rcya? Either in terms of:

1) Free being faster than pro
2) 2.2.5 being faster than 3.0.6
3) 2.2.5 being faster than pro

**Comment by p3rcya** [comment] 2016-07-12 19:01
I cannot do the reproduction because of my network condition. But users do reported 1).

**Comment by p3rcya** [comment] 2016-07-14 18:07
More slow log https://github.com/getlantern/forum/issues/606#issuecomment-232676053 Download Speed: 20 kbps
Upload Speed: 1.15 Mbps

**Comment by p3rcya** [comment] 2016-07-15 06:31
More log https://github.com/getlantern/lantern/issues/5020#issuecomment-232862574

**Comment by p3rcya** [comment] 2016-07-15 17:59
more log https://github.com/getlantern/forum/issues/645#issue-165824289

**Comment by p3rcya** [comment] 2016-07-20 05:18
More log https://github.com/getlantern/lantern/issues/5053

**Comment by myleshorton** [comment] 2016-08-08 20:44
Closing in favor of https://github.com/getlantern/lantern-internal/issues/36 (essentially a duplicate).

**Closed by myleshorton** 2016-08-08 20:44 UTC
Labels: P1
